// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationDelivery struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Channel     string             `json:"channel"`
	Provider    string             `json:"provider"`
	Status      string             `json:"status"`
	FailureCode pgtype.Text        `json:"failure_code"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type NotificationEvent struct {
	ID                  pgtype.UUID        `json:"id"`
	NotificationEventID string             `json:"notification_event_id"`
	CustomerReference   string             `json:"customer_reference"`
	Category            string             `json:"category"`
	EventType           string             `json:"event_type"`
	TitleKey            string             `json:"title_key"`
	BodyKey             string             `json:"body_key"`
	ResourceType        string             `json:"resource_type"`
	ResourceID          string             `json:"resource_id"`
	ActionPath          pgtype.Text        `json:"action_path"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}
