// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventByKey = `-- name: GetEventByKey :one
SELECT id, notification_event_id, customer_reference, category, event_type, title_key, body_key, resource_type, resource_id, action_path, created_at
FROM notification.events
WHERE notification_event_id = $1
`

func (q *Queries) GetEventByKey(ctx context.Context, notificationEventID string) (NotificationEvent, error) {
	row := q.db.QueryRow(ctx, getEventByKey, notificationEventID)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.NotificationEventID,
		&i.CustomerReference,
		&i.Category,
		&i.EventType,
		&i.TitleKey,
		&i.BodyKey,
		&i.ResourceType,
		&i.ResourceID,
		&i.ActionPath,
		&i.CreatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one
INSERT INTO notification.deliveries (
    event_id, channel, provider, status, delivered_at
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (event_id, channel) DO NOTHING
RETURNING id, event_id, channel, provider, status, failure_code, delivered_at, created_at
`

type InsertDeliveryParams struct {
	EventID     pgtype.UUID        `json:"event_id"`
	Channel     string             `json:"channel"`
	Provider    string             `json:"provider"`
	Status      string             `json:"status"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, insertDelivery,
		arg.EventID,
		arg.Channel,
		arg.Provider,
		arg.Status,
		arg.DeliveredAt,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Channel,
		&i.Provider,
		&i.Status,
		&i.FailureCode,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO notification.events (
    id, notification_event_id, customer_reference, category, event_type,
    title_key, body_key, resource_type, resource_id, action_path
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10
)
ON CONFLICT (notification_event_id) DO NOTHING
RETURNING id, notification_event_id, customer_reference, category, event_type, title_key, body_key, resource_type, resource_id, action_path, created_at
`

type InsertEventParams struct {
	ID                  pgtype.UUID `json:"id"`
	NotificationEventID string      `json:"notification_event_id"`
	CustomerReference   string      `json:"customer_reference"`
	Category            string      `json:"category"`
	EventType           string      `json:"event_type"`
	TitleKey            string      `json:"title_key"`
	BodyKey             string      `json:"body_key"`
	ResourceType        string      `json:"resource_type"`
	ResourceID          string      `json:"resource_id"`
	ActionPath          pgtype.Text `json:"action_path"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (NotificationEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.NotificationEventID,
		arg.CustomerReference,
		arg.Category,
		arg.EventType,
		arg.TitleKey,
		arg.BodyKey,
		arg.ResourceType,
		arg.ResourceID,
		arg.ActionPath,
	)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.NotificationEventID,
		&i.CustomerReference,
		&i.Category,
		&i.EventType,
		&i.TitleKey,
		&i.BodyKey,
		&i.ResourceType,
		&i.ResourceID,
		&i.ActionPath,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliveriesForEvent = `-- name: ListDeliveriesForEvent :many
SELECT id, event_id, channel, provider, status, failure_code, delivered_at, created_at
FROM notification.deliveries
WHERE event_id = $1
ORDER BY channel
`

func (q *Queries) ListDeliveriesForEvent(ctx context.Context, eventID pgtype.UUID) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDelivery
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Channel,
			&i.Provider,
			&i.Status,
			&i.FailureCode,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryReconciliation = `-- name: ListDeliveryReconciliation :many
SELECT
    events.customer_reference,
    events.notification_event_id,
    deliveries.channel,
    deliveries.status,
    deliveries.failure_code,
    deliveries.delivered_at
FROM notification.deliveries AS deliveries
JOIN notification.events AS events ON events.id = deliveries.event_id
ORDER BY events.created_at DESC, deliveries.channel
LIMIT $1
`

type ListDeliveryReconciliationRow struct {
	CustomerReference   string             `json:"customer_reference"`
	NotificationEventID string             `json:"notification_event_id"`
	Channel             string             `json:"channel"`
	Status              string             `json:"status"`
	FailureCode         pgtype.Text        `json:"failure_code"`
	DeliveredAt         pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) ListDeliveryReconciliation(ctx context.Context, pageSize int32) ([]ListDeliveryReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listDeliveryReconciliation, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliveryReconciliationRow
	for rows.Next() {
		var i ListDeliveryReconciliationRow
		if err := rows.Scan(
			&i.CustomerReference,
			&i.NotificationEventID,
			&i.Channel,
			&i.Status,
			&i.FailureCode,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInbox = `-- name: ListInbox :many
SELECT
    events.id, events.notification_event_id, events.customer_reference, events.category, events.event_type, events.title_key, events.body_key, events.resource_type, events.resource_id, events.action_path, events.created_at,
    deliveries.status AS delivery_status,
    deliveries.delivered_at
FROM notification.events AS events
JOIN notification.deliveries AS deliveries ON deliveries.event_id = events.id
WHERE events.customer_reference = $1
  AND deliveries.channel = 'IN_APP'
ORDER BY events.created_at DESC, events.id DESC
LIMIT $2
`

type ListInboxParams struct {
	CustomerReference string `json:"customer_reference"`
	PageSize          int32  `json:"page_size"`
}

type ListInboxRow struct {
	ID                  pgtype.UUID        `json:"id"`
	NotificationEventID string             `json:"notification_event_id"`
	CustomerReference   string             `json:"customer_reference"`
	Category            string             `json:"category"`
	EventType           string             `json:"event_type"`
	TitleKey            string             `json:"title_key"`
	BodyKey             string             `json:"body_key"`
	ResourceType        string             `json:"resource_type"`
	ResourceID          string             `json:"resource_id"`
	ActionPath          pgtype.Text        `json:"action_path"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	DeliveryStatus      string             `json:"delivery_status"`
	DeliveredAt         pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]ListInboxRow, error) {
	rows, err := q.db.Query(ctx, listInbox, arg.CustomerReference, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxRow
	for rows.Next() {
		var i ListInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.NotificationEventID,
			&i.CustomerReference,
			&i.Category,
			&i.EventType,
			&i.TitleKey,
			&i.BodyKey,
			&i.ResourceType,
			&i.ResourceID,
			&i.ActionPath,
			&i.CreatedAt,
			&i.DeliveryStatus,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
