// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetEventByKey(ctx context.Context, notificationEventID string) (NotificationEvent, error)
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (NotificationDelivery, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (NotificationEvent, error)
	ListDeliveriesForEvent(ctx context.Context, eventID pgtype.UUID) ([]NotificationDelivery, error)
	ListDeliveryReconciliation(ctx context.Context, pageSize int32) ([]ListDeliveryReconciliationRow, error)
	ListInbox(ctx context.Context, arg ListInboxParams) ([]ListInboxRow, error)
}

var _ Querier = (*Queries)(nil)
