// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID            pgtype.UUID        `json:"id"`
	Action        string             `json:"action"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    string             `json:"resource_id"`
	ActorType     string             `json:"actor_type"`
	ActorID       string             `json:"actor_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	Metadata      []byte             `json:"metadata"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

// Consumer idempotency receipts. A replay may redeliver an event but cannot repeat a recorded consumer effect.
type OutboxConsumerReceipt struct {
	ConsumerName string             `json:"consumer_name"`
	EventID      pgtype.UUID        `json:"event_id"`
	HandledAt    pgtype.Timestamptz `json:"handled_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	MaxAttempts   int32              `json:"max_attempts"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	ClaimedBy     pgtype.Text        `json:"claimed_by"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	LastError     pgtype.Text        `json:"last_error"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
