// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOutboxEvent = `-- name: CancelOutboxEvent :one
UPDATE outbox.events
SET status = 'CANCELLED',
    cancelled_at = clock_timestamp(),
    claimed_by = NULL,
    claimed_at = NULL
WHERE id = $1
  AND status IN ('PENDING', 'DEAD_LETTER')
RETURNING id, aggregate_type, aggregate_id, event_type, event_version, payload, status, attempt_count, max_attempts, available_at, claimed_by, claimed_at, delivered_at, last_error, cancelled_at, created_at
`

func (q *Queries) CancelOutboxEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, cancelOutboxEvent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.EventVersion,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidates AS (
    SELECT event.id
    FROM outbox.events AS event
    WHERE event.attempt_count < event.max_attempts
      AND (
          (event.status = 'PENDING' AND event.available_at <= clock_timestamp())
          OR (
              event.status = 'PROCESSING'
              AND event.claimed_at <= clock_timestamp() - make_interval(secs => $2::INTEGER)
          )
      )
    ORDER BY event.available_at, event.created_at, event.id
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
UPDATE outbox.events AS event
SET status = 'PROCESSING',
    attempt_count = event.attempt_count + 1,
    claimed_by = $1,
    claimed_at = clock_timestamp()
FROM candidates
WHERE event.id = candidates.id
RETURNING event.id, event.aggregate_type, event.aggregate_id, event.event_type, event.event_version, event.payload, event.status, event.attempt_count, event.max_attempts, event.available_at, event.claimed_by, event.claimed_at, event.delivered_at, event.last_error, event.cancelled_at, event.created_at
`

type ClaimOutboxEventsParams struct {
	WorkerID     pgtype.Text `json:"worker_id"`
	LeaseSeconds int32       `json:"lease_seconds"`
	BatchSize    int32       `json:"batch_size"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, arg.WorkerID, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.EventVersion,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.DeliveredAt,
			&i.LastError,
			&i.CancelledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConsumerReceipt = `-- name: GetConsumerReceipt :one
SELECT consumer_name, event_id, handled_at
FROM outbox.consumer_receipts
WHERE consumer_name = $1
  AND event_id = $2
`

type GetConsumerReceiptParams struct {
	ConsumerName string      `json:"consumer_name"`
	EventID      pgtype.UUID `json:"event_id"`
}

func (q *Queries) GetConsumerReceipt(ctx context.Context, arg GetConsumerReceiptParams) (OutboxConsumerReceipt, error) {
	row := q.db.QueryRow(ctx, getConsumerReceipt, arg.ConsumerName, arg.EventID)
	var i OutboxConsumerReceipt
	err := row.Scan(&i.ConsumerName, &i.EventID, &i.HandledAt)
	return i, err
}

const getOutboxEvent = `-- name: GetOutboxEvent :one
SELECT id, aggregate_type, aggregate_id, event_type, event_version, payload, status, attempt_count, max_attempts, available_at, claimed_by, claimed_at, delivered_at, last_error, cancelled_at, created_at
FROM outbox.events
WHERE id = $1
`

func (q *Queries) GetOutboxEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEvent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.EventVersion,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertConsumerReceipt = `-- name: InsertConsumerReceipt :one
INSERT INTO outbox.consumer_receipts (
    consumer_name,
    event_id
) VALUES (
    $1,
    $2
)
ON CONFLICT (consumer_name, event_id) DO NOTHING
RETURNING consumer_name, event_id, handled_at
`

type InsertConsumerReceiptParams struct {
	ConsumerName string      `json:"consumer_name"`
	EventID      pgtype.UUID `json:"event_id"`
}

func (q *Queries) InsertConsumerReceipt(ctx context.Context, arg InsertConsumerReceiptParams) (OutboxConsumerReceipt, error) {
	row := q.db.QueryRow(ctx, insertConsumerReceipt, arg.ConsumerName, arg.EventID)
	var i OutboxConsumerReceipt
	err := row.Scan(&i.ConsumerName, &i.EventID, &i.HandledAt)
	return i, err
}

const insertOutboxAdminAudit = `-- name: InsertOutboxAdminAudit :one
INSERT INTO audit.events (
    action,
    resource_type,
    resource_id,
    actor_type,
    actor_id,
    correlation_id,
    metadata
) VALUES (
    $1,
    'outbox.event',
    $2,
    'ADMIN',
    $3,
    $4,
    $5
)
RETURNING id, action, resource_type, resource_id, actor_type, actor_id, correlation_id, metadata, occurred_at
`

type InsertOutboxAdminAuditParams struct {
	Action        string      `json:"action"`
	ResourceID    string      `json:"resource_id"`
	ActorID       string      `json:"actor_id"`
	CorrelationID pgtype.UUID `json:"correlation_id"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) InsertOutboxAdminAudit(ctx context.Context, arg InsertOutboxAdminAuditParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxAdminAudit,
		arg.Action,
		arg.ResourceID,
		arg.ActorID,
		arg.CorrelationID,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ActorType,
		&i.ActorID,
		&i.CorrelationID,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox.events (
    aggregate_type,
    aggregate_id,
    event_type,
    event_version,
    payload,
    max_attempts
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, aggregate_type, aggregate_id, event_type, event_version, payload, status, attempt_count, max_attempts, available_at, claimed_by, claimed_at, delivered_at, last_error, cancelled_at, created_at
`

type InsertOutboxEventParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	EventType     string `json:"event_type"`
	EventVersion  int32  `json:"event_version"`
	Payload       []byte `json:"payload"`
	MaxAttempts   int32  `json:"max_attempts"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.EventVersion,
		arg.Payload,
		arg.MaxAttempts,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.EventVersion,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOutboxEventsByStatus = `-- name: ListOutboxEventsByStatus :many
SELECT id, aggregate_type, aggregate_id, event_type, event_version, payload, status, attempt_count, max_attempts, available_at, claimed_by, claimed_at, delivered_at, last_error, cancelled_at, created_at
FROM outbox.events
WHERE status = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListOutboxEventsByStatusParams struct {
	Status     string `json:"status"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) ListOutboxEventsByStatus(ctx context.Context, arg ListOutboxEventsByStatusParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsByStatus, arg.Status, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.EventVersion,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.DeliveredAt,
			&i.LastError,
			&i.CancelledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :one
UPDATE outbox.events
SET status = 'DELIVERED',
    delivered_at = clock_timestamp(),
    last_error = NULL
WHERE id = $1
  AND status = 'PROCESSING'
  AND claimed_by = $2
RETURNING id, aggregate_type, aggregate_id, event_type, event_version, payload, status, attempt_count, max_attempts, available_at, claimed_by, claimed_at, delivered_at, last_error, cancelled_at, created_at
`

type MarkOutboxDeliveredParams struct {
	ID       pgtype.UUID `json:"id"`
	WorkerID pgtype.Text `json:"worker_id"`
}

func (q *Queries) MarkOutboxDelivered(ctx context.Context, arg MarkOutboxDeliveredParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxDelivered, arg.ID, arg.WorkerID)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.EventVersion,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :one
UPDATE outbox.events
SET status = CASE
        WHEN attempt_count >= max_attempts THEN 'DEAD_LETTER'
        ELSE 'PENDING'
    END,
    available_at = CASE
        WHEN attempt_count >= max_attempts THEN available_at
        ELSE clock_timestamp() + make_interval(
            secs => LEAST(
                $1::INTEGER,
                $2::INTEGER
                    * (1 << LEAST(GREATEST(attempt_count - 1, 0), 20))
            )
        )
    END,
    claimed_by = NULL,
    claimed_at = NULL,
    last_error = LEFT($3, 1024)
WHERE id = $4
  AND status = 'PROCESSING'
  AND claimed_by = $5
RETURNING id, aggregate_type, aggregate_id, event_type, event_version, payload, status, attempt_count, max_attempts, available_at, claimed_by, claimed_at, delivered_at, last_error, cancelled_at, created_at
`

type MarkOutboxFailedParams struct {
	MaxBackoffSeconds  int32       `json:"max_backoff_seconds"`
	BaseBackoffSeconds int32       `json:"base_backoff_seconds"`
	ErrorMessage       string      `json:"error_message"`
	ID                 pgtype.UUID `json:"id"`
	WorkerID           pgtype.Text `json:"worker_id"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, markOutboxFailed,
		arg.MaxBackoffSeconds,
		arg.BaseBackoffSeconds,
		arg.ErrorMessage,
		arg.ID,
		arg.WorkerID,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.EventVersion,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const replayDeadLetterEvent = `-- name: ReplayDeadLetterEvent :one
UPDATE outbox.events
SET status = 'PENDING',
    attempt_count = 0,
    available_at = clock_timestamp(),
    claimed_by = NULL,
    claimed_at = NULL,
    delivered_at = NULL,
    last_error = NULL
WHERE id = $1
  AND status = 'DEAD_LETTER'
RETURNING id, aggregate_type, aggregate_id, event_type, event_version, payload, status, attempt_count, max_attempts, available_at, claimed_by, claimed_at, delivered_at, last_error, cancelled_at, created_at
`

func (q *Queries) ReplayDeadLetterEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, replayDeadLetterEvent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.EventVersion,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}
