// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelOutboxEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error)
	DeadLetterExpiredOutboxClaims(ctx context.Context, leaseSeconds int32) (int64, error)
	GetConsumerReceipt(ctx context.Context, arg GetConsumerReceiptParams) (OutboxConsumerReceipt, error)
	GetOutboxEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	InsertConsumerReceipt(ctx context.Context, arg InsertConsumerReceiptParams) (OutboxConsumerReceipt, error)
	InsertOutboxAdminAudit(ctx context.Context, arg InsertOutboxAdminAuditParams) (AuditEvent, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error)
	ListOutboxEventsByStatus(ctx context.Context, arg ListOutboxEventsByStatusParams) ([]OutboxEvent, error)
	MarkOutboxDelivered(ctx context.Context, arg MarkOutboxDeliveredParams) (OutboxEvent, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (OutboxEvent, error)
	ReplayDeadLetterEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
}

var _ Querier = (*Queries)(nil)
