// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compliance.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCase = `-- name: CreateCase :one
INSERT INTO compliance.cases (
    id,
    customer_reference,
    case_type,
    resource_type,
    resource_id,
    status,
    reason_code,
    next_action,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, customer_reference, case_type, resource_type, resource_id, status, reason_code, next_action, policy_version, created_at, updated_at, version
`

type CreateCaseParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
	CaseType          string      `json:"case_type"`
	ResourceType      string      `json:"resource_type"`
	ResourceID        string      `json:"resource_id"`
	Status            string      `json:"status"`
	ReasonCode        string      `json:"reason_code"`
	NextAction        string      `json:"next_action"`
	PolicyVersion     string      `json:"policy_version"`
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) (ComplianceCase, error) {
	row := q.db.QueryRow(ctx, createCase,
		arg.ID,
		arg.CustomerReference,
		arg.CaseType,
		arg.ResourceType,
		arg.ResourceID,
		arg.Status,
		arg.ReasonCode,
		arg.NextAction,
		arg.PolicyVersion,
	)
	var i ComplianceCase
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CaseType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createReviewProposal = `-- name: CreateReviewProposal :one
INSERT INTO compliance.review_proposals (
    id,
    case_id,
    action,
    maker_id,
    maker_role,
    reason_code,
    ticket_reference,
    evidence_reference
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, case_id, action, maker_id, maker_role, reason_code, ticket_reference, evidence_reference, status, checker_id, checker_role, decision_reason, created_at, decided_at
`

type CreateReviewProposalParams struct {
	ID                pgtype.UUID `json:"id"`
	CaseID            pgtype.UUID `json:"case_id"`
	Action            string      `json:"action"`
	MakerID           string      `json:"maker_id"`
	MakerRole         string      `json:"maker_role"`
	ReasonCode        string      `json:"reason_code"`
	TicketReference   string      `json:"ticket_reference"`
	EvidenceReference string      `json:"evidence_reference"`
}

func (q *Queries) CreateReviewProposal(ctx context.Context, arg CreateReviewProposalParams) (ComplianceReviewProposal, error) {
	row := q.db.QueryRow(ctx, createReviewProposal,
		arg.ID,
		arg.CaseID,
		arg.Action,
		arg.MakerID,
		arg.MakerRole,
		arg.ReasonCode,
		arg.TicketReference,
		arg.EvidenceReference,
	)
	var i ComplianceReviewProposal
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Action,
		&i.MakerID,
		&i.MakerRole,
		&i.ReasonCode,
		&i.TicketReference,
		&i.EvidenceReference,
		&i.Status,
		&i.CheckerID,
		&i.CheckerRole,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideReviewProposal = `-- name: DecideReviewProposal :one
UPDATE compliance.review_proposals
SET status = $1,
    checker_id = $2,
    checker_role = $3,
    decision_reason = $4,
    decided_at = clock_timestamp()
WHERE id = $5
  AND status = 'PENDING'
RETURNING id, case_id, action, maker_id, maker_role, reason_code, ticket_reference, evidence_reference, status, checker_id, checker_role, decision_reason, created_at, decided_at
`

type DecideReviewProposalParams struct {
	Status         string      `json:"status"`
	CheckerID      pgtype.Text `json:"checker_id"`
	CheckerRole    pgtype.Text `json:"checker_role"`
	DecisionReason pgtype.Text `json:"decision_reason"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) DecideReviewProposal(ctx context.Context, arg DecideReviewProposalParams) (ComplianceReviewProposal, error) {
	row := q.db.QueryRow(ctx, decideReviewProposal,
		arg.Status,
		arg.CheckerID,
		arg.CheckerRole,
		arg.DecisionReason,
		arg.ID,
	)
	var i ComplianceReviewProposal
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Action,
		&i.MakerID,
		&i.MakerRole,
		&i.ReasonCode,
		&i.TicketReference,
		&i.EvidenceReference,
		&i.Status,
		&i.CheckerID,
		&i.CheckerRole,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getCase = `-- name: GetCase :one
SELECT id, customer_reference, case_type, resource_type, resource_id, status, reason_code, next_action, policy_version, created_at, updated_at, version
FROM compliance.cases
WHERE id = $1
`

func (q *Queries) GetCase(ctx context.Context, id pgtype.UUID) (ComplianceCase, error) {
	row := q.db.QueryRow(ctx, getCase, id)
	var i ComplianceCase
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CaseType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCaseForUpdate = `-- name: GetCaseForUpdate :one
SELECT id, customer_reference, case_type, resource_type, resource_id, status, reason_code, next_action, policy_version, created_at, updated_at, version
FROM compliance.cases
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCaseForUpdate(ctx context.Context, id pgtype.UUID) (ComplianceCase, error) {
	row := q.db.QueryRow(ctx, getCaseForUpdate, id)
	var i ComplianceCase
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CaseType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getReviewProposal = `-- name: GetReviewProposal :one
SELECT id, case_id, action, maker_id, maker_role, reason_code, ticket_reference, evidence_reference, status, checker_id, checker_role, decision_reason, created_at, decided_at
FROM compliance.review_proposals
WHERE id = $1
`

func (q *Queries) GetReviewProposal(ctx context.Context, id pgtype.UUID) (ComplianceReviewProposal, error) {
	row := q.db.QueryRow(ctx, getReviewProposal, id)
	var i ComplianceReviewProposal
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Action,
		&i.MakerID,
		&i.MakerRole,
		&i.ReasonCode,
		&i.TicketReference,
		&i.EvidenceReference,
		&i.Status,
		&i.CheckerID,
		&i.CheckerRole,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getReviewProposalForUpdate = `-- name: GetReviewProposalForUpdate :one
SELECT id, case_id, action, maker_id, maker_role, reason_code, ticket_reference, evidence_reference, status, checker_id, checker_role, decision_reason, created_at, decided_at
FROM compliance.review_proposals
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetReviewProposalForUpdate(ctx context.Context, id pgtype.UUID) (ComplianceReviewProposal, error) {
	row := q.db.QueryRow(ctx, getReviewProposalForUpdate, id)
	var i ComplianceReviewProposal
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Action,
		&i.MakerID,
		&i.MakerRole,
		&i.ReasonCode,
		&i.TicketReference,
		&i.EvidenceReference,
		&i.Status,
		&i.CheckerID,
		&i.CheckerRole,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertCaseEvent = `-- name: InsertCaseEvent :one
INSERT INTO compliance.case_events (
    case_id,
    from_status,
    to_status,
    actor_type,
    actor_id,
    reason_code,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, case_id, from_status, to_status, actor_type, actor_id, reason_code, metadata, occurred_at
`

type InsertCaseEventParams struct {
	CaseID     pgtype.UUID `json:"case_id"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	ActorType  string      `json:"actor_type"`
	ActorID    string      `json:"actor_id"`
	ReasonCode string      `json:"reason_code"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) InsertCaseEvent(ctx context.Context, arg InsertCaseEventParams) (ComplianceCaseEvent, error) {
	row := q.db.QueryRow(ctx, insertCaseEvent,
		arg.CaseID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorType,
		arg.ActorID,
		arg.ReasonCode,
		arg.Metadata,
	)
	var i ComplianceCaseEvent
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorType,
		&i.ActorID,
		&i.ReasonCode,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const listCases = `-- name: ListCases :many
SELECT id, customer_reference, case_type, resource_type, resource_id, status, reason_code, next_action, policy_version, created_at, updated_at, version
FROM compliance.cases
WHERE ($1::TEXT = '' OR status = $1)
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListCasesParams struct {
	StatusFilter string `json:"status_filter"`
	PageSize     int32  `json:"page_size"`
}

func (q *Queries) ListCases(ctx context.Context, arg ListCasesParams) ([]ComplianceCase, error) {
	rows, err := q.db.Query(ctx, listCases, arg.StatusFilter, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceCase
	for rows.Next() {
		var i ComplianceCase
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.CaseType,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
			&i.ReasonCode,
			&i.NextAction,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewProposalsForCase = `-- name: ListReviewProposalsForCase :many
SELECT id, case_id, action, maker_id, maker_role, reason_code, ticket_reference, evidence_reference, status, checker_id, checker_role, decision_reason, created_at, decided_at
FROM compliance.review_proposals
WHERE case_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListReviewProposalsForCase(ctx context.Context, caseID pgtype.UUID) ([]ComplianceReviewProposal, error) {
	rows, err := q.db.Query(ctx, listReviewProposalsForCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceReviewProposal
	for rows.Next() {
		var i ComplianceReviewProposal
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Action,
			&i.MakerID,
			&i.MakerRole,
			&i.ReasonCode,
			&i.TicketReference,
			&i.EvidenceReference,
			&i.Status,
			&i.CheckerID,
			&i.CheckerRole,
			&i.DecisionReason,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionCase = `-- name: TransitionCase :one
UPDATE compliance.cases
SET status = $1,
    reason_code = $2,
    next_action = $3
WHERE id = $4
RETURNING id, customer_reference, case_type, resource_type, resource_id, status, reason_code, next_action, policy_version, created_at, updated_at, version
`

type TransitionCaseParams struct {
	Status     string      `json:"status"`
	ReasonCode string      `json:"reason_code"`
	NextAction string      `json:"next_action"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) TransitionCase(ctx context.Context, arg TransitionCaseParams) (ComplianceCase, error) {
	row := q.db.QueryRow(ctx, transitionCase,
		arg.Status,
		arg.ReasonCode,
		arg.NextAction,
		arg.ID,
	)
	var i ComplianceCase
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CaseType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
