// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ComplianceCase struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	CaseType          string             `json:"case_type"`
	ResourceType      string             `json:"resource_type"`
	ResourceID        string             `json:"resource_id"`
	Status            string             `json:"status"`
	ReasonCode        string             `json:"reason_code"`
	NextAction        string             `json:"next_action"`
	PolicyVersion     string             `json:"policy_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Version           int64              `json:"version"`
}

type ComplianceCaseEvent struct {
	ID         pgtype.UUID        `json:"id"`
	CaseID     pgtype.UUID        `json:"case_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	ActorType  string             `json:"actor_type"`
	ActorID    string             `json:"actor_id"`
	ReasonCode string             `json:"reason_code"`
	Metadata   []byte             `json:"metadata"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type ComplianceReviewProposal struct {
	ID                pgtype.UUID        `json:"id"`
	CaseID            pgtype.UUID        `json:"case_id"`
	Action            string             `json:"action"`
	MakerID           string             `json:"maker_id"`
	MakerRole         string             `json:"maker_role"`
	ReasonCode        string             `json:"reason_code"`
	TicketReference   string             `json:"ticket_reference"`
	EvidenceReference string             `json:"evidence_reference"`
	Status            string             `json:"status"`
	CheckerID         pgtype.Text        `json:"checker_id"`
	CheckerRole       pgtype.Text        `json:"checker_role"`
	DecisionReason    pgtype.Text        `json:"decision_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DecidedAt         pgtype.Timestamptz `json:"decided_at"`
}
