// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCase(ctx context.Context, arg CreateCaseParams) (ComplianceCase, error)
	CreateReviewProposal(ctx context.Context, arg CreateReviewProposalParams) (ComplianceReviewProposal, error)
	DecideReviewProposal(ctx context.Context, arg DecideReviewProposalParams) (ComplianceReviewProposal, error)
	GetCase(ctx context.Context, id pgtype.UUID) (ComplianceCase, error)
	GetCaseForUpdate(ctx context.Context, id pgtype.UUID) (ComplianceCase, error)
	GetReviewProposal(ctx context.Context, id pgtype.UUID) (ComplianceReviewProposal, error)
	GetReviewProposalForUpdate(ctx context.Context, id pgtype.UUID) (ComplianceReviewProposal, error)
	InsertCaseEvent(ctx context.Context, arg InsertCaseEventParams) (ComplianceCaseEvent, error)
	ListCases(ctx context.Context, arg ListCasesParams) ([]ComplianceCase, error)
	ListReviewProposalsForCase(ctx context.Context, caseID pgtype.UUID) ([]ComplianceReviewProposal, error)
	TransitionCase(ctx context.Context, arg TransitionCaseParams) (ComplianceCase, error)
}

var _ Querier = (*Queries)(nil)
