// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit.events (
    action,
    resource_type,
    resource_id,
    actor_type,
    actor_id,
    correlation_id,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, action, resource_type, resource_id, actor_type, actor_id, correlation_id, metadata, occurred_at
`

type InsertAuditEventParams struct {
	Action        string      `json:"action"`
	ResourceType  string      `json:"resource_type"`
	ResourceID    string      `json:"resource_id"`
	ActorType     string      `json:"actor_type"`
	ActorID       string      `json:"actor_id"`
	CorrelationID pgtype.UUID `json:"correlation_id"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ActorType,
		arg.ActorID,
		arg.CorrelationID,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ActorType,
		&i.ActorID,
		&i.CorrelationID,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}
