// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID            pgtype.UUID        `json:"id"`
	Action        string             `json:"action"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    string             `json:"resource_id"`
	ActorType     string             `json:"actor_type"`
	ActorID       string             `json:"actor_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	Metadata      []byte             `json:"metadata"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}
