// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
}

var _ Querier = (*Queries)(nil)
