// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card.sql

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindCommandRequestResource = `-- name: BindCommandRequestResource :exec
UPDATE card.command_requests
SET resource_id = $1
WHERE customer_reference = $2
  AND scope = $3
  AND idempotency_key = $4
`

type BindCommandRequestResourceParams struct {
	ResourceID        pgtype.UUID `json:"resource_id"`
	CustomerReference string      `json:"customer_reference"`
	Scope             string      `json:"scope"`
	IdempotencyKey    string      `json:"idempotency_key"`
}

func (q *Queries) BindCommandRequestResource(ctx context.Context, arg BindCommandRequestResourceParams) error {
	_, err := q.db.Exec(ctx, bindCommandRequestResource,
		arg.ResourceID,
		arg.CustomerReference,
		arg.Scope,
		arg.IdempotencyKey,
	)
	return err
}

const createAuthorization = `-- name: CreateAuthorization :one
INSERT INTO card.authorizations (
    id, customer_reference, card_id, provider, external_authorization_id,
    merchant_name, merchant_category_code, merchant_amount, merchant_currency,
    authorization_fx_rate, fx_markup_rate, authorized_usd, status, offline,
    entry_mode, occurred_at, decline_code, hold_ledger_transaction_id, policy_version
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8,
    $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19
)
RETURNING id, customer_reference, card_id, provider, external_authorization_id, merchant_name, merchant_category_code, merchant_amount, merchant_currency, authorization_fx_rate, fx_markup_rate, authorized_usd, status, offline, entry_mode, occurred_at, received_at, decline_code, hold_ledger_transaction_id, captured_usd, reversed_usd, policy_version, created_at, updated_at, version
`

type CreateAuthorizationParams struct {
	ID                      pgtype.UUID        `json:"id"`
	CustomerReference       string             `json:"customer_reference"`
	CardID                  pgtype.UUID        `json:"card_id"`
	Provider                string             `json:"provider"`
	ExternalAuthorizationID string             `json:"external_authorization_id"`
	MerchantName            string             `json:"merchant_name"`
	MerchantCategoryCode    string             `json:"merchant_category_code"`
	MerchantAmount          money.Decimal      `json:"merchant_amount"`
	MerchantCurrency        string             `json:"merchant_currency"`
	AuthorizationFxRate     money.Decimal      `json:"authorization_fx_rate"`
	FxMarkupRate            money.Decimal      `json:"fx_markup_rate"`
	AuthorizedUsd           money.Decimal      `json:"authorized_usd"`
	Status                  string             `json:"status"`
	Offline                 bool               `json:"offline"`
	EntryMode               string             `json:"entry_mode"`
	OccurredAt              pgtype.Timestamptz `json:"occurred_at"`
	DeclineCode             pgtype.Text        `json:"decline_code"`
	HoldLedgerTransactionID pgtype.UUID        `json:"hold_ledger_transaction_id"`
	PolicyVersion           string             `json:"policy_version"`
}

func (q *Queries) CreateAuthorization(ctx context.Context, arg CreateAuthorizationParams) (CardAuthorization, error) {
	row := q.db.QueryRow(ctx, createAuthorization,
		arg.ID,
		arg.CustomerReference,
		arg.CardID,
		arg.Provider,
		arg.ExternalAuthorizationID,
		arg.MerchantName,
		arg.MerchantCategoryCode,
		arg.MerchantAmount,
		arg.MerchantCurrency,
		arg.AuthorizationFxRate,
		arg.FxMarkupRate,
		arg.AuthorizedUsd,
		arg.Status,
		arg.Offline,
		arg.EntryMode,
		arg.OccurredAt,
		arg.DeclineCode,
		arg.HoldLedgerTransactionID,
		arg.PolicyVersion,
	)
	var i CardAuthorization
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardID,
		&i.Provider,
		&i.ExternalAuthorizationID,
		&i.MerchantName,
		&i.MerchantCategoryCode,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.AuthorizationFxRate,
		&i.FxMarkupRate,
		&i.AuthorizedUsd,
		&i.Status,
		&i.Offline,
		&i.EntryMode,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.DeclineCode,
		&i.HoldLedgerTransactionID,
		&i.CapturedUsd,
		&i.ReversedUsd,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createCapture = `-- name: CreateCapture :one
INSERT INTO card.captures (
    id, authorization_id, provider, external_capture_id, merchant_amount,
    merchant_currency, clearing_fx_rate, fx_markup_rate, settled_usd,
    tip_usd, hold_released_usd, cash_repaid_usd, auto_sell_repaid_usd,
    receivable_ledger_transaction_id, repayment_ledger_transaction_id, occurred_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14,
    $15, $16
)
RETURNING id, authorization_id, provider, external_capture_id, merchant_amount, merchant_currency, clearing_fx_rate, fx_markup_rate, settled_usd, tip_usd, hold_released_usd, cash_repaid_usd, auto_sell_repaid_usd, refunded_usd, status, receivable_ledger_transaction_id, repayment_ledger_transaction_id, occurred_at, created_at
`

type CreateCaptureParams struct {
	ID                            pgtype.UUID        `json:"id"`
	AuthorizationID               pgtype.UUID        `json:"authorization_id"`
	Provider                      string             `json:"provider"`
	ExternalCaptureID             string             `json:"external_capture_id"`
	MerchantAmount                money.Decimal      `json:"merchant_amount"`
	MerchantCurrency              string             `json:"merchant_currency"`
	ClearingFxRate                money.Decimal      `json:"clearing_fx_rate"`
	FxMarkupRate                  money.Decimal      `json:"fx_markup_rate"`
	SettledUsd                    money.Decimal      `json:"settled_usd"`
	TipUsd                        money.Decimal      `json:"tip_usd"`
	HoldReleasedUsd               money.Decimal      `json:"hold_released_usd"`
	CashRepaidUsd                 money.Decimal      `json:"cash_repaid_usd"`
	AutoSellRepaidUsd             money.Decimal      `json:"auto_sell_repaid_usd"`
	ReceivableLedgerTransactionID pgtype.UUID        `json:"receivable_ledger_transaction_id"`
	RepaymentLedgerTransactionID  pgtype.UUID        `json:"repayment_ledger_transaction_id"`
	OccurredAt                    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateCapture(ctx context.Context, arg CreateCaptureParams) (CardCapture, error) {
	row := q.db.QueryRow(ctx, createCapture,
		arg.ID,
		arg.AuthorizationID,
		arg.Provider,
		arg.ExternalCaptureID,
		arg.MerchantAmount,
		arg.MerchantCurrency,
		arg.ClearingFxRate,
		arg.FxMarkupRate,
		arg.SettledUsd,
		arg.TipUsd,
		arg.HoldReleasedUsd,
		arg.CashRepaidUsd,
		arg.AutoSellRepaidUsd,
		arg.ReceivableLedgerTransactionID,
		arg.RepaymentLedgerTransactionID,
		arg.OccurredAt,
	)
	var i CardCapture
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.Provider,
		&i.ExternalCaptureID,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.ClearingFxRate,
		&i.FxMarkupRate,
		&i.SettledUsd,
		&i.TipUsd,
		&i.HoldReleasedUsd,
		&i.CashRepaidUsd,
		&i.AutoSellRepaidUsd,
		&i.RefundedUsd,
		&i.Status,
		&i.ReceivableLedgerTransactionID,
		&i.RepaymentLedgerTransactionID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO card.cards (
    id, customer_reference, card_type, status, display_name, last4,
    provider, provider_card_reference, apple_wallet_status,
    google_wallet_status, replacement_for_card_id, policy_version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11,
    $12
)
RETURNING id, customer_reference, card_type, status, display_name, last4, pin_set, provider, provider_card_reference, apple_wallet_status, google_wallet_status, replacement_for_card_id, policy_version, created_at, updated_at, version
`

type CreateCardParams struct {
	ID                    pgtype.UUID `json:"id"`
	CustomerReference     string      `json:"customer_reference"`
	CardType              string      `json:"card_type"`
	Status                string      `json:"status"`
	DisplayName           string      `json:"display_name"`
	Last4                 string      `json:"last4"`
	Provider              string      `json:"provider"`
	ProviderCardReference string      `json:"provider_card_reference"`
	AppleWalletStatus     string      `json:"apple_wallet_status"`
	GoogleWalletStatus    string      `json:"google_wallet_status"`
	ReplacementForCardID  pgtype.UUID `json:"replacement_for_card_id"`
	PolicyVersion         string      `json:"policy_version"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (CardCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.CustomerReference,
		arg.CardType,
		arg.Status,
		arg.DisplayName,
		arg.Last4,
		arg.Provider,
		arg.ProviderCardReference,
		arg.AppleWalletStatus,
		arg.GoogleWalletStatus,
		arg.ReplacementForCardID,
		arg.PolicyVersion,
	)
	var i CardCard
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardType,
		&i.Status,
		&i.DisplayName,
		&i.Last4,
		&i.PinSet,
		&i.Provider,
		&i.ProviderCardReference,
		&i.AppleWalletStatus,
		&i.GoogleWalletStatus,
		&i.ReplacementForCardID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createCustomerProfile = `-- name: CreateCustomerProfile :one
INSERT INTO card.customer_profiles (
    customer_reference,
    paper_account_id,
    cash_ledger_account_id,
    receivable_ledger_account_id,
    provider_clearing_ledger_account_id,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (customer_reference) DO NOTHING
RETURNING customer_reference, paper_account_id, cash_ledger_account_id, receivable_ledger_account_id, provider_clearing_ledger_account_id, repayment_mode, spending_status, spending_status_reason, trust_tier, kyc_status, policy_version, created_at, updated_at, version
`

type CreateCustomerProfileParams struct {
	CustomerReference               string      `json:"customer_reference"`
	PaperAccountID                  pgtype.UUID `json:"paper_account_id"`
	CashLedgerAccountID             pgtype.UUID `json:"cash_ledger_account_id"`
	ReceivableLedgerAccountID       pgtype.UUID `json:"receivable_ledger_account_id"`
	ProviderClearingLedgerAccountID pgtype.UUID `json:"provider_clearing_ledger_account_id"`
	PolicyVersion                   string      `json:"policy_version"`
}

func (q *Queries) CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CardCustomerProfile, error) {
	row := q.db.QueryRow(ctx, createCustomerProfile,
		arg.CustomerReference,
		arg.PaperAccountID,
		arg.CashLedgerAccountID,
		arg.ReceivableLedgerAccountID,
		arg.ProviderClearingLedgerAccountID,
		arg.PolicyVersion,
	)
	var i CardCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ReceivableLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.RepaymentMode,
		&i.SpendingStatus,
		&i.SpendingStatusReason,
		&i.TrustTier,
		&i.KycStatus,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createDispute = `-- name: CreateDispute :one
INSERT INTO card.disputes (
    id, capture_id, customer_reference, amount_usd, reason_code,
    compliance_case_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, capture_id, customer_reference, amount_usd, reason_code, status, outcome, compliance_case_id, resolution_ledger_transaction_id, opened_at, resolved_at, version
`

type CreateDisputeParams struct {
	ID                pgtype.UUID   `json:"id"`
	CaptureID         pgtype.UUID   `json:"capture_id"`
	CustomerReference string        `json:"customer_reference"`
	AmountUsd         money.Decimal `json:"amount_usd"`
	ReasonCode        string        `json:"reason_code"`
	ComplianceCaseID  pgtype.UUID   `json:"compliance_case_id"`
}

func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (CardDispute, error) {
	row := q.db.QueryRow(ctx, createDispute,
		arg.ID,
		arg.CaptureID,
		arg.CustomerReference,
		arg.AmountUsd,
		arg.ReasonCode,
		arg.ComplianceCaseID,
	)
	var i CardDispute
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.CustomerReference,
		&i.AmountUsd,
		&i.ReasonCode,
		&i.Status,
		&i.Outcome,
		&i.ComplianceCaseID,
		&i.ResolutionLedgerTransactionID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.Version,
	)
	return i, err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO card.refunds (
    id, capture_id, provider, external_refund_id, refund_usd,
    receivable_reduction_usd, cash_credit_usd, ledger_transaction_id, occurred_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9
)
RETURNING id, capture_id, provider, external_refund_id, refund_usd, receivable_reduction_usd, cash_credit_usd, ledger_transaction_id, occurred_at, created_at
`

type CreateRefundParams struct {
	ID                     pgtype.UUID        `json:"id"`
	CaptureID              pgtype.UUID        `json:"capture_id"`
	Provider               string             `json:"provider"`
	ExternalRefundID       string             `json:"external_refund_id"`
	RefundUsd              money.Decimal      `json:"refund_usd"`
	ReceivableReductionUsd money.Decimal      `json:"receivable_reduction_usd"`
	CashCreditUsd          money.Decimal      `json:"cash_credit_usd"`
	LedgerTransactionID    pgtype.UUID        `json:"ledger_transaction_id"`
	OccurredAt             pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (CardRefund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.ID,
		arg.CaptureID,
		arg.Provider,
		arg.ExternalRefundID,
		arg.RefundUsd,
		arg.ReceivableReductionUsd,
		arg.CashCreditUsd,
		arg.LedgerTransactionID,
		arg.OccurredAt,
	)
	var i CardRefund
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Provider,
		&i.ExternalRefundID,
		&i.RefundUsd,
		&i.ReceivableReductionUsd,
		&i.CashCreditUsd,
		&i.LedgerTransactionID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createReversal = `-- name: CreateReversal :one
INSERT INTO card.reversals (
    id, authorization_id, provider, external_reversal_id,
    reversed_usd, ledger_transaction_id, occurred_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
RETURNING id, authorization_id, provider, external_reversal_id, reversed_usd, ledger_transaction_id, occurred_at, created_at
`

type CreateReversalParams struct {
	ID                  pgtype.UUID        `json:"id"`
	AuthorizationID     pgtype.UUID        `json:"authorization_id"`
	Provider            string             `json:"provider"`
	ExternalReversalID  string             `json:"external_reversal_id"`
	ReversedUsd         money.Decimal      `json:"reversed_usd"`
	LedgerTransactionID pgtype.UUID        `json:"ledger_transaction_id"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateReversal(ctx context.Context, arg CreateReversalParams) (CardReversal, error) {
	row := q.db.QueryRow(ctx, createReversal,
		arg.ID,
		arg.AuthorizationID,
		arg.Provider,
		arg.ExternalReversalID,
		arg.ReversedUsd,
		arg.LedgerTransactionID,
		arg.OccurredAt,
	)
	var i CardReversal
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.Provider,
		&i.ExternalReversalID,
		&i.ReversedUsd,
		&i.LedgerTransactionID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStatement = `-- name: CreateStatement :one
INSERT INTO card.statements (
    id, customer_reference, period_start, period_end, amount_due_usd, due_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (customer_reference, period_start, period_end) DO UPDATE
SET amount_due_usd = EXCLUDED.amount_due_usd,
    due_at = EXCLUDED.due_at
WHERE card.statements.status = 'OPEN'
RETURNING id, customer_reference, period_start, period_end, amount_due_usd, status, due_at, paid_at, repayment_ledger_transaction_id, created_at
`

type CreateStatementParams struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	PeriodStart       pgtype.Date        `json:"period_start"`
	PeriodEnd         pgtype.Date        `json:"period_end"`
	AmountDueUsd      money.Decimal      `json:"amount_due_usd"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateStatement(ctx context.Context, arg CreateStatementParams) (CardStatement, error) {
	row := q.db.QueryRow(ctx, createStatement,
		arg.ID,
		arg.CustomerReference,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.AmountDueUsd,
		arg.DueAt,
	)
	var i CardStatement
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.AmountDueUsd,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.RepaymentLedgerTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAutoSellMandateAssets = `-- name: DeleteAutoSellMandateAssets :exec
DELETE FROM card.auto_sell_mandate_assets
WHERE mandate_id = $1
`

func (q *Queries) DeleteAutoSellMandateAssets(ctx context.Context, mandateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAutoSellMandateAssets, mandateID)
	return err
}

const freezeSpending = `-- name: FreezeSpending :one
UPDATE card.customer_profiles
SET spending_status = 'FROZEN',
    spending_status_reason = $1,
    updated_at = clock_timestamp(),
    version = version + 1
WHERE customer_reference = $2
RETURNING customer_reference, paper_account_id, cash_ledger_account_id, receivable_ledger_account_id, provider_clearing_ledger_account_id, repayment_mode, spending_status, spending_status_reason, trust_tier, kyc_status, policy_version, created_at, updated_at, version
`

type FreezeSpendingParams struct {
	ReasonCode        pgtype.Text `json:"reason_code"`
	CustomerReference string      `json:"customer_reference"`
}

func (q *Queries) FreezeSpending(ctx context.Context, arg FreezeSpendingParams) (CardCustomerProfile, error) {
	row := q.db.QueryRow(ctx, freezeSpending, arg.ReasonCode, arg.CustomerReference)
	var i CardCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ReceivableLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.RepaymentMode,
		&i.SpendingStatus,
		&i.SpendingStatusReason,
		&i.TrustTier,
		&i.KycStatus,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getActivePolicy = `-- name: GetActivePolicy :one
SELECT policy_version, auth_fx_markup_rate, maximum_tip_rate, protected_limit_guardrail_rate, absolute_spending_cap_usd, provider_spending_cap_usd, default_daily_auto_sell_usd, quote_max_age_seconds, statement_cycle_days, effective_at, active, created_at
FROM card.policies
WHERE active
  AND effective_at <= clock_timestamp()
ORDER BY effective_at DESC
LIMIT 1
`

func (q *Queries) GetActivePolicy(ctx context.Context) (CardPolicy, error) {
	row := q.db.QueryRow(ctx, getActivePolicy)
	var i CardPolicy
	err := row.Scan(
		&i.PolicyVersion,
		&i.AuthFxMarkupRate,
		&i.MaximumTipRate,
		&i.ProtectedLimitGuardrailRate,
		&i.AbsoluteSpendingCapUsd,
		&i.ProviderSpendingCapUsd,
		&i.DefaultDailyAutoSellUsd,
		&i.QuoteMaxAgeSeconds,
		&i.StatementCycleDays,
		&i.EffectiveAt,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorization = `-- name: GetAuthorization :one
SELECT id, customer_reference, card_id, provider, external_authorization_id, merchant_name, merchant_category_code, merchant_amount, merchant_currency, authorization_fx_rate, fx_markup_rate, authorized_usd, status, offline, entry_mode, occurred_at, received_at, decline_code, hold_ledger_transaction_id, captured_usd, reversed_usd, policy_version, created_at, updated_at, version
FROM card.authorizations
WHERE id = $1
`

func (q *Queries) GetAuthorization(ctx context.Context, id pgtype.UUID) (CardAuthorization, error) {
	row := q.db.QueryRow(ctx, getAuthorization, id)
	var i CardAuthorization
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardID,
		&i.Provider,
		&i.ExternalAuthorizationID,
		&i.MerchantName,
		&i.MerchantCategoryCode,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.AuthorizationFxRate,
		&i.FxMarkupRate,
		&i.AuthorizedUsd,
		&i.Status,
		&i.Offline,
		&i.EntryMode,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.DeclineCode,
		&i.HoldLedgerTransactionID,
		&i.CapturedUsd,
		&i.ReversedUsd,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getAuthorizationForUpdate = `-- name: GetAuthorizationForUpdate :one
SELECT id, customer_reference, card_id, provider, external_authorization_id, merchant_name, merchant_category_code, merchant_amount, merchant_currency, authorization_fx_rate, fx_markup_rate, authorized_usd, status, offline, entry_mode, occurred_at, received_at, decline_code, hold_ledger_transaction_id, captured_usd, reversed_usd, policy_version, created_at, updated_at, version
FROM card.authorizations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAuthorizationForUpdate(ctx context.Context, id pgtype.UUID) (CardAuthorization, error) {
	row := q.db.QueryRow(ctx, getAuthorizationForUpdate, id)
	var i CardAuthorization
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardID,
		&i.Provider,
		&i.ExternalAuthorizationID,
		&i.MerchantName,
		&i.MerchantCategoryCode,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.AuthorizationFxRate,
		&i.FxMarkupRate,
		&i.AuthorizedUsd,
		&i.Status,
		&i.Offline,
		&i.EntryMode,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.DeclineCode,
		&i.HoldLedgerTransactionID,
		&i.CapturedUsd,
		&i.ReversedUsd,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getAutoSellMandate = `-- name: GetAutoSellMandate :one
SELECT id, customer_reference, enabled, allow_fractional, daily_max_usd, valid_until, policy_version, created_at, updated_at, version
FROM card.auto_sell_mandates
WHERE customer_reference = $1
`

func (q *Queries) GetAutoSellMandate(ctx context.Context, customerReference string) (CardAutoSellMandate, error) {
	row := q.db.QueryRow(ctx, getAutoSellMandate, customerReference)
	var i CardAutoSellMandate
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Enabled,
		&i.AllowFractional,
		&i.DailyMaxUsd,
		&i.ValidUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getAutoSellMandateForUpdate = `-- name: GetAutoSellMandateForUpdate :one
SELECT id, customer_reference, enabled, allow_fractional, daily_max_usd, valid_until, policy_version, created_at, updated_at, version
FROM card.auto_sell_mandates
WHERE customer_reference = $1
FOR UPDATE
`

func (q *Queries) GetAutoSellMandateForUpdate(ctx context.Context, customerReference string) (CardAutoSellMandate, error) {
	row := q.db.QueryRow(ctx, getAutoSellMandateForUpdate, customerReference)
	var i CardAutoSellMandate
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Enabled,
		&i.AllowFractional,
		&i.DailyMaxUsd,
		&i.ValidUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCapture = `-- name: GetCapture :one
SELECT id, authorization_id, provider, external_capture_id, merchant_amount, merchant_currency, clearing_fx_rate, fx_markup_rate, settled_usd, tip_usd, hold_released_usd, cash_repaid_usd, auto_sell_repaid_usd, refunded_usd, status, receivable_ledger_transaction_id, repayment_ledger_transaction_id, occurred_at, created_at
FROM card.captures
WHERE id = $1
`

func (q *Queries) GetCapture(ctx context.Context, id pgtype.UUID) (CardCapture, error) {
	row := q.db.QueryRow(ctx, getCapture, id)
	var i CardCapture
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.Provider,
		&i.ExternalCaptureID,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.ClearingFxRate,
		&i.FxMarkupRate,
		&i.SettledUsd,
		&i.TipUsd,
		&i.HoldReleasedUsd,
		&i.CashRepaidUsd,
		&i.AutoSellRepaidUsd,
		&i.RefundedUsd,
		&i.Status,
		&i.ReceivableLedgerTransactionID,
		&i.RepaymentLedgerTransactionID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCaptureForUpdate = `-- name: GetCaptureForUpdate :one
SELECT id, authorization_id, provider, external_capture_id, merchant_amount, merchant_currency, clearing_fx_rate, fx_markup_rate, settled_usd, tip_usd, hold_released_usd, cash_repaid_usd, auto_sell_repaid_usd, refunded_usd, status, receivable_ledger_transaction_id, repayment_ledger_transaction_id, occurred_at, created_at
FROM card.captures
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCaptureForUpdate(ctx context.Context, id pgtype.UUID) (CardCapture, error) {
	row := q.db.QueryRow(ctx, getCaptureForUpdate, id)
	var i CardCapture
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.Provider,
		&i.ExternalCaptureID,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.ClearingFxRate,
		&i.FxMarkupRate,
		&i.SettledUsd,
		&i.TipUsd,
		&i.HoldReleasedUsd,
		&i.CashRepaidUsd,
		&i.AutoSellRepaidUsd,
		&i.RefundedUsd,
		&i.Status,
		&i.ReceivableLedgerTransactionID,
		&i.RepaymentLedgerTransactionID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
SELECT id, customer_reference, card_type, status, display_name, last4, pin_set, provider, provider_card_reference, apple_wallet_status, google_wallet_status, replacement_for_card_id, policy_version, created_at, updated_at, version
FROM card.cards
WHERE id = $1
`

func (q *Queries) GetCard(ctx context.Context, id pgtype.UUID) (CardCard, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i CardCard
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardType,
		&i.Status,
		&i.DisplayName,
		&i.Last4,
		&i.PinSet,
		&i.Provider,
		&i.ProviderCardReference,
		&i.AppleWalletStatus,
		&i.GoogleWalletStatus,
		&i.ReplacementForCardID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCardForUpdate = `-- name: GetCardForUpdate :one
SELECT id, customer_reference, card_type, status, display_name, last4, pin_set, provider, provider_card_reference, apple_wallet_status, google_wallet_status, replacement_for_card_id, policy_version, created_at, updated_at, version
FROM card.cards
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCardForUpdate(ctx context.Context, id pgtype.UUID) (CardCard, error) {
	row := q.db.QueryRow(ctx, getCardForUpdate, id)
	var i CardCard
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardType,
		&i.Status,
		&i.DisplayName,
		&i.Last4,
		&i.PinSet,
		&i.Provider,
		&i.ProviderCardReference,
		&i.AppleWalletStatus,
		&i.GoogleWalletStatus,
		&i.ReplacementForCardID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCollateralAccount = `-- name: GetCollateralAccount :one
SELECT customer_reference, symbol, source_type, customer_ledger_account_id, provider_inventory_ledger_account_id, frozen, transferring, created_at
FROM card.collateral_accounts
WHERE customer_reference = $1
  AND symbol = $2
`

type GetCollateralAccountParams struct {
	CustomerReference string `json:"customer_reference"`
	Symbol            string `json:"symbol"`
}

func (q *Queries) GetCollateralAccount(ctx context.Context, arg GetCollateralAccountParams) (CardCollateralAccount, error) {
	row := q.db.QueryRow(ctx, getCollateralAccount, arg.CustomerReference, arg.Symbol)
	var i CardCollateralAccount
	err := row.Scan(
		&i.CustomerReference,
		&i.Symbol,
		&i.SourceType,
		&i.CustomerLedgerAccountID,
		&i.ProviderInventoryLedgerAccountID,
		&i.Frozen,
		&i.Transferring,
		&i.CreatedAt,
	)
	return i, err
}

const getCollateralAsset = `-- name: GetCollateralAsset :one
SELECT symbol, display_name, asset_class, haircut_rate, reference_price_usd, quote_status, market_status, observed_at, enabled, policy_version
FROM card.collateral_assets
WHERE symbol = $1
  AND enabled
`

func (q *Queries) GetCollateralAsset(ctx context.Context, symbol string) (CardCollateralAsset, error) {
	row := q.db.QueryRow(ctx, getCollateralAsset, symbol)
	var i CardCollateralAsset
	err := row.Scan(
		&i.Symbol,
		&i.DisplayName,
		&i.AssetClass,
		&i.HaircutRate,
		&i.ReferencePriceUsd,
		&i.QuoteStatus,
		&i.MarketStatus,
		&i.ObservedAt,
		&i.Enabled,
		&i.PolicyVersion,
	)
	return i, err
}

const getCommandRequest = `-- name: GetCommandRequest :one
SELECT customer_reference, scope, idempotency_key, request_hash, resource_id, created_at
FROM card.command_requests
WHERE customer_reference = $1
  AND scope = $2
  AND idempotency_key = $3
`

type GetCommandRequestParams struct {
	CustomerReference string `json:"customer_reference"`
	Scope             string `json:"scope"`
	IdempotencyKey    string `json:"idempotency_key"`
}

func (q *Queries) GetCommandRequest(ctx context.Context, arg GetCommandRequestParams) (CardCommandRequest, error) {
	row := q.db.QueryRow(ctx, getCommandRequest, arg.CustomerReference, arg.Scope, arg.IdempotencyKey)
	var i CardCommandRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerAuthorization = `-- name: GetCustomerAuthorization :one
SELECT id, customer_reference, card_id, provider, external_authorization_id, merchant_name, merchant_category_code, merchant_amount, merchant_currency, authorization_fx_rate, fx_markup_rate, authorized_usd, status, offline, entry_mode, occurred_at, received_at, decline_code, hold_ledger_transaction_id, captured_usd, reversed_usd, policy_version, created_at, updated_at, version
FROM card.authorizations
WHERE id = $1
  AND customer_reference = $2
`

type GetCustomerAuthorizationParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
}

func (q *Queries) GetCustomerAuthorization(ctx context.Context, arg GetCustomerAuthorizationParams) (CardAuthorization, error) {
	row := q.db.QueryRow(ctx, getCustomerAuthorization, arg.ID, arg.CustomerReference)
	var i CardAuthorization
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardID,
		&i.Provider,
		&i.ExternalAuthorizationID,
		&i.MerchantName,
		&i.MerchantCategoryCode,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.AuthorizationFxRate,
		&i.FxMarkupRate,
		&i.AuthorizedUsd,
		&i.Status,
		&i.Offline,
		&i.EntryMode,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.DeclineCode,
		&i.HoldLedgerTransactionID,
		&i.CapturedUsd,
		&i.ReversedUsd,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerCard = `-- name: GetCustomerCard :one
SELECT id, customer_reference, card_type, status, display_name, last4, pin_set, provider, provider_card_reference, apple_wallet_status, google_wallet_status, replacement_for_card_id, policy_version, created_at, updated_at, version
FROM card.cards
WHERE id = $1
  AND customer_reference = $2
`

type GetCustomerCardParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
}

func (q *Queries) GetCustomerCard(ctx context.Context, arg GetCustomerCardParams) (CardCard, error) {
	row := q.db.QueryRow(ctx, getCustomerCard, arg.ID, arg.CustomerReference)
	var i CardCard
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardType,
		&i.Status,
		&i.DisplayName,
		&i.Last4,
		&i.PinSet,
		&i.Provider,
		&i.ProviderCardReference,
		&i.AppleWalletStatus,
		&i.GoogleWalletStatus,
		&i.ReplacementForCardID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerCardForUpdate = `-- name: GetCustomerCardForUpdate :one
SELECT id, customer_reference, card_type, status, display_name, last4, pin_set, provider, provider_card_reference, apple_wallet_status, google_wallet_status, replacement_for_card_id, policy_version, created_at, updated_at, version
FROM card.cards
WHERE id = $1
  AND customer_reference = $2
FOR UPDATE
`

type GetCustomerCardForUpdateParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
}

func (q *Queries) GetCustomerCardForUpdate(ctx context.Context, arg GetCustomerCardForUpdateParams) (CardCard, error) {
	row := q.db.QueryRow(ctx, getCustomerCardForUpdate, arg.ID, arg.CustomerReference)
	var i CardCard
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardType,
		&i.Status,
		&i.DisplayName,
		&i.Last4,
		&i.PinSet,
		&i.Provider,
		&i.ProviderCardReference,
		&i.AppleWalletStatus,
		&i.GoogleWalletStatus,
		&i.ReplacementForCardID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerProfile = `-- name: GetCustomerProfile :one
SELECT customer_reference, paper_account_id, cash_ledger_account_id, receivable_ledger_account_id, provider_clearing_ledger_account_id, repayment_mode, spending_status, spending_status_reason, trust_tier, kyc_status, policy_version, created_at, updated_at, version
FROM card.customer_profiles
WHERE customer_reference = $1
`

func (q *Queries) GetCustomerProfile(ctx context.Context, customerReference string) (CardCustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfile, customerReference)
	var i CardCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ReceivableLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.RepaymentMode,
		&i.SpendingStatus,
		&i.SpendingStatusReason,
		&i.TrustTier,
		&i.KycStatus,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerProfileForUpdate = `-- name: GetCustomerProfileForUpdate :one
SELECT customer_reference, paper_account_id, cash_ledger_account_id, receivable_ledger_account_id, provider_clearing_ledger_account_id, repayment_mode, spending_status, spending_status_reason, trust_tier, kyc_status, policy_version, created_at, updated_at, version
FROM card.customer_profiles
WHERE customer_reference = $1
FOR UPDATE
`

func (q *Queries) GetCustomerProfileForUpdate(ctx context.Context, customerReference string) (CardCustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfileForUpdate, customerReference)
	var i CardCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ReceivableLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.RepaymentMode,
		&i.SpendingStatus,
		&i.SpendingStatusReason,
		&i.TrustTier,
		&i.KycStatus,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getDispute = `-- name: GetDispute :one
SELECT id, capture_id, customer_reference, amount_usd, reason_code, status, outcome, compliance_case_id, resolution_ledger_transaction_id, opened_at, resolved_at, version
FROM card.disputes
WHERE id = $1
`

func (q *Queries) GetDispute(ctx context.Context, id pgtype.UUID) (CardDispute, error) {
	row := q.db.QueryRow(ctx, getDispute, id)
	var i CardDispute
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.CustomerReference,
		&i.AmountUsd,
		&i.ReasonCode,
		&i.Status,
		&i.Outcome,
		&i.ComplianceCaseID,
		&i.ResolutionLedgerTransactionID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.Version,
	)
	return i, err
}

const getDisputeForUpdate = `-- name: GetDisputeForUpdate :one
SELECT id, capture_id, customer_reference, amount_usd, reason_code, status, outcome, compliance_case_id, resolution_ledger_transaction_id, opened_at, resolved_at, version
FROM card.disputes
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetDisputeForUpdate(ctx context.Context, id pgtype.UUID) (CardDispute, error) {
	row := q.db.QueryRow(ctx, getDisputeForUpdate, id)
	var i CardDispute
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.CustomerReference,
		&i.AmountUsd,
		&i.ReasonCode,
		&i.Status,
		&i.Outcome,
		&i.ComplianceCaseID,
		&i.ResolutionLedgerTransactionID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.Version,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT policy_version, auth_fx_markup_rate, maximum_tip_rate, protected_limit_guardrail_rate, absolute_spending_cap_usd, provider_spending_cap_usd, default_daily_auto_sell_usd, quote_max_age_seconds, statement_cycle_days, effective_at, active, created_at
FROM card.policies
WHERE policy_version = $1
`

func (q *Queries) GetPolicy(ctx context.Context, policyVersion string) (CardPolicy, error) {
	row := q.db.QueryRow(ctx, getPolicy, policyVersion)
	var i CardPolicy
	err := row.Scan(
		&i.PolicyVersion,
		&i.AuthFxMarkupRate,
		&i.MaximumTipRate,
		&i.ProtectedLimitGuardrailRate,
		&i.AbsoluteSpendingCapUsd,
		&i.ProviderSpendingCapUsd,
		&i.DefaultDailyAutoSellUsd,
		&i.QuoteMaxAgeSeconds,
		&i.StatementCycleDays,
		&i.EffectiveAt,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderEvent = `-- name: GetProviderEvent :one
SELECT provider, external_event_id, event_type, payload_hash, resource_type, resource_id, received_at
FROM card.provider_events
WHERE provider = $1
  AND external_event_id = $2
`

type GetProviderEventParams struct {
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (CardProviderEvent, error) {
	row := q.db.QueryRow(ctx, getProviderEvent, arg.Provider, arg.ExternalEventID)
	var i CardProviderEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.EventType,
		&i.PayloadHash,
		&i.ResourceType,
		&i.ResourceID,
		&i.ReceivedAt,
	)
	return i, err
}

const getRefund = `-- name: GetRefund :one
SELECT id, capture_id, provider, external_refund_id, refund_usd, receivable_reduction_usd, cash_credit_usd, ledger_transaction_id, occurred_at, created_at
FROM card.refunds
WHERE id = $1
`

func (q *Queries) GetRefund(ctx context.Context, id pgtype.UUID) (CardRefund, error) {
	row := q.db.QueryRow(ctx, getRefund, id)
	var i CardRefund
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.Provider,
		&i.ExternalRefundID,
		&i.RefundUsd,
		&i.ReceivableReductionUsd,
		&i.CashCreditUsd,
		&i.LedgerTransactionID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStatement = `-- name: GetStatement :one
SELECT id, customer_reference, period_start, period_end, amount_due_usd, status, due_at, paid_at, repayment_ledger_transaction_id, created_at
FROM card.statements
WHERE id = $1
`

func (q *Queries) GetStatement(ctx context.Context, id pgtype.UUID) (CardStatement, error) {
	row := q.db.QueryRow(ctx, getStatement, id)
	var i CardStatement
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.AmountDueUsd,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.RepaymentLedgerTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const getStatementByPeriod = `-- name: GetStatementByPeriod :one
SELECT id, customer_reference, period_start, period_end, amount_due_usd, status, due_at, paid_at, repayment_ledger_transaction_id, created_at
FROM card.statements
WHERE customer_reference = $1
  AND period_start = $2
  AND period_end = $3
`

type GetStatementByPeriodParams struct {
	CustomerReference string      `json:"customer_reference"`
	PeriodStart       pgtype.Date `json:"period_start"`
	PeriodEnd         pgtype.Date `json:"period_end"`
}

func (q *Queries) GetStatementByPeriod(ctx context.Context, arg GetStatementByPeriodParams) (CardStatement, error) {
	row := q.db.QueryRow(ctx, getStatementByPeriod, arg.CustomerReference, arg.PeriodStart, arg.PeriodEnd)
	var i CardStatement
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.AmountDueUsd,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.RepaymentLedgerTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const getStatementForUpdate = `-- name: GetStatementForUpdate :one
SELECT id, customer_reference, period_start, period_end, amount_due_usd, status, due_at, paid_at, repayment_ledger_transaction_id, created_at
FROM card.statements
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetStatementForUpdate(ctx context.Context, id pgtype.UUID) (CardStatement, error) {
	row := q.db.QueryRow(ctx, getStatementForUpdate, id)
	var i CardStatement
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.AmountDueUsd,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.RepaymentLedgerTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertAutoSellExecution = `-- name: InsertAutoSellExecution :one
INSERT INTO card.auto_sell_executions (
    id, capture_id, mandate_id, execution_sequence, symbol,
    requested_quantity, protected_limit_price, execution_price,
    filled_quantity, proceeds_usd, status, failure_code,
    ledger_transaction_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10, $11,
    $12, $13
)
RETURNING id, capture_id, mandate_id, execution_sequence, symbol, requested_quantity, protected_limit_price, execution_price, filled_quantity, proceeds_usd, status, failure_code, ledger_transaction_id, created_at
`

type InsertAutoSellExecutionParams struct {
	ID                  pgtype.UUID   `json:"id"`
	CaptureID           pgtype.UUID   `json:"capture_id"`
	MandateID           pgtype.UUID   `json:"mandate_id"`
	ExecutionSequence   int16         `json:"execution_sequence"`
	Symbol              string        `json:"symbol"`
	RequestedQuantity   money.Decimal `json:"requested_quantity"`
	ProtectedLimitPrice money.Decimal `json:"protected_limit_price"`
	ExecutionPrice      money.Decimal `json:"execution_price"`
	FilledQuantity      money.Decimal `json:"filled_quantity"`
	ProceedsUsd         money.Decimal `json:"proceeds_usd"`
	Status              string        `json:"status"`
	FailureCode         pgtype.Text   `json:"failure_code"`
	LedgerTransactionID pgtype.UUID   `json:"ledger_transaction_id"`
}

func (q *Queries) InsertAutoSellExecution(ctx context.Context, arg InsertAutoSellExecutionParams) (CardAutoSellExecution, error) {
	row := q.db.QueryRow(ctx, insertAutoSellExecution,
		arg.ID,
		arg.CaptureID,
		arg.MandateID,
		arg.ExecutionSequence,
		arg.Symbol,
		arg.RequestedQuantity,
		arg.ProtectedLimitPrice,
		arg.ExecutionPrice,
		arg.FilledQuantity,
		arg.ProceedsUsd,
		arg.Status,
		arg.FailureCode,
		arg.LedgerTransactionID,
	)
	var i CardAutoSellExecution
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.MandateID,
		&i.ExecutionSequence,
		&i.Symbol,
		&i.RequestedQuantity,
		&i.ProtectedLimitPrice,
		&i.ExecutionPrice,
		&i.FilledQuantity,
		&i.ProceedsUsd,
		&i.Status,
		&i.FailureCode,
		&i.LedgerTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertAutoSellMandateAsset = `-- name: InsertAutoSellMandateAsset :one
INSERT INTO card.auto_sell_mandate_assets (
    mandate_id, priority, symbol, minimum_retain_quantity
) VALUES (
    $1, $2, $3,
    $4
)
RETURNING mandate_id, priority, symbol, minimum_retain_quantity
`

type InsertAutoSellMandateAssetParams struct {
	MandateID             pgtype.UUID   `json:"mandate_id"`
	Priority              int16         `json:"priority"`
	Symbol                string        `json:"symbol"`
	MinimumRetainQuantity money.Decimal `json:"minimum_retain_quantity"`
}

func (q *Queries) InsertAutoSellMandateAsset(ctx context.Context, arg InsertAutoSellMandateAssetParams) (CardAutoSellMandateAsset, error) {
	row := q.db.QueryRow(ctx, insertAutoSellMandateAsset,
		arg.MandateID,
		arg.Priority,
		arg.Symbol,
		arg.MinimumRetainQuantity,
	)
	var i CardAutoSellMandateAsset
	err := row.Scan(
		&i.MandateID,
		&i.Priority,
		&i.Symbol,
		&i.MinimumRetainQuantity,
	)
	return i, err
}

const insertCollateralAccount = `-- name: InsertCollateralAccount :one
INSERT INTO card.collateral_accounts (
    customer_reference, symbol, customer_ledger_account_id,
    provider_inventory_ledger_account_id
) VALUES (
    $1, $2, $3,
    $4
)
ON CONFLICT (customer_reference, symbol) DO NOTHING
RETURNING customer_reference, symbol, source_type, customer_ledger_account_id, provider_inventory_ledger_account_id, frozen, transferring, created_at
`

type InsertCollateralAccountParams struct {
	CustomerReference                string      `json:"customer_reference"`
	Symbol                           string      `json:"symbol"`
	CustomerLedgerAccountID          pgtype.UUID `json:"customer_ledger_account_id"`
	ProviderInventoryLedgerAccountID pgtype.UUID `json:"provider_inventory_ledger_account_id"`
}

func (q *Queries) InsertCollateralAccount(ctx context.Context, arg InsertCollateralAccountParams) (CardCollateralAccount, error) {
	row := q.db.QueryRow(ctx, insertCollateralAccount,
		arg.CustomerReference,
		arg.Symbol,
		arg.CustomerLedgerAccountID,
		arg.ProviderInventoryLedgerAccountID,
	)
	var i CardCollateralAccount
	err := row.Scan(
		&i.CustomerReference,
		&i.Symbol,
		&i.SourceType,
		&i.CustomerLedgerAccountID,
		&i.ProviderInventoryLedgerAccountID,
		&i.Frozen,
		&i.Transferring,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommandRequest = `-- name: InsertCommandRequest :one
INSERT INTO card.command_requests (
    customer_reference, scope, idempotency_key, request_hash, resource_id
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (customer_reference, scope, idempotency_key) DO NOTHING
RETURNING resource_id
`

type InsertCommandRequestParams struct {
	CustomerReference string      `json:"customer_reference"`
	Scope             string      `json:"scope"`
	IdempotencyKey    string      `json:"idempotency_key"`
	RequestHash       string      `json:"request_hash"`
	ResourceID        pgtype.UUID `json:"resource_id"`
}

func (q *Queries) InsertCommandRequest(ctx context.Context, arg InsertCommandRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCommandRequest,
		arg.CustomerReference,
		arg.Scope,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResourceID,
	)
	var resource_id pgtype.UUID
	err := row.Scan(&resource_id)
	return resource_id, err
}

const insertLifecycleEvent = `-- name: InsertLifecycleEvent :one
INSERT INTO card.lifecycle_events (
    card_id, from_status, to_status, action, actor_type, actor_id, reason_code
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, card_id, from_status, to_status, action, actor_type, actor_id, reason_code, occurred_at
`

type InsertLifecycleEventParams struct {
	CardID     pgtype.UUID `json:"card_id"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	Action     string      `json:"action"`
	ActorType  string      `json:"actor_type"`
	ActorID    string      `json:"actor_id"`
	ReasonCode pgtype.Text `json:"reason_code"`
}

func (q *Queries) InsertLifecycleEvent(ctx context.Context, arg InsertLifecycleEventParams) (CardLifecycleEvent, error) {
	row := q.db.QueryRow(ctx, insertLifecycleEvent,
		arg.CardID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Action,
		arg.ActorType,
		arg.ActorID,
		arg.ReasonCode,
	)
	var i CardLifecycleEvent
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Action,
		&i.ActorType,
		&i.ActorID,
		&i.ReasonCode,
		&i.OccurredAt,
	)
	return i, err
}

const insertProviderEvent = `-- name: InsertProviderEvent :one
INSERT INTO card.provider_events (
    provider, external_event_id, event_type, payload_hash, resource_type, resource_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (provider, external_event_id) DO NOTHING
RETURNING resource_id
`

type InsertProviderEventParams struct {
	Provider        string      `json:"provider"`
	ExternalEventID string      `json:"external_event_id"`
	EventType       string      `json:"event_type"`
	PayloadHash     string      `json:"payload_hash"`
	ResourceType    string      `json:"resource_type"`
	ResourceID      pgtype.UUID `json:"resource_id"`
}

func (q *Queries) InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProviderEvent,
		arg.Provider,
		arg.ExternalEventID,
		arg.EventType,
		arg.PayloadHash,
		arg.ResourceType,
		arg.ResourceID,
	)
	var resource_id pgtype.UUID
	err := row.Scan(&resource_id)
	return resource_id, err
}

const insertReconciliationRun = `-- name: InsertReconciliationRun :one
INSERT INTO card.reconciliation_runs (
    id, customer_reference, ledger_hold_usd, provider_hold_usd,
    ledger_receivable_usd, provider_receivable_usd, difference_usd,
    status, compliance_case_id, started_at, completed_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9, $10,
    $11
)
RETURNING id, customer_reference, ledger_hold_usd, provider_hold_usd, ledger_receivable_usd, provider_receivable_usd, difference_usd, status, compliance_case_id, started_at, completed_at
`

type InsertReconciliationRunParams struct {
	ID                    pgtype.UUID        `json:"id"`
	CustomerReference     string             `json:"customer_reference"`
	LedgerHoldUsd         money.Decimal      `json:"ledger_hold_usd"`
	ProviderHoldUsd       money.Decimal      `json:"provider_hold_usd"`
	LedgerReceivableUsd   money.Decimal      `json:"ledger_receivable_usd"`
	ProviderReceivableUsd money.Decimal      `json:"provider_receivable_usd"`
	DifferenceUsd         money.Decimal      `json:"difference_usd"`
	Status                string             `json:"status"`
	ComplianceCaseID      pgtype.UUID        `json:"compliance_case_id"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) InsertReconciliationRun(ctx context.Context, arg InsertReconciliationRunParams) (CardReconciliationRun, error) {
	row := q.db.QueryRow(ctx, insertReconciliationRun,
		arg.ID,
		arg.CustomerReference,
		arg.LedgerHoldUsd,
		arg.ProviderHoldUsd,
		arg.LedgerReceivableUsd,
		arg.ProviderReceivableUsd,
		arg.DifferenceUsd,
		arg.Status,
		arg.ComplianceCaseID,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i CardReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.LedgerHoldUsd,
		&i.ProviderHoldUsd,
		&i.LedgerReceivableUsd,
		&i.ProviderReceivableUsd,
		&i.DifferenceUsd,
		&i.Status,
		&i.ComplianceCaseID,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAuthorizations = `-- name: ListAuthorizations :many
SELECT id, customer_reference, card_id, provider, external_authorization_id, merchant_name, merchant_category_code, merchant_amount, merchant_currency, authorization_fx_rate, fx_markup_rate, authorized_usd, status, offline, entry_mode, occurred_at, received_at, decline_code, hold_ledger_transaction_id, captured_usd, reversed_usd, policy_version, created_at, updated_at, version
FROM card.authorizations
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAuthorizationsParams struct {
	CustomerReference string `json:"customer_reference"`
	PageSize          int32  `json:"page_size"`
}

func (q *Queries) ListAuthorizations(ctx context.Context, arg ListAuthorizationsParams) ([]CardAuthorization, error) {
	rows, err := q.db.Query(ctx, listAuthorizations, arg.CustomerReference, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardAuthorization
	for rows.Next() {
		var i CardAuthorization
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.CardID,
			&i.Provider,
			&i.ExternalAuthorizationID,
			&i.MerchantName,
			&i.MerchantCategoryCode,
			&i.MerchantAmount,
			&i.MerchantCurrency,
			&i.AuthorizationFxRate,
			&i.FxMarkupRate,
			&i.AuthorizedUsd,
			&i.Status,
			&i.Offline,
			&i.EntryMode,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.DeclineCode,
			&i.HoldLedgerTransactionID,
			&i.CapturedUsd,
			&i.ReversedUsd,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoSellExecutions = `-- name: ListAutoSellExecutions :many
SELECT id, capture_id, mandate_id, execution_sequence, symbol, requested_quantity, protected_limit_price, execution_price, filled_quantity, proceeds_usd, status, failure_code, ledger_transaction_id, created_at
FROM card.auto_sell_executions
WHERE capture_id = $1
ORDER BY execution_sequence
`

func (q *Queries) ListAutoSellExecutions(ctx context.Context, captureID pgtype.UUID) ([]CardAutoSellExecution, error) {
	rows, err := q.db.Query(ctx, listAutoSellExecutions, captureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardAutoSellExecution
	for rows.Next() {
		var i CardAutoSellExecution
		if err := rows.Scan(
			&i.ID,
			&i.CaptureID,
			&i.MandateID,
			&i.ExecutionSequence,
			&i.Symbol,
			&i.RequestedQuantity,
			&i.ProtectedLimitPrice,
			&i.ExecutionPrice,
			&i.FilledQuantity,
			&i.ProceedsUsd,
			&i.Status,
			&i.FailureCode,
			&i.LedgerTransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoSellMandateAssets = `-- name: ListAutoSellMandateAssets :many
SELECT mandate_id, priority, symbol, minimum_retain_quantity
FROM card.auto_sell_mandate_assets
WHERE mandate_id = $1
ORDER BY priority
`

func (q *Queries) ListAutoSellMandateAssets(ctx context.Context, mandateID pgtype.UUID) ([]CardAutoSellMandateAsset, error) {
	rows, err := q.db.Query(ctx, listAutoSellMandateAssets, mandateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardAutoSellMandateAsset
	for rows.Next() {
		var i CardAutoSellMandateAsset
		if err := rows.Scan(
			&i.MandateID,
			&i.Priority,
			&i.Symbol,
			&i.MinimumRetainQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapturesForAuthorization = `-- name: ListCapturesForAuthorization :many
SELECT id, authorization_id, provider, external_capture_id, merchant_amount, merchant_currency, clearing_fx_rate, fx_markup_rate, settled_usd, tip_usd, hold_released_usd, cash_repaid_usd, auto_sell_repaid_usd, refunded_usd, status, receivable_ledger_transaction_id, repayment_ledger_transaction_id, occurred_at, created_at
FROM card.captures
WHERE authorization_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCapturesForAuthorization(ctx context.Context, authorizationID pgtype.UUID) ([]CardCapture, error) {
	rows, err := q.db.Query(ctx, listCapturesForAuthorization, authorizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardCapture
	for rows.Next() {
		var i CardCapture
		if err := rows.Scan(
			&i.ID,
			&i.AuthorizationID,
			&i.Provider,
			&i.ExternalCaptureID,
			&i.MerchantAmount,
			&i.MerchantCurrency,
			&i.ClearingFxRate,
			&i.FxMarkupRate,
			&i.SettledUsd,
			&i.TipUsd,
			&i.HoldReleasedUsd,
			&i.CashRepaidUsd,
			&i.AutoSellRepaidUsd,
			&i.RefundedUsd,
			&i.Status,
			&i.ReceivableLedgerTransactionID,
			&i.RepaymentLedgerTransactionID,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCards = `-- name: ListCards :many
SELECT id, customer_reference, card_type, status, display_name, last4, pin_set, provider, provider_card_reference, apple_wallet_status, google_wallet_status, replacement_for_card_id, policy_version, created_at, updated_at, version
FROM card.cards
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCards(ctx context.Context, customerReference string) ([]CardCard, error) {
	rows, err := q.db.Query(ctx, listCards, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardCard
	for rows.Next() {
		var i CardCard
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.CardType,
			&i.Status,
			&i.DisplayName,
			&i.Last4,
			&i.PinSet,
			&i.Provider,
			&i.ProviderCardReference,
			&i.AppleWalletStatus,
			&i.GoogleWalletStatus,
			&i.ReplacementForCardID,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollateralAccounts = `-- name: ListCollateralAccounts :many
SELECT
    accounts.customer_reference,
    accounts.symbol,
    accounts.source_type,
    accounts.customer_ledger_account_id,
    accounts.provider_inventory_ledger_account_id,
    accounts.frozen,
    accounts.transferring,
    assets.display_name,
    assets.asset_class,
    assets.haircut_rate,
    assets.reference_price_usd,
    assets.quote_status,
    assets.market_status,
    assets.observed_at,
    assets.policy_version
FROM card.collateral_accounts AS accounts
JOIN card.collateral_assets AS assets ON assets.symbol = accounts.symbol
WHERE accounts.customer_reference = $1
ORDER BY accounts.symbol
`

type ListCollateralAccountsRow struct {
	CustomerReference                string             `json:"customer_reference"`
	Symbol                           string             `json:"symbol"`
	SourceType                       string             `json:"source_type"`
	CustomerLedgerAccountID          pgtype.UUID        `json:"customer_ledger_account_id"`
	ProviderInventoryLedgerAccountID pgtype.UUID        `json:"provider_inventory_ledger_account_id"`
	Frozen                           bool               `json:"frozen"`
	Transferring                     bool               `json:"transferring"`
	DisplayName                      string             `json:"display_name"`
	AssetClass                       string             `json:"asset_class"`
	HaircutRate                      money.Decimal      `json:"haircut_rate"`
	ReferencePriceUsd                money.Decimal      `json:"reference_price_usd"`
	QuoteStatus                      string             `json:"quote_status"`
	MarketStatus                     string             `json:"market_status"`
	ObservedAt                       pgtype.Timestamptz `json:"observed_at"`
	PolicyVersion                    string             `json:"policy_version"`
}

func (q *Queries) ListCollateralAccounts(ctx context.Context, customerReference string) ([]ListCollateralAccountsRow, error) {
	rows, err := q.db.Query(ctx, listCollateralAccounts, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollateralAccountsRow
	for rows.Next() {
		var i ListCollateralAccountsRow
		if err := rows.Scan(
			&i.CustomerReference,
			&i.Symbol,
			&i.SourceType,
			&i.CustomerLedgerAccountID,
			&i.ProviderInventoryLedgerAccountID,
			&i.Frozen,
			&i.Transferring,
			&i.DisplayName,
			&i.AssetClass,
			&i.HaircutRate,
			&i.ReferencePriceUsd,
			&i.QuoteStatus,
			&i.MarketStatus,
			&i.ObservedAt,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollateralAssets = `-- name: ListCollateralAssets :many
SELECT symbol, display_name, asset_class, haircut_rate, reference_price_usd, quote_status, market_status, observed_at, enabled, policy_version
FROM card.collateral_assets
WHERE enabled
ORDER BY symbol
`

func (q *Queries) ListCollateralAssets(ctx context.Context) ([]CardCollateralAsset, error) {
	rows, err := q.db.Query(ctx, listCollateralAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardCollateralAsset
	for rows.Next() {
		var i CardCollateralAsset
		if err := rows.Scan(
			&i.Symbol,
			&i.DisplayName,
			&i.AssetClass,
			&i.HaircutRate,
			&i.ReferencePriceUsd,
			&i.QuoteStatus,
			&i.MarketStatus,
			&i.ObservedAt,
			&i.Enabled,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerCaptures = `-- name: ListCustomerCaptures :many
SELECT captures.id, captures.authorization_id, captures.provider, captures.external_capture_id, captures.merchant_amount, captures.merchant_currency, captures.clearing_fx_rate, captures.fx_markup_rate, captures.settled_usd, captures.tip_usd, captures.hold_released_usd, captures.cash_repaid_usd, captures.auto_sell_repaid_usd, captures.refunded_usd, captures.status, captures.receivable_ledger_transaction_id, captures.repayment_ledger_transaction_id, captures.occurred_at, captures.created_at
FROM card.captures AS captures
JOIN card.authorizations AS authorizations ON authorizations.id = captures.authorization_id
WHERE authorizations.customer_reference = $1
ORDER BY captures.created_at DESC, captures.id DESC
LIMIT $2
`

type ListCustomerCapturesParams struct {
	CustomerReference string `json:"customer_reference"`
	PageSize          int32  `json:"page_size"`
}

func (q *Queries) ListCustomerCaptures(ctx context.Context, arg ListCustomerCapturesParams) ([]CardCapture, error) {
	rows, err := q.db.Query(ctx, listCustomerCaptures, arg.CustomerReference, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardCapture
	for rows.Next() {
		var i CardCapture
		if err := rows.Scan(
			&i.ID,
			&i.AuthorizationID,
			&i.Provider,
			&i.ExternalCaptureID,
			&i.MerchantAmount,
			&i.MerchantCurrency,
			&i.ClearingFxRate,
			&i.FxMarkupRate,
			&i.SettledUsd,
			&i.TipUsd,
			&i.HoldReleasedUsd,
			&i.CashRepaidUsd,
			&i.AutoSellRepaidUsd,
			&i.RefundedUsd,
			&i.Status,
			&i.ReceivableLedgerTransactionID,
			&i.RepaymentLedgerTransactionID,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputes = `-- name: ListDisputes :many
SELECT id, capture_id, customer_reference, amount_usd, reason_code, status, outcome, compliance_case_id, resolution_ledger_transaction_id, opened_at, resolved_at, version
FROM card.disputes
WHERE ($1::TEXT = '' OR customer_reference = $1)
ORDER BY opened_at DESC, id DESC
LIMIT $2
`

type ListDisputesParams struct {
	CustomerFilter string `json:"customer_filter"`
	PageSize       int32  `json:"page_size"`
}

func (q *Queries) ListDisputes(ctx context.Context, arg ListDisputesParams) ([]CardDispute, error) {
	rows, err := q.db.Query(ctx, listDisputes, arg.CustomerFilter, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardDispute
	for rows.Next() {
		var i CardDispute
		if err := rows.Scan(
			&i.ID,
			&i.CaptureID,
			&i.CustomerReference,
			&i.AmountUsd,
			&i.ReasonCode,
			&i.Status,
			&i.Outcome,
			&i.ComplianceCaseID,
			&i.ResolutionLedgerTransactionID,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycleEvents = `-- name: ListLifecycleEvents :many
SELECT id, card_id, from_status, to_status, action, actor_type, actor_id, reason_code, occurred_at
FROM card.lifecycle_events
WHERE card_id = $1
ORDER BY occurred_at, id
`

func (q *Queries) ListLifecycleEvents(ctx context.Context, cardID pgtype.UUID) ([]CardLifecycleEvent, error) {
	rows, err := q.db.Query(ctx, listLifecycleEvents, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardLifecycleEvent
	for rows.Next() {
		var i CardLifecycleEvent
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Action,
			&i.ActorType,
			&i.ActorID,
			&i.ReasonCode,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationRuns = `-- name: ListReconciliationRuns :many
SELECT id, customer_reference, ledger_hold_usd, provider_hold_usd, ledger_receivable_usd, provider_receivable_usd, difference_usd, status, compliance_case_id, started_at, completed_at
FROM card.reconciliation_runs
WHERE ($1::TEXT = '' OR customer_reference = $1)
ORDER BY completed_at DESC, id DESC
LIMIT $2
`

type ListReconciliationRunsParams struct {
	CustomerFilter string `json:"customer_filter"`
	PageSize       int32  `json:"page_size"`
}

func (q *Queries) ListReconciliationRuns(ctx context.Context, arg ListReconciliationRunsParams) ([]CardReconciliationRun, error) {
	rows, err := q.db.Query(ctx, listReconciliationRuns, arg.CustomerFilter, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardReconciliationRun
	for rows.Next() {
		var i CardReconciliationRun
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.LedgerHoldUsd,
			&i.ProviderHoldUsd,
			&i.LedgerReceivableUsd,
			&i.ProviderReceivableUsd,
			&i.DifferenceUsd,
			&i.Status,
			&i.ComplianceCaseID,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsForCapture = `-- name: ListRefundsForCapture :many
SELECT id, capture_id, provider, external_refund_id, refund_usd, receivable_reduction_usd, cash_credit_usd, ledger_transaction_id, occurred_at, created_at
FROM card.refunds
WHERE capture_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListRefundsForCapture(ctx context.Context, captureID pgtype.UUID) ([]CardRefund, error) {
	rows, err := q.db.Query(ctx, listRefundsForCapture, captureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardRefund
	for rows.Next() {
		var i CardRefund
		if err := rows.Scan(
			&i.ID,
			&i.CaptureID,
			&i.Provider,
			&i.ExternalRefundID,
			&i.RefundUsd,
			&i.ReceivableReductionUsd,
			&i.CashCreditUsd,
			&i.LedgerTransactionID,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatements = `-- name: ListStatements :many
SELECT id, customer_reference, period_start, period_end, amount_due_usd, status, due_at, paid_at, repayment_ledger_transaction_id, created_at
FROM card.statements
WHERE customer_reference = $1
ORDER BY period_end DESC, id DESC
`

func (q *Queries) ListStatements(ctx context.Context, customerReference string) ([]CardStatement, error) {
	rows, err := q.db.Query(ctx, listStatements, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardStatement
	for rows.Next() {
		var i CardStatement
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.AmountDueUsd,
			&i.Status,
			&i.DueAt,
			&i.PaidAt,
			&i.RepaymentLedgerTransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCaptureDisputed = `-- name: MarkCaptureDisputed :one
UPDATE card.captures
SET status = 'DISPUTED'
WHERE id = $1
  AND status IN ('CAPTURED', 'PARTIALLY_REFUNDED')
RETURNING id, authorization_id, provider, external_capture_id, merchant_amount, merchant_currency, clearing_fx_rate, fx_markup_rate, settled_usd, tip_usd, hold_released_usd, cash_repaid_usd, auto_sell_repaid_usd, refunded_usd, status, receivable_ledger_transaction_id, repayment_ledger_transaction_id, occurred_at, created_at
`

func (q *Queries) MarkCaptureDisputed(ctx context.Context, id pgtype.UUID) (CardCapture, error) {
	row := q.db.QueryRow(ctx, markCaptureDisputed, id)
	var i CardCapture
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.Provider,
		&i.ExternalCaptureID,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.ClearingFxRate,
		&i.FxMarkupRate,
		&i.SettledUsd,
		&i.TipUsd,
		&i.HoldReleasedUsd,
		&i.CashRepaidUsd,
		&i.AutoSellRepaidUsd,
		&i.RefundedUsd,
		&i.Status,
		&i.ReceivableLedgerTransactionID,
		&i.RepaymentLedgerTransactionID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const markStatementPaid = `-- name: MarkStatementPaid :one
UPDATE card.statements
SET status = 'PAID',
    paid_at = clock_timestamp(),
    repayment_ledger_transaction_id = $1
WHERE id = $2
  AND status IN ('OPEN', 'PAST_DUE')
RETURNING id, customer_reference, period_start, period_end, amount_due_usd, status, due_at, paid_at, repayment_ledger_transaction_id, created_at
`

type MarkStatementPaidParams struct {
	RepaymentLedgerTransactionID pgtype.UUID `json:"repayment_ledger_transaction_id"`
	ID                           pgtype.UUID `json:"id"`
}

func (q *Queries) MarkStatementPaid(ctx context.Context, arg MarkStatementPaidParams) (CardStatement, error) {
	row := q.db.QueryRow(ctx, markStatementPaid, arg.RepaymentLedgerTransactionID, arg.ID)
	var i CardStatement
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.AmountDueUsd,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.RepaymentLedgerTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE card.disputes
SET status = 'RESOLVED',
    outcome = $1,
    resolution_ledger_transaction_id = $2,
    resolved_at = clock_timestamp(),
    version = version + 1
WHERE id = $3
  AND status IN ('OPEN', 'UNDER_REVIEW')
RETURNING id, capture_id, customer_reference, amount_usd, reason_code, status, outcome, compliance_case_id, resolution_ledger_transaction_id, opened_at, resolved_at, version
`

type ResolveDisputeParams struct {
	Outcome                       pgtype.Text `json:"outcome"`
	ResolutionLedgerTransactionID pgtype.UUID `json:"resolution_ledger_transaction_id"`
	ID                            pgtype.UUID `json:"id"`
}

func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (CardDispute, error) {
	row := q.db.QueryRow(ctx, resolveDispute, arg.Outcome, arg.ResolutionLedgerTransactionID, arg.ID)
	var i CardDispute
	err := row.Scan(
		&i.ID,
		&i.CaptureID,
		&i.CustomerReference,
		&i.AmountUsd,
		&i.ReasonCode,
		&i.Status,
		&i.Outcome,
		&i.ComplianceCaseID,
		&i.ResolutionLedgerTransactionID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.Version,
	)
	return i, err
}

const sumAcceptedDisputeAmountForCapture = `-- name: SumAcceptedDisputeAmountForCapture :one
SELECT COALESCE(SUM(amount_usd), 0)::NUMERIC(38, 18) AS total_usd
FROM card.disputes
WHERE capture_id = $1
  AND status = 'RESOLVED'
  AND outcome = 'ACCEPTED'
`

func (q *Queries) SumAcceptedDisputeAmountForCapture(ctx context.Context, captureID pgtype.UUID) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumAcceptedDisputeAmountForCapture, captureID)
	var total_usd money.Decimal
	err := row.Scan(&total_usd)
	return total_usd, err
}

const sumDailyAutoSell = `-- name: SumDailyAutoSell :one
SELECT COALESCE(SUM(executions.proceeds_usd), 0)::NUMERIC(38, 18) AS total_usd
FROM card.auto_sell_executions AS executions
JOIN card.captures AS captures ON captures.id = executions.capture_id
JOIN card.authorizations AS authorizations ON authorizations.id = captures.authorization_id
WHERE authorizations.customer_reference = $1
  AND executions.created_at >= $2
  AND executions.status IN ('FILLED', 'PARTIALLY_FILLED')
`

type SumDailyAutoSellParams struct {
	CustomerReference string             `json:"customer_reference"`
	SinceTime         pgtype.Timestamptz `json:"since_time"`
}

func (q *Queries) SumDailyAutoSell(ctx context.Context, arg SumDailyAutoSellParams) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumDailyAutoSell, arg.CustomerReference, arg.SinceTime)
	var total_usd money.Decimal
	err := row.Scan(&total_usd)
	return total_usd, err
}

const sumDisputedAmountForCapture = `-- name: SumDisputedAmountForCapture :one
SELECT COALESCE(SUM(amount_usd), 0)::NUMERIC(38, 18) AS total_usd
FROM card.disputes
WHERE capture_id = $1
  AND status IN ('OPEN', 'UNDER_REVIEW', 'RESOLVED')
  AND (status <> 'RESOLVED' OR outcome = 'ACCEPTED')
`

func (q *Queries) SumDisputedAmountForCapture(ctx context.Context, captureID pgtype.UUID) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumDisputedAmountForCapture, captureID)
	var total_usd money.Decimal
	err := row.Scan(&total_usd)
	return total_usd, err
}

const unfreezeSpending = `-- name: UnfreezeSpending :one
UPDATE card.customer_profiles
SET spending_status = 'ACTIVE',
    spending_status_reason = NULL,
    updated_at = clock_timestamp(),
    version = version + 1
WHERE customer_reference = $1
RETURNING customer_reference, paper_account_id, cash_ledger_account_id, receivable_ledger_account_id, provider_clearing_ledger_account_id, repayment_mode, spending_status, spending_status_reason, trust_tier, kyc_status, policy_version, created_at, updated_at, version
`

func (q *Queries) UnfreezeSpending(ctx context.Context, customerReference string) (CardCustomerProfile, error) {
	row := q.db.QueryRow(ctx, unfreezeSpending, customerReference)
	var i CardCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ReceivableLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.RepaymentMode,
		&i.SpendingStatus,
		&i.SpendingStatusReason,
		&i.TrustTier,
		&i.KycStatus,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateAuthorizationTotals = `-- name: UpdateAuthorizationTotals :one
UPDATE card.authorizations
SET status = $1,
    captured_usd = $2,
    reversed_usd = $3,
    updated_at = clock_timestamp(),
    version = version + 1
WHERE id = $4
RETURNING id, customer_reference, card_id, provider, external_authorization_id, merchant_name, merchant_category_code, merchant_amount, merchant_currency, authorization_fx_rate, fx_markup_rate, authorized_usd, status, offline, entry_mode, occurred_at, received_at, decline_code, hold_ledger_transaction_id, captured_usd, reversed_usd, policy_version, created_at, updated_at, version
`

type UpdateAuthorizationTotalsParams struct {
	Status      string        `json:"status"`
	CapturedUsd money.Decimal `json:"captured_usd"`
	ReversedUsd money.Decimal `json:"reversed_usd"`
	ID          pgtype.UUID   `json:"id"`
}

func (q *Queries) UpdateAuthorizationTotals(ctx context.Context, arg UpdateAuthorizationTotalsParams) (CardAuthorization, error) {
	row := q.db.QueryRow(ctx, updateAuthorizationTotals,
		arg.Status,
		arg.CapturedUsd,
		arg.ReversedUsd,
		arg.ID,
	)
	var i CardAuthorization
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardID,
		&i.Provider,
		&i.ExternalAuthorizationID,
		&i.MerchantName,
		&i.MerchantCategoryCode,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.AuthorizationFxRate,
		&i.FxMarkupRate,
		&i.AuthorizedUsd,
		&i.Status,
		&i.Offline,
		&i.EntryMode,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.DeclineCode,
		&i.HoldLedgerTransactionID,
		&i.CapturedUsd,
		&i.ReversedUsd,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateCaptureRefund = `-- name: UpdateCaptureRefund :one
UPDATE card.captures
SET refunded_usd = $1,
    status = $2
WHERE id = $3
RETURNING id, authorization_id, provider, external_capture_id, merchant_amount, merchant_currency, clearing_fx_rate, fx_markup_rate, settled_usd, tip_usd, hold_released_usd, cash_repaid_usd, auto_sell_repaid_usd, refunded_usd, status, receivable_ledger_transaction_id, repayment_ledger_transaction_id, occurred_at, created_at
`

type UpdateCaptureRefundParams struct {
	RefundedUsd money.Decimal `json:"refunded_usd"`
	Status      string        `json:"status"`
	ID          pgtype.UUID   `json:"id"`
}

func (q *Queries) UpdateCaptureRefund(ctx context.Context, arg UpdateCaptureRefundParams) (CardCapture, error) {
	row := q.db.QueryRow(ctx, updateCaptureRefund, arg.RefundedUsd, arg.Status, arg.ID)
	var i CardCapture
	err := row.Scan(
		&i.ID,
		&i.AuthorizationID,
		&i.Provider,
		&i.ExternalCaptureID,
		&i.MerchantAmount,
		&i.MerchantCurrency,
		&i.ClearingFxRate,
		&i.FxMarkupRate,
		&i.SettledUsd,
		&i.TipUsd,
		&i.HoldReleasedUsd,
		&i.CashRepaidUsd,
		&i.AutoSellRepaidUsd,
		&i.RefundedUsd,
		&i.Status,
		&i.ReceivableLedgerTransactionID,
		&i.RepaymentLedgerTransactionID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCardState = `-- name: UpdateCardState :one
UPDATE card.cards
SET status = $1,
    pin_set = $2,
    updated_at = clock_timestamp(),
    version = version + 1
WHERE id = $3
RETURNING id, customer_reference, card_type, status, display_name, last4, pin_set, provider, provider_card_reference, apple_wallet_status, google_wallet_status, replacement_for_card_id, policy_version, created_at, updated_at, version
`

type UpdateCardStateParams struct {
	Status string      `json:"status"`
	PinSet bool        `json:"pin_set"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCardState(ctx context.Context, arg UpdateCardStateParams) (CardCard, error) {
	row := q.db.QueryRow(ctx, updateCardState, arg.Status, arg.PinSet, arg.ID)
	var i CardCard
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.CardType,
		&i.Status,
		&i.DisplayName,
		&i.Last4,
		&i.PinSet,
		&i.Provider,
		&i.ProviderCardReference,
		&i.AppleWalletStatus,
		&i.GoogleWalletStatus,
		&i.ReplacementForCardID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateCollateralQuote = `-- name: UpdateCollateralQuote :one
UPDATE card.collateral_assets
SET reference_price_usd = $1,
    quote_status = $2,
    market_status = $3,
    observed_at = $4
WHERE symbol = $5
RETURNING symbol, display_name, asset_class, haircut_rate, reference_price_usd, quote_status, market_status, observed_at, enabled, policy_version
`

type UpdateCollateralQuoteParams struct {
	ReferencePriceUsd money.Decimal      `json:"reference_price_usd"`
	QuoteStatus       string             `json:"quote_status"`
	MarketStatus      string             `json:"market_status"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
	Symbol            string             `json:"symbol"`
}

func (q *Queries) UpdateCollateralQuote(ctx context.Context, arg UpdateCollateralQuoteParams) (CardCollateralAsset, error) {
	row := q.db.QueryRow(ctx, updateCollateralQuote,
		arg.ReferencePriceUsd,
		arg.QuoteStatus,
		arg.MarketStatus,
		arg.ObservedAt,
		arg.Symbol,
	)
	var i CardCollateralAsset
	err := row.Scan(
		&i.Symbol,
		&i.DisplayName,
		&i.AssetClass,
		&i.HaircutRate,
		&i.ReferencePriceUsd,
		&i.QuoteStatus,
		&i.MarketStatus,
		&i.ObservedAt,
		&i.Enabled,
		&i.PolicyVersion,
	)
	return i, err
}

const updateRepaymentMode = `-- name: UpdateRepaymentMode :one
UPDATE card.customer_profiles
SET repayment_mode = $1,
    updated_at = clock_timestamp(),
    version = version + 1
WHERE customer_reference = $2
RETURNING customer_reference, paper_account_id, cash_ledger_account_id, receivable_ledger_account_id, provider_clearing_ledger_account_id, repayment_mode, spending_status, spending_status_reason, trust_tier, kyc_status, policy_version, created_at, updated_at, version
`

type UpdateRepaymentModeParams struct {
	RepaymentMode     string `json:"repayment_mode"`
	CustomerReference string `json:"customer_reference"`
}

func (q *Queries) UpdateRepaymentMode(ctx context.Context, arg UpdateRepaymentModeParams) (CardCustomerProfile, error) {
	row := q.db.QueryRow(ctx, updateRepaymentMode, arg.RepaymentMode, arg.CustomerReference)
	var i CardCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ReceivableLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.RepaymentMode,
		&i.SpendingStatus,
		&i.SpendingStatusReason,
		&i.TrustTier,
		&i.KycStatus,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const upsertAutoSellMandate = `-- name: UpsertAutoSellMandate :one
INSERT INTO card.auto_sell_mandates (
    id, customer_reference, enabled, allow_fractional, daily_max_usd,
    valid_until, policy_version
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7
)
ON CONFLICT (customer_reference) DO UPDATE
SET enabled = EXCLUDED.enabled,
    allow_fractional = EXCLUDED.allow_fractional,
    daily_max_usd = EXCLUDED.daily_max_usd,
    valid_until = EXCLUDED.valid_until,
    policy_version = EXCLUDED.policy_version,
    updated_at = clock_timestamp(),
    version = card.auto_sell_mandates.version + 1
RETURNING id, customer_reference, enabled, allow_fractional, daily_max_usd, valid_until, policy_version, created_at, updated_at, version
`

type UpsertAutoSellMandateParams struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	Enabled           bool               `json:"enabled"`
	AllowFractional   bool               `json:"allow_fractional"`
	DailyMaxUsd       money.Decimal      `json:"daily_max_usd"`
	ValidUntil        pgtype.Timestamptz `json:"valid_until"`
	PolicyVersion     string             `json:"policy_version"`
}

func (q *Queries) UpsertAutoSellMandate(ctx context.Context, arg UpsertAutoSellMandateParams) (CardAutoSellMandate, error) {
	row := q.db.QueryRow(ctx, upsertAutoSellMandate,
		arg.ID,
		arg.CustomerReference,
		arg.Enabled,
		arg.AllowFractional,
		arg.DailyMaxUsd,
		arg.ValidUntil,
		arg.PolicyVersion,
	)
	var i CardAutoSellMandate
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Enabled,
		&i.AllowFractional,
		&i.DailyMaxUsd,
		&i.ValidUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
