// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type CardAuthorization struct {
	ID                      pgtype.UUID        `json:"id"`
	CustomerReference       string             `json:"customer_reference"`
	CardID                  pgtype.UUID        `json:"card_id"`
	Provider                string             `json:"provider"`
	ExternalAuthorizationID string             `json:"external_authorization_id"`
	MerchantName            string             `json:"merchant_name"`
	MerchantCategoryCode    string             `json:"merchant_category_code"`
	MerchantAmount          money.Decimal      `json:"merchant_amount"`
	MerchantCurrency        string             `json:"merchant_currency"`
	AuthorizationFxRate     money.Decimal      `json:"authorization_fx_rate"`
	FxMarkupRate            money.Decimal      `json:"fx_markup_rate"`
	AuthorizedUsd           money.Decimal      `json:"authorized_usd"`
	Status                  string             `json:"status"`
	Offline                 bool               `json:"offline"`
	EntryMode               string             `json:"entry_mode"`
	OccurredAt              pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt              pgtype.Timestamptz `json:"received_at"`
	DeclineCode             pgtype.Text        `json:"decline_code"`
	HoldLedgerTransactionID pgtype.UUID        `json:"hold_ledger_transaction_id"`
	CapturedUsd             money.Decimal      `json:"captured_usd"`
	ReversedUsd             money.Decimal      `json:"reversed_usd"`
	PolicyVersion           string             `json:"policy_version"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Version                 int64              `json:"version"`
}

type CardAutoSellExecution struct {
	ID                  pgtype.UUID        `json:"id"`
	CaptureID           pgtype.UUID        `json:"capture_id"`
	MandateID           pgtype.UUID        `json:"mandate_id"`
	ExecutionSequence   int16              `json:"execution_sequence"`
	Symbol              string             `json:"symbol"`
	RequestedQuantity   money.Decimal      `json:"requested_quantity"`
	ProtectedLimitPrice money.Decimal      `json:"protected_limit_price"`
	ExecutionPrice      money.Decimal      `json:"execution_price"`
	FilledQuantity      money.Decimal      `json:"filled_quantity"`
	ProceedsUsd         money.Decimal      `json:"proceeds_usd"`
	Status              string             `json:"status"`
	FailureCode         pgtype.Text        `json:"failure_code"`
	LedgerTransactionID pgtype.UUID        `json:"ledger_transaction_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type CardAutoSellMandate struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	Enabled           bool               `json:"enabled"`
	AllowFractional   bool               `json:"allow_fractional"`
	DailyMaxUsd       money.Decimal      `json:"daily_max_usd"`
	ValidUntil        pgtype.Timestamptz `json:"valid_until"`
	PolicyVersion     string             `json:"policy_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Version           int64              `json:"version"`
}

type CardAutoSellMandateAsset struct {
	MandateID             pgtype.UUID   `json:"mandate_id"`
	Priority              int16         `json:"priority"`
	Symbol                string        `json:"symbol"`
	MinimumRetainQuantity money.Decimal `json:"minimum_retain_quantity"`
}

type CardCapture struct {
	ID                            pgtype.UUID        `json:"id"`
	AuthorizationID               pgtype.UUID        `json:"authorization_id"`
	Provider                      string             `json:"provider"`
	ExternalCaptureID             string             `json:"external_capture_id"`
	MerchantAmount                money.Decimal      `json:"merchant_amount"`
	MerchantCurrency              string             `json:"merchant_currency"`
	ClearingFxRate                money.Decimal      `json:"clearing_fx_rate"`
	FxMarkupRate                  money.Decimal      `json:"fx_markup_rate"`
	SettledUsd                    money.Decimal      `json:"settled_usd"`
	TipUsd                        money.Decimal      `json:"tip_usd"`
	HoldReleasedUsd               money.Decimal      `json:"hold_released_usd"`
	CashRepaidUsd                 money.Decimal      `json:"cash_repaid_usd"`
	AutoSellRepaidUsd             money.Decimal      `json:"auto_sell_repaid_usd"`
	RefundedUsd                   money.Decimal      `json:"refunded_usd"`
	Status                        string             `json:"status"`
	ReceivableLedgerTransactionID pgtype.UUID        `json:"receivable_ledger_transaction_id"`
	RepaymentLedgerTransactionID  pgtype.UUID        `json:"repayment_ledger_transaction_id"`
	OccurredAt                    pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
}

type CardCard struct {
	ID                    pgtype.UUID        `json:"id"`
	CustomerReference     string             `json:"customer_reference"`
	CardType              string             `json:"card_type"`
	Status                string             `json:"status"`
	DisplayName           string             `json:"display_name"`
	Last4                 string             `json:"last4"`
	PinSet                bool               `json:"pin_set"`
	Provider              string             `json:"provider"`
	ProviderCardReference string             `json:"provider_card_reference"`
	AppleWalletStatus     string             `json:"apple_wallet_status"`
	GoogleWalletStatus    string             `json:"google_wallet_status"`
	ReplacementForCardID  pgtype.UUID        `json:"replacement_for_card_id"`
	PolicyVersion         string             `json:"policy_version"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Version               int64              `json:"version"`
}

type CardCollateralAccount struct {
	CustomerReference                string             `json:"customer_reference"`
	Symbol                           string             `json:"symbol"`
	SourceType                       string             `json:"source_type"`
	CustomerLedgerAccountID          pgtype.UUID        `json:"customer_ledger_account_id"`
	ProviderInventoryLedgerAccountID pgtype.UUID        `json:"provider_inventory_ledger_account_id"`
	Frozen                           bool               `json:"frozen"`
	Transferring                     bool               `json:"transferring"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
}

type CardCollateralAsset struct {
	Symbol            string             `json:"symbol"`
	DisplayName       string             `json:"display_name"`
	AssetClass        string             `json:"asset_class"`
	HaircutRate       money.Decimal      `json:"haircut_rate"`
	ReferencePriceUsd money.Decimal      `json:"reference_price_usd"`
	QuoteStatus       string             `json:"quote_status"`
	MarketStatus      string             `json:"market_status"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
	Enabled           bool               `json:"enabled"`
	PolicyVersion     string             `json:"policy_version"`
}

type CardCommandRequest struct {
	CustomerReference string             `json:"customer_reference"`
	Scope             string             `json:"scope"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       string             `json:"request_hash"`
	ResourceID        pgtype.UUID        `json:"resource_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CardCustomerProfile struct {
	CustomerReference               string             `json:"customer_reference"`
	PaperAccountID                  pgtype.UUID        `json:"paper_account_id"`
	CashLedgerAccountID             pgtype.UUID        `json:"cash_ledger_account_id"`
	ReceivableLedgerAccountID       pgtype.UUID        `json:"receivable_ledger_account_id"`
	ProviderClearingLedgerAccountID pgtype.UUID        `json:"provider_clearing_ledger_account_id"`
	RepaymentMode                   string             `json:"repayment_mode"`
	SpendingStatus                  string             `json:"spending_status"`
	SpendingStatusReason            pgtype.Text        `json:"spending_status_reason"`
	TrustTier                       string             `json:"trust_tier"`
	KycStatus                       string             `json:"kyc_status"`
	PolicyVersion                   string             `json:"policy_version"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	Version                         int64              `json:"version"`
}

type CardDispute struct {
	ID                            pgtype.UUID        `json:"id"`
	CaptureID                     pgtype.UUID        `json:"capture_id"`
	CustomerReference             string             `json:"customer_reference"`
	AmountUsd                     money.Decimal      `json:"amount_usd"`
	ReasonCode                    string             `json:"reason_code"`
	Status                        string             `json:"status"`
	Outcome                       pgtype.Text        `json:"outcome"`
	ComplianceCaseID              pgtype.UUID        `json:"compliance_case_id"`
	ResolutionLedgerTransactionID pgtype.UUID        `json:"resolution_ledger_transaction_id"`
	OpenedAt                      pgtype.Timestamptz `json:"opened_at"`
	ResolvedAt                    pgtype.Timestamptz `json:"resolved_at"`
	Version                       int64              `json:"version"`
}

type CardLifecycleEvent struct {
	ID         pgtype.UUID        `json:"id"`
	CardID     pgtype.UUID        `json:"card_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Action     string             `json:"action"`
	ActorType  string             `json:"actor_type"`
	ActorID    string             `json:"actor_id"`
	ReasonCode pgtype.Text        `json:"reason_code"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type CardPolicy struct {
	PolicyVersion               string             `json:"policy_version"`
	AuthFxMarkupRate            money.Decimal      `json:"auth_fx_markup_rate"`
	MaximumTipRate              money.Decimal      `json:"maximum_tip_rate"`
	ProtectedLimitGuardrailRate money.Decimal      `json:"protected_limit_guardrail_rate"`
	AbsoluteSpendingCapUsd      money.Decimal      `json:"absolute_spending_cap_usd"`
	ProviderSpendingCapUsd      money.Decimal      `json:"provider_spending_cap_usd"`
	DefaultDailyAutoSellUsd     money.Decimal      `json:"default_daily_auto_sell_usd"`
	QuoteMaxAgeSeconds          int32              `json:"quote_max_age_seconds"`
	StatementCycleDays          int32              `json:"statement_cycle_days"`
	EffectiveAt                 pgtype.Timestamptz `json:"effective_at"`
	Active                      bool               `json:"active"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

type CardProviderEvent struct {
	Provider        string             `json:"provider"`
	ExternalEventID string             `json:"external_event_id"`
	EventType       string             `json:"event_type"`
	PayloadHash     string             `json:"payload_hash"`
	ResourceType    string             `json:"resource_type"`
	ResourceID      pgtype.UUID        `json:"resource_id"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
}

type CardReconciliationRun struct {
	ID                    pgtype.UUID        `json:"id"`
	CustomerReference     string             `json:"customer_reference"`
	LedgerHoldUsd         money.Decimal      `json:"ledger_hold_usd"`
	ProviderHoldUsd       money.Decimal      `json:"provider_hold_usd"`
	LedgerReceivableUsd   money.Decimal      `json:"ledger_receivable_usd"`
	ProviderReceivableUsd money.Decimal      `json:"provider_receivable_usd"`
	DifferenceUsd         money.Decimal      `json:"difference_usd"`
	Status                string             `json:"status"`
	ComplianceCaseID      pgtype.UUID        `json:"compliance_case_id"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
}

type CardRefund struct {
	ID                     pgtype.UUID        `json:"id"`
	CaptureID              pgtype.UUID        `json:"capture_id"`
	Provider               string             `json:"provider"`
	ExternalRefundID       string             `json:"external_refund_id"`
	RefundUsd              money.Decimal      `json:"refund_usd"`
	ReceivableReductionUsd money.Decimal      `json:"receivable_reduction_usd"`
	CashCreditUsd          money.Decimal      `json:"cash_credit_usd"`
	LedgerTransactionID    pgtype.UUID        `json:"ledger_transaction_id"`
	OccurredAt             pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type CardReversal struct {
	ID                  pgtype.UUID        `json:"id"`
	AuthorizationID     pgtype.UUID        `json:"authorization_id"`
	Provider            string             `json:"provider"`
	ExternalReversalID  string             `json:"external_reversal_id"`
	ReversedUsd         money.Decimal      `json:"reversed_usd"`
	LedgerTransactionID pgtype.UUID        `json:"ledger_transaction_id"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type CardStatement struct {
	ID                           pgtype.UUID        `json:"id"`
	CustomerReference            string             `json:"customer_reference"`
	PeriodStart                  pgtype.Date        `json:"period_start"`
	PeriodEnd                    pgtype.Date        `json:"period_end"`
	AmountDueUsd                 money.Decimal      `json:"amount_due_usd"`
	Status                       string             `json:"status"`
	DueAt                        pgtype.Timestamptz `json:"due_at"`
	PaidAt                       pgtype.Timestamptz `json:"paid_at"`
	RepaymentLedgerTransactionID pgtype.UUID        `json:"repayment_ledger_transaction_id"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
}
