// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BindCommandRequestResource(ctx context.Context, arg BindCommandRequestResourceParams) error
	CreateAuthorization(ctx context.Context, arg CreateAuthorizationParams) (CardAuthorization, error)
	CreateCapture(ctx context.Context, arg CreateCaptureParams) (CardCapture, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (CardCard, error)
	CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CardCustomerProfile, error)
	CreateDispute(ctx context.Context, arg CreateDisputeParams) (CardDispute, error)
	CreateRefund(ctx context.Context, arg CreateRefundParams) (CardRefund, error)
	CreateReversal(ctx context.Context, arg CreateReversalParams) (CardReversal, error)
	CreateStatement(ctx context.Context, arg CreateStatementParams) (CardStatement, error)
	DeleteAutoSellMandateAssets(ctx context.Context, mandateID pgtype.UUID) error
	FreezeSpending(ctx context.Context, arg FreezeSpendingParams) (CardCustomerProfile, error)
	GetActivePolicy(ctx context.Context) (CardPolicy, error)
	GetAuthorization(ctx context.Context, id pgtype.UUID) (CardAuthorization, error)
	GetAuthorizationForUpdate(ctx context.Context, id pgtype.UUID) (CardAuthorization, error)
	GetAutoSellMandate(ctx context.Context, customerReference string) (CardAutoSellMandate, error)
	GetAutoSellMandateForUpdate(ctx context.Context, customerReference string) (CardAutoSellMandate, error)
	GetCapture(ctx context.Context, id pgtype.UUID) (CardCapture, error)
	GetCaptureForUpdate(ctx context.Context, id pgtype.UUID) (CardCapture, error)
	GetCard(ctx context.Context, id pgtype.UUID) (CardCard, error)
	GetCardForUpdate(ctx context.Context, id pgtype.UUID) (CardCard, error)
	GetCollateralAccount(ctx context.Context, arg GetCollateralAccountParams) (CardCollateralAccount, error)
	GetCollateralAsset(ctx context.Context, symbol string) (CardCollateralAsset, error)
	GetCommandRequest(ctx context.Context, arg GetCommandRequestParams) (CardCommandRequest, error)
	GetCustomerAuthorization(ctx context.Context, arg GetCustomerAuthorizationParams) (CardAuthorization, error)
	GetCustomerCard(ctx context.Context, arg GetCustomerCardParams) (CardCard, error)
	GetCustomerCardForUpdate(ctx context.Context, arg GetCustomerCardForUpdateParams) (CardCard, error)
	GetCustomerProfile(ctx context.Context, customerReference string) (CardCustomerProfile, error)
	GetCustomerProfileForUpdate(ctx context.Context, customerReference string) (CardCustomerProfile, error)
	GetDispute(ctx context.Context, id pgtype.UUID) (CardDispute, error)
	GetDisputeForUpdate(ctx context.Context, id pgtype.UUID) (CardDispute, error)
	GetPolicy(ctx context.Context, policyVersion string) (CardPolicy, error)
	GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (CardProviderEvent, error)
	GetRefund(ctx context.Context, id pgtype.UUID) (CardRefund, error)
	GetStatement(ctx context.Context, id pgtype.UUID) (CardStatement, error)
	GetStatementByPeriod(ctx context.Context, arg GetStatementByPeriodParams) (CardStatement, error)
	GetStatementForUpdate(ctx context.Context, id pgtype.UUID) (CardStatement, error)
	InsertAutoSellExecution(ctx context.Context, arg InsertAutoSellExecutionParams) (CardAutoSellExecution, error)
	InsertAutoSellMandateAsset(ctx context.Context, arg InsertAutoSellMandateAssetParams) (CardAutoSellMandateAsset, error)
	InsertCollateralAccount(ctx context.Context, arg InsertCollateralAccountParams) (CardCollateralAccount, error)
	InsertCommandRequest(ctx context.Context, arg InsertCommandRequestParams) (pgtype.UUID, error)
	InsertLifecycleEvent(ctx context.Context, arg InsertLifecycleEventParams) (CardLifecycleEvent, error)
	InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (pgtype.UUID, error)
	InsertReconciliationRun(ctx context.Context, arg InsertReconciliationRunParams) (CardReconciliationRun, error)
	ListAuthorizations(ctx context.Context, arg ListAuthorizationsParams) ([]CardAuthorization, error)
	ListAutoSellExecutions(ctx context.Context, captureID pgtype.UUID) ([]CardAutoSellExecution, error)
	ListAutoSellMandateAssets(ctx context.Context, mandateID pgtype.UUID) ([]CardAutoSellMandateAsset, error)
	ListCapturesForAuthorization(ctx context.Context, authorizationID pgtype.UUID) ([]CardCapture, error)
	ListCards(ctx context.Context, customerReference string) ([]CardCard, error)
	ListCollateralAccounts(ctx context.Context, customerReference string) ([]ListCollateralAccountsRow, error)
	ListCollateralAssets(ctx context.Context) ([]CardCollateralAsset, error)
	ListCustomerCaptures(ctx context.Context, arg ListCustomerCapturesParams) ([]CardCapture, error)
	ListDisputes(ctx context.Context, arg ListDisputesParams) ([]CardDispute, error)
	ListLifecycleEvents(ctx context.Context, cardID pgtype.UUID) ([]CardLifecycleEvent, error)
	ListReconciliationRuns(ctx context.Context, arg ListReconciliationRunsParams) ([]CardReconciliationRun, error)
	ListRefundsForCapture(ctx context.Context, captureID pgtype.UUID) ([]CardRefund, error)
	ListStatements(ctx context.Context, customerReference string) ([]CardStatement, error)
	MarkCaptureDisputed(ctx context.Context, id pgtype.UUID) (CardCapture, error)
	MarkStatementPaid(ctx context.Context, arg MarkStatementPaidParams) (CardStatement, error)
	ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (CardDispute, error)
	SumAcceptedDisputeAmountForCapture(ctx context.Context, captureID pgtype.UUID) (money.Decimal, error)
	SumDailyAutoSell(ctx context.Context, arg SumDailyAutoSellParams) (money.Decimal, error)
	SumDisputedAmountForCapture(ctx context.Context, captureID pgtype.UUID) (money.Decimal, error)
	UnfreezeSpending(ctx context.Context, customerReference string) (CardCustomerProfile, error)
	UpdateAuthorizationTotals(ctx context.Context, arg UpdateAuthorizationTotalsParams) (CardAuthorization, error)
	UpdateCaptureRefund(ctx context.Context, arg UpdateCaptureRefundParams) (CardCapture, error)
	UpdateCardState(ctx context.Context, arg UpdateCardStateParams) (CardCard, error)
	UpdateCollateralQuote(ctx context.Context, arg UpdateCollateralQuoteParams) (CardCollateralAsset, error)
	UpdateRepaymentMode(ctx context.Context, arg UpdateRepaymentModeParams) (CardCustomerProfile, error)
	UpsertAutoSellMandate(ctx context.Context, arg UpsertAutoSellMandateParams) (CardAutoSellMandate, error)
}

var _ Querier = (*Queries)(nil)
