// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marketdata.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInstrumentFixtures = `-- name: CountInstrumentFixtures :one
SELECT COUNT(*)
FROM marketdata.instruments
WHERE fixture
`

func (q *Queries) CountInstrumentFixtures(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInstrumentFixtures)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInstrumentBySymbol = `-- name: GetInstrumentBySymbol :one
SELECT
    instrument.id,
    instrument.symbol,
    instrument.display_name,
    instrument.asset_type,
    instrument.primary_exchange,
    instrument.currency,
    instrument.listed,
    capability.searchable,
    capability.quote_enabled,
    capability.paper_tradable,
    capability.live_tradable,
    capability.fractional_enabled,
    capability.transfer_out_enabled,
    capability.rwa_mint_enabled,
    capability.user_eligible,
    capability.disabled_reason,
    capability.policy_version
FROM marketdata.instruments AS instrument
JOIN marketdata.instrument_capabilities AS capability
    ON capability.instrument_id = instrument.id
WHERE instrument.symbol = $1
`

type GetInstrumentBySymbolRow struct {
	ID                 pgtype.UUID `json:"id"`
	Symbol             string      `json:"symbol"`
	DisplayName        string      `json:"display_name"`
	AssetType          string      `json:"asset_type"`
	PrimaryExchange    string      `json:"primary_exchange"`
	Currency           string      `json:"currency"`
	Listed             bool        `json:"listed"`
	Searchable         bool        `json:"searchable"`
	QuoteEnabled       bool        `json:"quote_enabled"`
	PaperTradable      bool        `json:"paper_tradable"`
	LiveTradable       bool        `json:"live_tradable"`
	FractionalEnabled  bool        `json:"fractional_enabled"`
	TransferOutEnabled bool        `json:"transfer_out_enabled"`
	RwaMintEnabled     bool        `json:"rwa_mint_enabled"`
	UserEligible       bool        `json:"user_eligible"`
	DisabledReason     pgtype.Text `json:"disabled_reason"`
	PolicyVersion      string      `json:"policy_version"`
}

func (q *Queries) GetInstrumentBySymbol(ctx context.Context, symbol string) (GetInstrumentBySymbolRow, error) {
	row := q.db.QueryRow(ctx, getInstrumentBySymbol, symbol)
	var i GetInstrumentBySymbolRow
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.DisplayName,
		&i.AssetType,
		&i.PrimaryExchange,
		&i.Currency,
		&i.Listed,
		&i.Searchable,
		&i.QuoteEnabled,
		&i.PaperTradable,
		&i.LiveTradable,
		&i.FractionalEnabled,
		&i.TransferOutEnabled,
		&i.RwaMintEnabled,
		&i.UserEligible,
		&i.DisabledReason,
		&i.PolicyVersion,
	)
	return i, err
}

const getQuoteFixture = `-- name: GetQuoteFixture :one
SELECT
    instrument.id AS instrument_id,
    instrument.symbol,
    fixture.replay_cursor,
    fixture.bid,
    fixture.ask,
    fixture.last,
    fixture.status,
    fixture.market_status,
    fixture.observed_at,
    fixture.provider
FROM marketdata.quote_fixtures AS fixture
JOIN marketdata.instruments AS instrument
    ON instrument.id = fixture.instrument_id
JOIN marketdata.instrument_capabilities AS capability
    ON capability.instrument_id = instrument.id
WHERE instrument.symbol = $1
  AND fixture.replay_cursor = $2
  AND capability.quote_enabled
`

type GetQuoteFixtureParams struct {
	Symbol       string `json:"symbol"`
	ReplayCursor int32  `json:"replay_cursor"`
}

type GetQuoteFixtureRow struct {
	InstrumentID pgtype.UUID        `json:"instrument_id"`
	Symbol       string             `json:"symbol"`
	ReplayCursor int32              `json:"replay_cursor"`
	Bid          pgtype.Numeric     `json:"bid"`
	Ask          pgtype.Numeric     `json:"ask"`
	Last         pgtype.Numeric     `json:"last"`
	Status       string             `json:"status"`
	MarketStatus string             `json:"market_status"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	Provider     string             `json:"provider"`
}

func (q *Queries) GetQuoteFixture(ctx context.Context, arg GetQuoteFixtureParams) (GetQuoteFixtureRow, error) {
	row := q.db.QueryRow(ctx, getQuoteFixture, arg.Symbol, arg.ReplayCursor)
	var i GetQuoteFixtureRow
	err := row.Scan(
		&i.InstrumentID,
		&i.Symbol,
		&i.ReplayCursor,
		&i.Bid,
		&i.Ask,
		&i.Last,
		&i.Status,
		&i.MarketStatus,
		&i.ObservedAt,
		&i.Provider,
	)
	return i, err
}

const searchInstruments = `-- name: SearchInstruments :many
SELECT
    instrument.id,
    instrument.symbol,
    instrument.display_name,
    instrument.asset_type,
    instrument.primary_exchange,
    instrument.currency,
    instrument.listed,
    capability.searchable,
    capability.quote_enabled,
    capability.paper_tradable,
    capability.live_tradable,
    capability.fractional_enabled,
    capability.transfer_out_enabled,
    capability.rwa_mint_enabled,
    capability.user_eligible,
    capability.disabled_reason,
    capability.policy_version
FROM marketdata.instruments AS instrument
JOIN marketdata.instrument_capabilities AS capability
    ON capability.instrument_id = instrument.id
WHERE capability.searchable
  AND (
      instrument.symbol ILIKE $1::text ESCAPE '\'
      OR instrument.display_name ILIKE $1::text ESCAPE '\'
  )
ORDER BY
    CASE WHEN instrument.symbol = $2 THEN 0 ELSE 1 END,
    instrument.symbol
LIMIT $3
`

type SearchInstrumentsParams struct {
	QueryPattern string `json:"query_pattern"`
	ExactSymbol  string `json:"exact_symbol"`
	PageSize     int32  `json:"page_size"`
}

type SearchInstrumentsRow struct {
	ID                 pgtype.UUID `json:"id"`
	Symbol             string      `json:"symbol"`
	DisplayName        string      `json:"display_name"`
	AssetType          string      `json:"asset_type"`
	PrimaryExchange    string      `json:"primary_exchange"`
	Currency           string      `json:"currency"`
	Listed             bool        `json:"listed"`
	Searchable         bool        `json:"searchable"`
	QuoteEnabled       bool        `json:"quote_enabled"`
	PaperTradable      bool        `json:"paper_tradable"`
	LiveTradable       bool        `json:"live_tradable"`
	FractionalEnabled  bool        `json:"fractional_enabled"`
	TransferOutEnabled bool        `json:"transfer_out_enabled"`
	RwaMintEnabled     bool        `json:"rwa_mint_enabled"`
	UserEligible       bool        `json:"user_eligible"`
	DisabledReason     pgtype.Text `json:"disabled_reason"`
	PolicyVersion      string      `json:"policy_version"`
}

func (q *Queries) SearchInstruments(ctx context.Context, arg SearchInstrumentsParams) ([]SearchInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, searchInstruments, arg.QueryPattern, arg.ExactSymbol, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchInstrumentsRow
	for rows.Next() {
		var i SearchInstrumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.DisplayName,
			&i.AssetType,
			&i.PrimaryExchange,
			&i.Currency,
			&i.Listed,
			&i.Searchable,
			&i.QuoteEnabled,
			&i.PaperTradable,
			&i.LiveTradable,
			&i.FractionalEnabled,
			&i.TransferOutEnabled,
			&i.RwaMintEnabled,
			&i.UserEligible,
			&i.DisabledReason,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
