// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountInstrumentFixtures(ctx context.Context) (int64, error)
	GetInstrumentBySymbol(ctx context.Context, symbol string) (GetInstrumentBySymbolRow, error)
	GetQuoteFixture(ctx context.Context, arg GetQuoteFixtureParams) (GetQuoteFixtureRow, error)
	SearchInstruments(ctx context.Context, arg SearchInstrumentsParams) ([]SearchInstrumentsRow, error)
}

var _ Querier = (*Queries)(nil)
