// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO ledger.accounts (
    account_key,
    owner_type,
    owner_id,
    account_type,
    currency,
    normal_side
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (account_key) DO NOTHING
RETURNING id, account_key, owner_type, owner_id, account_type, currency, normal_side, created_at, version
`

type CreateLedgerAccountParams struct {
	AccountKey  string `json:"account_key"`
	OwnerType   string `json:"owner_type"`
	OwnerID     string `json:"owner_id"`
	AccountType string `json:"account_type"`
	Currency    string `json:"currency"`
	NormalSide  string `json:"normal_side"`
}

func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.AccountKey,
		arg.OwnerType,
		arg.OwnerID,
		arg.AccountType,
		arg.Currency,
		arg.NormalSide,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.AccountKey,
		&i.OwnerType,
		&i.OwnerID,
		&i.AccountType,
		&i.Currency,
		&i.NormalSide,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT account_id, currency, balance_dimension, debit_balance, last_entry_at
FROM ledger.account_balances
WHERE account_id = $1
  AND currency = $2
  AND balance_dimension = $3
`

type GetAccountBalanceParams struct {
	AccountID        pgtype.UUID `json:"account_id"`
	Currency         string      `json:"currency"`
	BalanceDimension string      `json:"balance_dimension"`
}

func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (LedgerAccountBalance, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, arg.AccountID, arg.Currency, arg.BalanceDimension)
	var i LedgerAccountBalance
	err := row.Scan(
		&i.AccountID,
		&i.Currency,
		&i.BalanceDimension,
		&i.DebitBalance,
		&i.LastEntryAt,
	)
	return i, err
}

const getLedgerAccount = `-- name: GetLedgerAccount :one
SELECT id, account_key, owner_type, owner_id, account_type, currency, normal_side, created_at, version
FROM ledger.accounts
WHERE id = $1
`

func (q *Queries) GetLedgerAccount(ctx context.Context, id pgtype.UUID) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccount, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.AccountKey,
		&i.OwnerType,
		&i.OwnerID,
		&i.AccountType,
		&i.Currency,
		&i.NormalSide,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getLedgerAccountByKey = `-- name: GetLedgerAccountByKey :one
SELECT id, account_key, owner_type, owner_id, account_type, currency, normal_side, created_at, version
FROM ledger.accounts
WHERE account_key = $1
`

func (q *Queries) GetLedgerAccountByKey(ctx context.Context, accountKey string) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByKey, accountKey)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.AccountKey,
		&i.OwnerType,
		&i.OwnerID,
		&i.AccountType,
		&i.Currency,
		&i.NormalSide,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getLedgerTransaction = `-- name: GetLedgerTransaction :one
SELECT id, transaction_type, policy_version, effective_at, created_at
FROM ledger.transactions
WHERE id = $1
`

func (q *Queries) GetLedgerTransaction(ctx context.Context, id pgtype.UUID) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, getLedgerTransaction, id)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionType,
		&i.PolicyVersion,
		&i.EffectiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderEvent = `-- name: GetProviderEvent :one
SELECT provider, external_event_id, payload_hash, transaction_id, processed_at
FROM ledger.provider_events
WHERE provider = $1
  AND external_event_id = $2
`

type GetProviderEventParams struct {
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (LedgerProviderEvent, error) {
	row := q.db.QueryRow(ctx, getProviderEvent, arg.Provider, arg.ExternalEventID)
	var i LedgerProviderEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.PayloadHash,
		&i.TransactionID,
		&i.ProcessedAt,
	)
	return i, err
}

const getRequestIdempotency = `-- name: GetRequestIdempotency :one
SELECT scope, idempotency_key, request_hash, transaction_id, created_at
FROM ledger.request_idempotency
WHERE scope = $1
  AND idempotency_key = $2
`

type GetRequestIdempotencyParams struct {
	Scope          string `json:"scope"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetRequestIdempotency(ctx context.Context, arg GetRequestIdempotencyParams) (LedgerRequestIdempotency, error) {
	row := q.db.QueryRow(ctx, getRequestIdempotency, arg.Scope, arg.IdempotencyKey)
	var i LedgerRequestIdempotency
	err := row.Scan(
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.TransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const getReversal = `-- name: GetReversal :one
SELECT original_transaction_id, reversal_transaction_id, reason_code, created_at
FROM ledger.reversals
WHERE original_transaction_id = $1
`

func (q *Queries) GetReversal(ctx context.Context, originalTransactionID pgtype.UUID) (LedgerReversal, error) {
	row := q.db.QueryRow(ctx, getReversal, originalTransactionID)
	var i LedgerReversal
	err := row.Scan(
		&i.OriginalTransactionID,
		&i.ReversalTransactionID,
		&i.ReasonCode,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger.entries (
    transaction_id,
    entry_sequence,
    account_id,
    currency,
    balance_dimension,
    direction,
    amount
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, transaction_id, entry_sequence, account_id, currency, balance_dimension, direction, amount, created_at
`

type InsertLedgerEntryParams struct {
	TransactionID    pgtype.UUID   `json:"transaction_id"`
	EntrySequence    int16         `json:"entry_sequence"`
	AccountID        pgtype.UUID   `json:"account_id"`
	Currency         string        `json:"currency"`
	BalanceDimension string        `json:"balance_dimension"`
	Direction        string        `json:"direction"`
	Amount           money.Decimal `json:"amount"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.TransactionID,
		arg.EntrySequence,
		arg.AccountID,
		arg.Currency,
		arg.BalanceDimension,
		arg.Direction,
		arg.Amount,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.EntrySequence,
		&i.AccountID,
		&i.Currency,
		&i.BalanceDimension,
		&i.Direction,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerTransaction = `-- name: InsertLedgerTransaction :one
INSERT INTO ledger.transactions (
    id,
    transaction_type,
    policy_version,
    effective_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, transaction_type, policy_version, effective_at, created_at
`

type InsertLedgerTransactionParams struct {
	ID              pgtype.UUID        `json:"id"`
	TransactionType string             `json:"transaction_type"`
	PolicyVersion   string             `json:"policy_version"`
	EffectiveAt     pgtype.Timestamptz `json:"effective_at"`
}

func (q *Queries) InsertLedgerTransaction(ctx context.Context, arg InsertLedgerTransactionParams) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, insertLedgerTransaction,
		arg.ID,
		arg.TransactionType,
		arg.PolicyVersion,
		arg.EffectiveAt,
	)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionType,
		&i.PolicyVersion,
		&i.EffectiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderEvent = `-- name: InsertProviderEvent :one
INSERT INTO ledger.provider_events (
    provider,
    external_event_id,
    payload_hash,
    transaction_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (provider, external_event_id) DO NOTHING
RETURNING transaction_id
`

type InsertProviderEventParams struct {
	Provider        string      `json:"provider"`
	ExternalEventID string      `json:"external_event_id"`
	PayloadHash     string      `json:"payload_hash"`
	TransactionID   pgtype.UUID `json:"transaction_id"`
}

func (q *Queries) InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertProviderEvent,
		arg.Provider,
		arg.ExternalEventID,
		arg.PayloadHash,
		arg.TransactionID,
	)
	var transaction_id pgtype.UUID
	err := row.Scan(&transaction_id)
	return transaction_id, err
}

const insertRequestIdempotency = `-- name: InsertRequestIdempotency :one
INSERT INTO ledger.request_idempotency (
    scope,
    idempotency_key,
    request_hash,
    transaction_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (scope, idempotency_key) DO NOTHING
RETURNING transaction_id
`

type InsertRequestIdempotencyParams struct {
	Scope          string      `json:"scope"`
	IdempotencyKey string      `json:"idempotency_key"`
	RequestHash    string      `json:"request_hash"`
	TransactionID  pgtype.UUID `json:"transaction_id"`
}

func (q *Queries) InsertRequestIdempotency(ctx context.Context, arg InsertRequestIdempotencyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRequestIdempotency,
		arg.Scope,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.TransactionID,
	)
	var transaction_id pgtype.UUID
	err := row.Scan(&transaction_id)
	return transaction_id, err
}

const insertReversal = `-- name: InsertReversal :one
INSERT INTO ledger.reversals (
    original_transaction_id,
    reversal_transaction_id,
    reason_code
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (original_transaction_id) DO NOTHING
RETURNING reversal_transaction_id
`

type InsertReversalParams struct {
	OriginalTransactionID pgtype.UUID `json:"original_transaction_id"`
	ReversalTransactionID pgtype.UUID `json:"reversal_transaction_id"`
	ReasonCode            string      `json:"reason_code"`
}

func (q *Queries) InsertReversal(ctx context.Context, arg InsertReversalParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertReversal, arg.OriginalTransactionID, arg.ReversalTransactionID, arg.ReasonCode)
	var reversal_transaction_id pgtype.UUID
	err := row.Scan(&reversal_transaction_id)
	return reversal_transaction_id, err
}

const listLedgerEntriesForTransaction = `-- name: ListLedgerEntriesForTransaction :many
SELECT id, transaction_id, entry_sequence, account_id, currency, balance_dimension, direction, amount, created_at
FROM ledger.entries
WHERE transaction_id = $1
ORDER BY entry_sequence
`

func (q *Queries) ListLedgerEntriesForTransaction(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesForTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.EntrySequence,
			&i.AccountID,
			&i.Currency,
			&i.BalanceDimension,
			&i.Direction,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLedgerEntriesForTransaction = `-- name: LockLedgerEntriesForTransaction :many
SELECT id, transaction_id, entry_sequence, account_id, currency, balance_dimension, direction, amount, created_at
FROM ledger.entries
WHERE transaction_id = $1
ORDER BY entry_sequence
FOR SHARE
`

func (q *Queries) LockLedgerEntriesForTransaction(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, lockLedgerEntriesForTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.EntrySequence,
			&i.AccountID,
			&i.Currency,
			&i.BalanceDimension,
			&i.Direction,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
