// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID            pgtype.UUID        `json:"id"`
	Action        string             `json:"action"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    string             `json:"resource_id"`
	ActorType     string             `json:"actor_type"`
	ActorID       string             `json:"actor_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	Metadata      []byte             `json:"metadata"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type LedgerAccount struct {
	ID          pgtype.UUID        `json:"id"`
	AccountKey  string             `json:"account_key"`
	OwnerType   string             `json:"owner_type"`
	OwnerID     string             `json:"owner_id"`
	AccountType string             `json:"account_type"`
	Currency    string             `json:"currency"`
	NormalSide  string             `json:"normal_side"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Version     int64              `json:"version"`
}

// Read-only projection derived exclusively from immutable ledger entries; never update balances directly.
type LedgerAccountBalance struct {
	AccountID        pgtype.UUID   `json:"account_id"`
	Currency         string        `json:"currency"`
	BalanceDimension string        `json:"balance_dimension"`
	DebitBalance     money.Decimal `json:"debit_balance"`
	LastEntryAt      interface{}   `json:"last_entry_at"`
}

type LedgerEntry struct {
	ID               pgtype.UUID        `json:"id"`
	TransactionID    pgtype.UUID        `json:"transaction_id"`
	EntrySequence    int16              `json:"entry_sequence"`
	AccountID        pgtype.UUID        `json:"account_id"`
	Currency         string             `json:"currency"`
	BalanceDimension string             `json:"balance_dimension"`
	Direction        string             `json:"direction"`
	Amount           money.Decimal      `json:"amount"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type LedgerProviderEvent struct {
	Provider        string             `json:"provider"`
	ExternalEventID string             `json:"external_event_id"`
	PayloadHash     string             `json:"payload_hash"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

type LedgerRequestIdempotency struct {
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	TransactionID  pgtype.UUID        `json:"transaction_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type LedgerReversal struct {
	OriginalTransactionID pgtype.UUID        `json:"original_transaction_id"`
	ReversalTransactionID pgtype.UUID        `json:"reversal_transaction_id"`
	ReasonCode            string             `json:"reason_code"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type LedgerTransaction struct {
	ID              pgtype.UUID        `json:"id"`
	TransactionType string             `json:"transaction_type"`
	PolicyVersion   string             `json:"policy_version"`
	EffectiveAt     pgtype.Timestamptz `json:"effective_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Consumer idempotency receipts. A replay may redeliver an event but cannot repeat a recorded consumer effect.
type OutboxConsumerReceipt struct {
	ConsumerName string             `json:"consumer_name"`
	EventID      pgtype.UUID        `json:"event_id"`
	HandledAt    pgtype.Timestamptz `json:"handled_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	MaxAttempts   int32              `json:"max_attempts"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	ClaimedBy     pgtype.Text        `json:"claimed_by"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	LastError     pgtype.Text        `json:"last_error"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
