// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAuditEventsForCorrelation(ctx context.Context, correlationID pgtype.UUID) (int64, error)
	CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error)
	GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (LedgerAccountBalance, error)
	GetLedgerAccount(ctx context.Context, id pgtype.UUID) (LedgerAccount, error)
	GetLedgerTransaction(ctx context.Context, id pgtype.UUID) (LedgerTransaction, error)
	GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (LedgerProviderEvent, error)
	GetRequestIdempotency(ctx context.Context, arg GetRequestIdempotencyParams) (LedgerRequestIdempotency, error)
	GetReversal(ctx context.Context, originalTransactionID pgtype.UUID) (LedgerReversal, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	InsertLedgerTransaction(ctx context.Context, arg InsertLedgerTransactionParams) (LedgerTransaction, error)
	InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (pgtype.UUID, error)
	InsertRequestIdempotency(ctx context.Context, arg InsertRequestIdempotencyParams) (pgtype.UUID, error)
	InsertReversal(ctx context.Context, arg InsertReversalParams) (pgtype.UUID, error)
	ListLedgerEntriesForTransaction(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntry, error)
	LockLedgerEntriesForTransaction(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntry, error)
}

var _ Querier = (*Queries)(nil)
