// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

// Immutable adapter events. Only the Securities application service may translate these events into Ledger commands.
type SecuritiesBrokerEvent struct {
	Provider        string             `json:"provider"`
	ExternalEventID string             `json:"external_event_id"`
	OrderID         pgtype.UUID        `json:"order_id"`
	PayloadHash     string             `json:"payload_hash"`
	EventType       string             `json:"event_type"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

type SecuritiesFill struct {
	ID              pgtype.UUID        `json:"id"`
	OrderID         pgtype.UUID        `json:"order_id"`
	Provider        string             `json:"provider"`
	ExternalEventID string             `json:"external_event_id"`
	FillSequence    int32              `json:"fill_sequence"`
	Quantity        money.Decimal      `json:"quantity"`
	Price           money.Decimal      `json:"price"`
	Consideration   money.Decimal      `json:"consideration"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SecuritiesInstrumentLedgerAccount struct {
	PaperAccountID                 pgtype.UUID        `json:"paper_account_id"`
	InstrumentID                   pgtype.UUID        `json:"instrument_id"`
	Symbol                         string             `json:"symbol"`
	CustomerLedgerAccountID        pgtype.UUID        `json:"customer_ledger_account_id"`
	BrokerInventoryLedgerAccountID pgtype.UUID        `json:"broker_inventory_ledger_account_id"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
}

type SecuritiesOrder struct {
	ID                   pgtype.UUID        `json:"id"`
	PaperAccountID       pgtype.UUID        `json:"paper_account_id"`
	InstrumentID         pgtype.UUID        `json:"instrument_id"`
	Symbol               string             `json:"symbol"`
	ClientOrderReference string             `json:"client_order_reference"`
	Side                 string             `json:"side"`
	OrderType            string             `json:"order_type"`
	TimeInForce          string             `json:"time_in_force"`
	Quantity             money.Decimal      `json:"quantity"`
	LimitPrice           pgtype.Numeric     `json:"limit_price"`
	Status               string             `json:"status"`
	RejectionCode        pgtype.Text        `json:"rejection_code"`
	FilledQuantity       money.Decimal      `json:"filled_quantity"`
	AverageFillPrice     pgtype.Numeric     `json:"average_fill_price"`
	ReferencePrice       money.Decimal      `json:"reference_price"`
	QuoteStatus          string             `json:"quote_status"`
	QuoteObservedAt      pgtype.Timestamptz `json:"quote_observed_at"`
	ReplayCursor         int32              `json:"replay_cursor"`
	ProviderOrderID      string             `json:"provider_order_id"`
	PolicyVersion        string             `json:"policy_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Version              int64              `json:"version"`
}

type SecuritiesOrderActionRequest struct {
	PaperAccountID pgtype.UUID        `json:"paper_account_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	OrderID        pgtype.UUID        `json:"order_id"`
	Action         string             `json:"action"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SecuritiesOrderRequest struct {
	PaperAccountID pgtype.UUID        `json:"paper_account_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	OrderID        pgtype.UUID        `json:"order_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SecuritiesPaperAccount struct {
	ID                     pgtype.UUID        `json:"id"`
	FixtureID              string             `json:"fixture_id"`
	CustomerReference      string             `json:"customer_reference"`
	SessionTokenHash       string             `json:"session_token_hash"`
	Status                 string             `json:"status"`
	CashLedgerAccountID    pgtype.UUID        `json:"cash_ledger_account_id"`
	FundingLedgerAccountID pgtype.UUID        `json:"funding_ledger_account_id"`
	InitialCash            money.Decimal      `json:"initial_cash"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
}

// Mutable read projection derived from immutable fills and Ledger-backed securities movements.
type SecuritiesPosition struct {
	PaperAccountID pgtype.UUID        `json:"paper_account_id"`
	InstrumentID   pgtype.UUID        `json:"instrument_id"`
	Symbol         string             `json:"symbol"`
	Quantity       money.Decimal      `json:"quantity"`
	AverageCost    money.Decimal      `json:"average_cost"`
	CostBasis      money.Decimal      `json:"cost_basis"`
	RealizedPnl    money.Decimal      `json:"realized_pnl"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Version        int64              `json:"version"`
}

type SecuritiesPositionReservation struct {
	ID                         pgtype.UUID        `json:"id"`
	PaperAccountID             pgtype.UUID        `json:"paper_account_id"`
	InstrumentID               pgtype.UUID        `json:"instrument_id"`
	Symbol                     string             `json:"symbol"`
	ReservationType            string             `json:"reservation_type"`
	Quantity                   money.Decimal      `json:"quantity"`
	Status                     string             `json:"status"`
	CustomerLedgerAccountID    pgtype.UUID        `json:"customer_ledger_account_id"`
	LockedLedgerAccountID      pgtype.UUID        `json:"locked_ledger_account_id"`
	LockLedgerTransactionID    pgtype.UUID        `json:"lock_ledger_transaction_id"`
	ReleaseLedgerTransactionID pgtype.UUID        `json:"release_ledger_transaction_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	ReleasedAt                 pgtype.Timestamptz `json:"released_at"`
	Version                    int64              `json:"version"`
}
