// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdvanceOpenOrder(ctx context.Context, arg AdvanceOpenOrderParams) (SecuritiesOrder, error)
	ApplyOrderFill(ctx context.Context, arg ApplyOrderFillParams) (SecuritiesOrder, error)
	GetBrokerEvent(ctx context.Context, arg GetBrokerEventParams) (SecuritiesBrokerEvent, error)
	GetInstrumentLedgerAccounts(ctx context.Context, arg GetInstrumentLedgerAccountsParams) (SecuritiesInstrumentLedgerAccount, error)
	GetOrder(ctx context.Context, id pgtype.UUID) (SecuritiesOrder, error)
	GetOrderActionRequest(ctx context.Context, arg GetOrderActionRequestParams) (SecuritiesOrderActionRequest, error)
	GetOrderForUpdate(ctx context.Context, arg GetOrderForUpdateParams) (SecuritiesOrder, error)
	GetOrderRequest(ctx context.Context, arg GetOrderRequestParams) (SecuritiesOrderRequest, error)
	GetPaperAccount(ctx context.Context, id pgtype.UUID) (SecuritiesPaperAccount, error)
	GetPaperAccountByFixture(ctx context.Context, fixtureID string) (SecuritiesPaperAccount, error)
	GetPaperAccountBySessionHash(ctx context.Context, sessionTokenHash string) (SecuritiesPaperAccount, error)
	GetPositionForUpdate(ctx context.Context, arg GetPositionForUpdateParams) (SecuritiesPosition, error)
	GetPositionReservation(ctx context.Context, id pgtype.UUID) (SecuritiesPositionReservation, error)
	GetPositionReservationForUpdate(ctx context.Context, id pgtype.UUID) (SecuritiesPositionReservation, error)
	InsertBrokerEvent(ctx context.Context, arg InsertBrokerEventParams) (SecuritiesBrokerEvent, error)
	InsertFill(ctx context.Context, arg InsertFillParams) (SecuritiesFill, error)
	InsertInstrumentLedgerAccounts(ctx context.Context, arg InsertInstrumentLedgerAccountsParams) (SecuritiesInstrumentLedgerAccount, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) (SecuritiesOrder, error)
	InsertOrderActionRequest(ctx context.Context, arg InsertOrderActionRequestParams) (pgtype.UUID, error)
	InsertOrderRequest(ctx context.Context, arg InsertOrderRequestParams) (pgtype.UUID, error)
	InsertPaperAccount(ctx context.Context, arg InsertPaperAccountParams) (SecuritiesPaperAccount, error)
	InsertPositionReservation(ctx context.Context, arg InsertPositionReservationParams) (SecuritiesPositionReservation, error)
	ListFillsForOrder(ctx context.Context, orderID pgtype.UUID) ([]SecuritiesFill, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]SecuritiesOrder, error)
	ListPositions(ctx context.Context, paperAccountID pgtype.UUID) ([]SecuritiesPosition, error)
	LockPaperAccount(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	LockRegistrationFixture(ctx context.Context, fixtureID string) error
	MarkOrderCancelled(ctx context.Context, id pgtype.UUID) (SecuritiesOrder, error)
	MarkOrderExpired(ctx context.Context, arg MarkOrderExpiredParams) (SecuritiesOrder, error)
	MarkOrderOpen(ctx context.Context, id pgtype.UUID) (SecuritiesOrder, error)
	MarkOrderRejected(ctx context.Context, arg MarkOrderRejectedParams) (SecuritiesOrder, error)
	ReleasePositionReservation(ctx context.Context, arg ReleasePositionReservationParams) (SecuritiesPositionReservation, error)
	SumActivePositionReservations(ctx context.Context, arg SumActivePositionReservationsParams) (money.Decimal, error)
	UpsertPosition(ctx context.Context, arg UpsertPositionParams) (SecuritiesPosition, error)
}

var _ Querier = (*Queries)(nil)
