// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: securities.sql

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceOpenOrder = `-- name: AdvanceOpenOrder :one
UPDATE securities.orders
SET replay_cursor = $1
WHERE id = $2
  AND status IN ('OPEN', 'PARTIALLY_FILLED')
RETURNING id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
`

type AdvanceOpenOrderParams struct {
	ReplayCursor int32       `json:"replay_cursor"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) AdvanceOpenOrder(ctx context.Context, arg AdvanceOpenOrderParams) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, advanceOpenOrder, arg.ReplayCursor, arg.ID)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const applyOrderFill = `-- name: ApplyOrderFill :one
UPDATE securities.orders
SET status = $1,
    filled_quantity = $2,
    average_fill_price = $3,
    replay_cursor = $4
WHERE id = $5
  AND status IN ('PENDING_SUBMISSION', 'OPEN', 'PARTIALLY_FILLED')
RETURNING id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
`

type ApplyOrderFillParams struct {
	Status           string         `json:"status"`
	FilledQuantity   money.Decimal  `json:"filled_quantity"`
	AverageFillPrice pgtype.Numeric `json:"average_fill_price"`
	ReplayCursor     int32          `json:"replay_cursor"`
	ID               pgtype.UUID    `json:"id"`
}

func (q *Queries) ApplyOrderFill(ctx context.Context, arg ApplyOrderFillParams) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, applyOrderFill,
		arg.Status,
		arg.FilledQuantity,
		arg.AverageFillPrice,
		arg.ReplayCursor,
		arg.ID,
	)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getBrokerEvent = `-- name: GetBrokerEvent :one
SELECT provider, external_event_id, order_id, payload_hash, event_type, processed_at
FROM securities.broker_events
WHERE provider = $1
  AND external_event_id = $2
`

type GetBrokerEventParams struct {
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetBrokerEvent(ctx context.Context, arg GetBrokerEventParams) (SecuritiesBrokerEvent, error) {
	row := q.db.QueryRow(ctx, getBrokerEvent, arg.Provider, arg.ExternalEventID)
	var i SecuritiesBrokerEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.OrderID,
		&i.PayloadHash,
		&i.EventType,
		&i.ProcessedAt,
	)
	return i, err
}

const getInstrumentLedgerAccounts = `-- name: GetInstrumentLedgerAccounts :one
SELECT paper_account_id, instrument_id, symbol, customer_ledger_account_id, broker_inventory_ledger_account_id, created_at
FROM securities.instrument_ledger_accounts
WHERE paper_account_id = $1
  AND instrument_id = $2
`

type GetInstrumentLedgerAccountsParams struct {
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
	InstrumentID   pgtype.UUID `json:"instrument_id"`
}

func (q *Queries) GetInstrumentLedgerAccounts(ctx context.Context, arg GetInstrumentLedgerAccountsParams) (SecuritiesInstrumentLedgerAccount, error) {
	row := q.db.QueryRow(ctx, getInstrumentLedgerAccounts, arg.PaperAccountID, arg.InstrumentID)
	var i SecuritiesInstrumentLedgerAccount
	err := row.Scan(
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.CustomerLedgerAccountID,
		&i.BrokerInventoryLedgerAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
FROM securities.orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getOrderActionRequest = `-- name: GetOrderActionRequest :one
SELECT paper_account_id, idempotency_key, request_hash, order_id, action, created_at
FROM securities.order_action_requests
WHERE paper_account_id = $1
  AND idempotency_key = $2
`

type GetOrderActionRequestParams struct {
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetOrderActionRequest(ctx context.Context, arg GetOrderActionRequestParams) (SecuritiesOrderActionRequest, error) {
	row := q.db.QueryRow(ctx, getOrderActionRequest, arg.PaperAccountID, arg.IdempotencyKey)
	var i SecuritiesOrderActionRequest
	err := row.Scan(
		&i.PaperAccountID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.OrderID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
FROM securities.orders
WHERE id = $1
  AND paper_account_id = $2
FOR UPDATE
`

type GetOrderForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
}

func (q *Queries) GetOrderForUpdate(ctx context.Context, arg GetOrderForUpdateParams) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, arg.ID, arg.PaperAccountID)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getOrderRequest = `-- name: GetOrderRequest :one
SELECT paper_account_id, idempotency_key, request_hash, order_id, created_at
FROM securities.order_requests
WHERE paper_account_id = $1
  AND idempotency_key = $2
`

type GetOrderRequestParams struct {
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetOrderRequest(ctx context.Context, arg GetOrderRequestParams) (SecuritiesOrderRequest, error) {
	row := q.db.QueryRow(ctx, getOrderRequest, arg.PaperAccountID, arg.IdempotencyKey)
	var i SecuritiesOrderRequest
	err := row.Scan(
		&i.PaperAccountID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getPaperAccount = `-- name: GetPaperAccount :one
SELECT id, fixture_id, customer_reference, session_token_hash, status, cash_ledger_account_id, funding_ledger_account_id, initial_cash, created_at, archived_at
FROM securities.paper_accounts
WHERE id = $1
`

func (q *Queries) GetPaperAccount(ctx context.Context, id pgtype.UUID) (SecuritiesPaperAccount, error) {
	row := q.db.QueryRow(ctx, getPaperAccount, id)
	var i SecuritiesPaperAccount
	err := row.Scan(
		&i.ID,
		&i.FixtureID,
		&i.CustomerReference,
		&i.SessionTokenHash,
		&i.Status,
		&i.CashLedgerAccountID,
		&i.FundingLedgerAccountID,
		&i.InitialCash,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getPaperAccountByFixture = `-- name: GetPaperAccountByFixture :one
SELECT id, fixture_id, customer_reference, session_token_hash, status, cash_ledger_account_id, funding_ledger_account_id, initial_cash, created_at, archived_at
FROM securities.paper_accounts
WHERE fixture_id = $1
`

func (q *Queries) GetPaperAccountByFixture(ctx context.Context, fixtureID string) (SecuritiesPaperAccount, error) {
	row := q.db.QueryRow(ctx, getPaperAccountByFixture, fixtureID)
	var i SecuritiesPaperAccount
	err := row.Scan(
		&i.ID,
		&i.FixtureID,
		&i.CustomerReference,
		&i.SessionTokenHash,
		&i.Status,
		&i.CashLedgerAccountID,
		&i.FundingLedgerAccountID,
		&i.InitialCash,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getPaperAccountBySessionHash = `-- name: GetPaperAccountBySessionHash :one
SELECT id, fixture_id, customer_reference, session_token_hash, status, cash_ledger_account_id, funding_ledger_account_id, initial_cash, created_at, archived_at
FROM securities.paper_accounts
WHERE session_token_hash = $1
  AND status = 'ACTIVE'
`

func (q *Queries) GetPaperAccountBySessionHash(ctx context.Context, sessionTokenHash string) (SecuritiesPaperAccount, error) {
	row := q.db.QueryRow(ctx, getPaperAccountBySessionHash, sessionTokenHash)
	var i SecuritiesPaperAccount
	err := row.Scan(
		&i.ID,
		&i.FixtureID,
		&i.CustomerReference,
		&i.SessionTokenHash,
		&i.Status,
		&i.CashLedgerAccountID,
		&i.FundingLedgerAccountID,
		&i.InitialCash,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getPositionForUpdate = `-- name: GetPositionForUpdate :one
SELECT paper_account_id, instrument_id, symbol, quantity, average_cost, cost_basis, realized_pnl, updated_at, version
FROM securities.positions
WHERE paper_account_id = $1
  AND instrument_id = $2
FOR UPDATE
`

type GetPositionForUpdateParams struct {
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
	InstrumentID   pgtype.UUID `json:"instrument_id"`
}

func (q *Queries) GetPositionForUpdate(ctx context.Context, arg GetPositionForUpdateParams) (SecuritiesPosition, error) {
	row := q.db.QueryRow(ctx, getPositionForUpdate, arg.PaperAccountID, arg.InstrumentID)
	var i SecuritiesPosition
	err := row.Scan(
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.Quantity,
		&i.AverageCost,
		&i.CostBasis,
		&i.RealizedPnl,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPositionReservation = `-- name: GetPositionReservation :one
SELECT id, paper_account_id, instrument_id, symbol, reservation_type, quantity, status, customer_ledger_account_id, locked_ledger_account_id, lock_ledger_transaction_id, release_ledger_transaction_id, created_at, released_at, version FROM securities.position_reservations WHERE id = $1
`

func (q *Queries) GetPositionReservation(ctx context.Context, id pgtype.UUID) (SecuritiesPositionReservation, error) {
	row := q.db.QueryRow(ctx, getPositionReservation, id)
	var i SecuritiesPositionReservation
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ReservationType,
		&i.Quantity,
		&i.Status,
		&i.CustomerLedgerAccountID,
		&i.LockedLedgerAccountID,
		&i.LockLedgerTransactionID,
		&i.ReleaseLedgerTransactionID,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Version,
	)
	return i, err
}

const getPositionReservationForUpdate = `-- name: GetPositionReservationForUpdate :one
SELECT id, paper_account_id, instrument_id, symbol, reservation_type, quantity, status, customer_ledger_account_id, locked_ledger_account_id, lock_ledger_transaction_id, release_ledger_transaction_id, created_at, released_at, version FROM securities.position_reservations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPositionReservationForUpdate(ctx context.Context, id pgtype.UUID) (SecuritiesPositionReservation, error) {
	row := q.db.QueryRow(ctx, getPositionReservationForUpdate, id)
	var i SecuritiesPositionReservation
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ReservationType,
		&i.Quantity,
		&i.Status,
		&i.CustomerLedgerAccountID,
		&i.LockedLedgerAccountID,
		&i.LockLedgerTransactionID,
		&i.ReleaseLedgerTransactionID,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Version,
	)
	return i, err
}

const insertBrokerEvent = `-- name: InsertBrokerEvent :one
INSERT INTO securities.broker_events (
    provider,
    external_event_id,
    order_id,
    payload_hash,
    event_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (provider, external_event_id) DO NOTHING
RETURNING provider, external_event_id, order_id, payload_hash, event_type, processed_at
`

type InsertBrokerEventParams struct {
	Provider        string      `json:"provider"`
	ExternalEventID string      `json:"external_event_id"`
	OrderID         pgtype.UUID `json:"order_id"`
	PayloadHash     string      `json:"payload_hash"`
	EventType       string      `json:"event_type"`
}

func (q *Queries) InsertBrokerEvent(ctx context.Context, arg InsertBrokerEventParams) (SecuritiesBrokerEvent, error) {
	row := q.db.QueryRow(ctx, insertBrokerEvent,
		arg.Provider,
		arg.ExternalEventID,
		arg.OrderID,
		arg.PayloadHash,
		arg.EventType,
	)
	var i SecuritiesBrokerEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.OrderID,
		&i.PayloadHash,
		&i.EventType,
		&i.ProcessedAt,
	)
	return i, err
}

const insertFill = `-- name: InsertFill :one
INSERT INTO securities.fills (
    order_id,
    provider,
    external_event_id,
    fill_sequence,
    quantity,
    price,
    consideration,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, order_id, provider, external_event_id, fill_sequence, quantity, price, consideration, occurred_at, created_at
`

type InsertFillParams struct {
	OrderID         pgtype.UUID        `json:"order_id"`
	Provider        string             `json:"provider"`
	ExternalEventID string             `json:"external_event_id"`
	FillSequence    int32              `json:"fill_sequence"`
	Quantity        money.Decimal      `json:"quantity"`
	Price           money.Decimal      `json:"price"`
	Consideration   money.Decimal      `json:"consideration"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertFill(ctx context.Context, arg InsertFillParams) (SecuritiesFill, error) {
	row := q.db.QueryRow(ctx, insertFill,
		arg.OrderID,
		arg.Provider,
		arg.ExternalEventID,
		arg.FillSequence,
		arg.Quantity,
		arg.Price,
		arg.Consideration,
		arg.OccurredAt,
	)
	var i SecuritiesFill
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ExternalEventID,
		&i.FillSequence,
		&i.Quantity,
		&i.Price,
		&i.Consideration,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertInstrumentLedgerAccounts = `-- name: InsertInstrumentLedgerAccounts :one
INSERT INTO securities.instrument_ledger_accounts (
    paper_account_id,
    instrument_id,
    symbol,
    customer_ledger_account_id,
    broker_inventory_ledger_account_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (paper_account_id, instrument_id) DO NOTHING
RETURNING paper_account_id, instrument_id, symbol, customer_ledger_account_id, broker_inventory_ledger_account_id, created_at
`

type InsertInstrumentLedgerAccountsParams struct {
	PaperAccountID                 pgtype.UUID `json:"paper_account_id"`
	InstrumentID                   pgtype.UUID `json:"instrument_id"`
	Symbol                         string      `json:"symbol"`
	CustomerLedgerAccountID        pgtype.UUID `json:"customer_ledger_account_id"`
	BrokerInventoryLedgerAccountID pgtype.UUID `json:"broker_inventory_ledger_account_id"`
}

func (q *Queries) InsertInstrumentLedgerAccounts(ctx context.Context, arg InsertInstrumentLedgerAccountsParams) (SecuritiesInstrumentLedgerAccount, error) {
	row := q.db.QueryRow(ctx, insertInstrumentLedgerAccounts,
		arg.PaperAccountID,
		arg.InstrumentID,
		arg.Symbol,
		arg.CustomerLedgerAccountID,
		arg.BrokerInventoryLedgerAccountID,
	)
	var i SecuritiesInstrumentLedgerAccount
	err := row.Scan(
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.CustomerLedgerAccountID,
		&i.BrokerInventoryLedgerAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO securities.orders (
    id,
    paper_account_id,
    instrument_id,
    symbol,
    client_order_reference,
    side,
    order_type,
    time_in_force,
    quantity,
    limit_price,
    status,
    reference_price,
    quote_status,
    quote_observed_at,
    replay_cursor,
    provider_order_id,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    'PENDING_SUBMISSION',
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
`

type InsertOrderParams struct {
	ID                   pgtype.UUID        `json:"id"`
	PaperAccountID       pgtype.UUID        `json:"paper_account_id"`
	InstrumentID         pgtype.UUID        `json:"instrument_id"`
	Symbol               string             `json:"symbol"`
	ClientOrderReference string             `json:"client_order_reference"`
	Side                 string             `json:"side"`
	OrderType            string             `json:"order_type"`
	TimeInForce          string             `json:"time_in_force"`
	Quantity             money.Decimal      `json:"quantity"`
	LimitPrice           pgtype.Numeric     `json:"limit_price"`
	ReferencePrice       money.Decimal      `json:"reference_price"`
	QuoteStatus          string             `json:"quote_status"`
	QuoteObservedAt      pgtype.Timestamptz `json:"quote_observed_at"`
	ReplayCursor         int32              `json:"replay_cursor"`
	ProviderOrderID      string             `json:"provider_order_id"`
	PolicyVersion        string             `json:"policy_version"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.PaperAccountID,
		arg.InstrumentID,
		arg.Symbol,
		arg.ClientOrderReference,
		arg.Side,
		arg.OrderType,
		arg.TimeInForce,
		arg.Quantity,
		arg.LimitPrice,
		arg.ReferencePrice,
		arg.QuoteStatus,
		arg.QuoteObservedAt,
		arg.ReplayCursor,
		arg.ProviderOrderID,
		arg.PolicyVersion,
	)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertOrderActionRequest = `-- name: InsertOrderActionRequest :one
INSERT INTO securities.order_action_requests (
    paper_account_id,
    idempotency_key,
    request_hash,
    order_id,
    action
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (paper_account_id, idempotency_key) DO NOTHING
RETURNING order_id
`

type InsertOrderActionRequestParams struct {
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	RequestHash    string      `json:"request_hash"`
	OrderID        pgtype.UUID `json:"order_id"`
	Action         string      `json:"action"`
}

func (q *Queries) InsertOrderActionRequest(ctx context.Context, arg InsertOrderActionRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertOrderActionRequest,
		arg.PaperAccountID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.OrderID,
		arg.Action,
	)
	var order_id pgtype.UUID
	err := row.Scan(&order_id)
	return order_id, err
}

const insertOrderRequest = `-- name: InsertOrderRequest :one
INSERT INTO securities.order_requests (
    paper_account_id,
    idempotency_key,
    request_hash,
    order_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (paper_account_id, idempotency_key) DO NOTHING
RETURNING order_id
`

type InsertOrderRequestParams struct {
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	RequestHash    string      `json:"request_hash"`
	OrderID        pgtype.UUID `json:"order_id"`
}

func (q *Queries) InsertOrderRequest(ctx context.Context, arg InsertOrderRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertOrderRequest,
		arg.PaperAccountID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.OrderID,
	)
	var order_id pgtype.UUID
	err := row.Scan(&order_id)
	return order_id, err
}

const insertPaperAccount = `-- name: InsertPaperAccount :one
INSERT INTO securities.paper_accounts (
    id,
    fixture_id,
    customer_reference,
    session_token_hash,
    cash_ledger_account_id,
    funding_ledger_account_id,
    initial_cash
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, fixture_id, customer_reference, session_token_hash, status, cash_ledger_account_id, funding_ledger_account_id, initial_cash, created_at, archived_at
`

type InsertPaperAccountParams struct {
	ID                     pgtype.UUID   `json:"id"`
	FixtureID              string        `json:"fixture_id"`
	CustomerReference      string        `json:"customer_reference"`
	SessionTokenHash       string        `json:"session_token_hash"`
	CashLedgerAccountID    pgtype.UUID   `json:"cash_ledger_account_id"`
	FundingLedgerAccountID pgtype.UUID   `json:"funding_ledger_account_id"`
	InitialCash            money.Decimal `json:"initial_cash"`
}

func (q *Queries) InsertPaperAccount(ctx context.Context, arg InsertPaperAccountParams) (SecuritiesPaperAccount, error) {
	row := q.db.QueryRow(ctx, insertPaperAccount,
		arg.ID,
		arg.FixtureID,
		arg.CustomerReference,
		arg.SessionTokenHash,
		arg.CashLedgerAccountID,
		arg.FundingLedgerAccountID,
		arg.InitialCash,
	)
	var i SecuritiesPaperAccount
	err := row.Scan(
		&i.ID,
		&i.FixtureID,
		&i.CustomerReference,
		&i.SessionTokenHash,
		&i.Status,
		&i.CashLedgerAccountID,
		&i.FundingLedgerAccountID,
		&i.InitialCash,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertPositionReservation = `-- name: InsertPositionReservation :one
INSERT INTO securities.position_reservations (
    id, paper_account_id, instrument_id, symbol, reservation_type, quantity,
    customer_ledger_account_id, locked_ledger_account_id, lock_ledger_transaction_id
) VALUES (
    $1, $2, $3, $4,
    'RWA_LOCK', $5, $6,
    $7, $8
)
RETURNING id, paper_account_id, instrument_id, symbol, reservation_type, quantity, status, customer_ledger_account_id, locked_ledger_account_id, lock_ledger_transaction_id, release_ledger_transaction_id, created_at, released_at, version
`

type InsertPositionReservationParams struct {
	ID                      pgtype.UUID   `json:"id"`
	PaperAccountID          pgtype.UUID   `json:"paper_account_id"`
	InstrumentID            pgtype.UUID   `json:"instrument_id"`
	Symbol                  string        `json:"symbol"`
	Quantity                money.Decimal `json:"quantity"`
	CustomerLedgerAccountID pgtype.UUID   `json:"customer_ledger_account_id"`
	LockedLedgerAccountID   pgtype.UUID   `json:"locked_ledger_account_id"`
	LockLedgerTransactionID pgtype.UUID   `json:"lock_ledger_transaction_id"`
}

func (q *Queries) InsertPositionReservation(ctx context.Context, arg InsertPositionReservationParams) (SecuritiesPositionReservation, error) {
	row := q.db.QueryRow(ctx, insertPositionReservation,
		arg.ID,
		arg.PaperAccountID,
		arg.InstrumentID,
		arg.Symbol,
		arg.Quantity,
		arg.CustomerLedgerAccountID,
		arg.LockedLedgerAccountID,
		arg.LockLedgerTransactionID,
	)
	var i SecuritiesPositionReservation
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ReservationType,
		&i.Quantity,
		&i.Status,
		&i.CustomerLedgerAccountID,
		&i.LockedLedgerAccountID,
		&i.LockLedgerTransactionID,
		&i.ReleaseLedgerTransactionID,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Version,
	)
	return i, err
}

const listFillsForOrder = `-- name: ListFillsForOrder :many
SELECT id, order_id, provider, external_event_id, fill_sequence, quantity, price, consideration, occurred_at, created_at
FROM securities.fills
WHERE order_id = $1
ORDER BY fill_sequence
`

func (q *Queries) ListFillsForOrder(ctx context.Context, orderID pgtype.UUID) ([]SecuritiesFill, error) {
	rows, err := q.db.Query(ctx, listFillsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecuritiesFill
	for rows.Next() {
		var i SecuritiesFill
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Provider,
			&i.ExternalEventID,
			&i.FillSequence,
			&i.Quantity,
			&i.Price,
			&i.Consideration,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
FROM securities.orders
WHERE paper_account_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListOrdersParams struct {
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
	PageSize       int32       `json:"page_size"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]SecuritiesOrder, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.PaperAccountID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecuritiesOrder
	for rows.Next() {
		var i SecuritiesOrder
		if err := rows.Scan(
			&i.ID,
			&i.PaperAccountID,
			&i.InstrumentID,
			&i.Symbol,
			&i.ClientOrderReference,
			&i.Side,
			&i.OrderType,
			&i.TimeInForce,
			&i.Quantity,
			&i.LimitPrice,
			&i.Status,
			&i.RejectionCode,
			&i.FilledQuantity,
			&i.AverageFillPrice,
			&i.ReferencePrice,
			&i.QuoteStatus,
			&i.QuoteObservedAt,
			&i.ReplayCursor,
			&i.ProviderOrderID,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT paper_account_id, instrument_id, symbol, quantity, average_cost, cost_basis, realized_pnl, updated_at, version
FROM securities.positions
WHERE paper_account_id = $1
  AND quantity > 0
ORDER BY symbol
`

func (q *Queries) ListPositions(ctx context.Context, paperAccountID pgtype.UUID) ([]SecuritiesPosition, error) {
	rows, err := q.db.Query(ctx, listPositions, paperAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecuritiesPosition
	for rows.Next() {
		var i SecuritiesPosition
		if err := rows.Scan(
			&i.PaperAccountID,
			&i.InstrumentID,
			&i.Symbol,
			&i.Quantity,
			&i.AverageCost,
			&i.CostBasis,
			&i.RealizedPnl,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaperAccount = `-- name: LockPaperAccount :one
SELECT id
FROM securities.paper_accounts
WHERE id = $1
  AND status = 'ACTIVE'
FOR UPDATE
`

func (q *Queries) LockPaperAccount(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockPaperAccount, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockRegistrationFixture = `-- name: LockRegistrationFixture :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockRegistrationFixture(ctx context.Context, fixtureID string) error {
	_, err := q.db.Exec(ctx, lockRegistrationFixture, fixtureID)
	return err
}

const markOrderCancelled = `-- name: MarkOrderCancelled :one
UPDATE securities.orders
SET status = 'CANCELLED'
WHERE id = $1
  AND status IN ('OPEN', 'PARTIALLY_FILLED')
RETURNING id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
`

func (q *Queries) MarkOrderCancelled(ctx context.Context, id pgtype.UUID) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, markOrderCancelled, id)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const markOrderExpired = `-- name: MarkOrderExpired :one
UPDATE securities.orders
SET status = 'EXPIRED',
    replay_cursor = $1
WHERE id = $2
  AND status IN ('OPEN', 'PARTIALLY_FILLED')
RETURNING id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
`

type MarkOrderExpiredParams struct {
	ReplayCursor int32       `json:"replay_cursor"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) MarkOrderExpired(ctx context.Context, arg MarkOrderExpiredParams) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, markOrderExpired, arg.ReplayCursor, arg.ID)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const markOrderOpen = `-- name: MarkOrderOpen :one
UPDATE securities.orders
SET status = 'OPEN'
WHERE id = $1
  AND status = 'PENDING_SUBMISSION'
RETURNING id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
`

func (q *Queries) MarkOrderOpen(ctx context.Context, id pgtype.UUID) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, markOrderOpen, id)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const markOrderRejected = `-- name: MarkOrderRejected :one
UPDATE securities.orders
SET status = 'REJECTED',
    rejection_code = $1,
    replay_cursor = $2
WHERE id = $3
  AND status IN ('PENDING_SUBMISSION', 'OPEN')
RETURNING id, paper_account_id, instrument_id, symbol, client_order_reference, side, order_type, time_in_force, quantity, limit_price, status, rejection_code, filled_quantity, average_fill_price, reference_price, quote_status, quote_observed_at, replay_cursor, provider_order_id, policy_version, created_at, updated_at, version
`

type MarkOrderRejectedParams struct {
	RejectionCode pgtype.Text `json:"rejection_code"`
	ReplayCursor  int32       `json:"replay_cursor"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) MarkOrderRejected(ctx context.Context, arg MarkOrderRejectedParams) (SecuritiesOrder, error) {
	row := q.db.QueryRow(ctx, markOrderRejected, arg.RejectionCode, arg.ReplayCursor, arg.ID)
	var i SecuritiesOrder
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ClientOrderReference,
		&i.Side,
		&i.OrderType,
		&i.TimeInForce,
		&i.Quantity,
		&i.LimitPrice,
		&i.Status,
		&i.RejectionCode,
		&i.FilledQuantity,
		&i.AverageFillPrice,
		&i.ReferencePrice,
		&i.QuoteStatus,
		&i.QuoteObservedAt,
		&i.ReplayCursor,
		&i.ProviderOrderID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const releasePositionReservation = `-- name: ReleasePositionReservation :one
UPDATE securities.position_reservations
SET status = 'RELEASED',
    release_ledger_transaction_id = $1,
    released_at = clock_timestamp(),
    version = version + 1
WHERE id = $2 AND status = 'ACTIVE'
RETURNING id, paper_account_id, instrument_id, symbol, reservation_type, quantity, status, customer_ledger_account_id, locked_ledger_account_id, lock_ledger_transaction_id, release_ledger_transaction_id, created_at, released_at, version
`

type ReleasePositionReservationParams struct {
	ReleaseLedgerTransactionID pgtype.UUID `json:"release_ledger_transaction_id"`
	ID                         pgtype.UUID `json:"id"`
}

func (q *Queries) ReleasePositionReservation(ctx context.Context, arg ReleasePositionReservationParams) (SecuritiesPositionReservation, error) {
	row := q.db.QueryRow(ctx, releasePositionReservation, arg.ReleaseLedgerTransactionID, arg.ID)
	var i SecuritiesPositionReservation
	err := row.Scan(
		&i.ID,
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.ReservationType,
		&i.Quantity,
		&i.Status,
		&i.CustomerLedgerAccountID,
		&i.LockedLedgerAccountID,
		&i.LockLedgerTransactionID,
		&i.ReleaseLedgerTransactionID,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Version,
	)
	return i, err
}

const sumActivePositionReservations = `-- name: SumActivePositionReservations :one
SELECT COALESCE(sum(quantity), 0)::numeric AS quantity
FROM securities.position_reservations
WHERE paper_account_id = $1
  AND instrument_id = $2
  AND status = 'ACTIVE'
`

type SumActivePositionReservationsParams struct {
	PaperAccountID pgtype.UUID `json:"paper_account_id"`
	InstrumentID   pgtype.UUID `json:"instrument_id"`
}

func (q *Queries) SumActivePositionReservations(ctx context.Context, arg SumActivePositionReservationsParams) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumActivePositionReservations, arg.PaperAccountID, arg.InstrumentID)
	var quantity money.Decimal
	err := row.Scan(&quantity)
	return quantity, err
}

const upsertPosition = `-- name: UpsertPosition :one
INSERT INTO securities.positions (
    paper_account_id,
    instrument_id,
    symbol,
    quantity,
    average_cost,
    cost_basis,
    realized_pnl
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (paper_account_id, instrument_id) DO UPDATE
SET quantity = EXCLUDED.quantity,
    average_cost = EXCLUDED.average_cost,
    cost_basis = EXCLUDED.cost_basis,
    realized_pnl = EXCLUDED.realized_pnl,
    updated_at = clock_timestamp(),
    version = securities.positions.version + 1
RETURNING paper_account_id, instrument_id, symbol, quantity, average_cost, cost_basis, realized_pnl, updated_at, version
`

type UpsertPositionParams struct {
	PaperAccountID pgtype.UUID   `json:"paper_account_id"`
	InstrumentID   pgtype.UUID   `json:"instrument_id"`
	Symbol         string        `json:"symbol"`
	Quantity       money.Decimal `json:"quantity"`
	AverageCost    money.Decimal `json:"average_cost"`
	CostBasis      money.Decimal `json:"cost_basis"`
	RealizedPnl    money.Decimal `json:"realized_pnl"`
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) (SecuritiesPosition, error) {
	row := q.db.QueryRow(ctx, upsertPosition,
		arg.PaperAccountID,
		arg.InstrumentID,
		arg.Symbol,
		arg.Quantity,
		arg.AverageCost,
		arg.CostBasis,
		arg.RealizedPnl,
	)
	var i SecuritiesPosition
	err := row.Scan(
		&i.PaperAccountID,
		&i.InstrumentID,
		&i.Symbol,
		&i.Quantity,
		&i.AverageCost,
		&i.CostBasis,
		&i.RealizedPnl,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
