// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type RwaAsset struct {
	ID                   pgtype.UUID        `json:"id"`
	InstrumentID         pgtype.UUID        `json:"instrument_id"`
	UnderlyingSymbol     string             `json:"underlying_symbol"`
	TokenName            string             `json:"token_name"`
	TokenSymbol          string             `json:"token_symbol"`
	TokenDecimals        int16              `json:"token_decimals"`
	ContractAddress      string             `json:"contract_address"`
	PlatformVaultAddress string             `json:"platform_vault_address"`
	Enabled              bool               `json:"enabled"`
	SimulationDisclaimer string             `json:"simulation_disclaimer"`
	PolicyVersion        string             `json:"policy_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type RwaBeneficialHolding struct {
	CustomerReference  string             `json:"customer_reference"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	CustodyMode        string             `json:"custody_mode"`
	DestinationAddress string             `json:"destination_address"`
	Quantity           money.Decimal      `json:"quantity"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Version            int64              `json:"version"`
}

type RwaChainOperation struct {
	OperationID   string             `json:"operation_id"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    pgtype.UUID        `json:"resource_id"`
	OperationType string             `json:"operation_type"`
	Status        string             `json:"status"`
	TxHash        pgtype.Text        `json:"tx_hash"`
	AttemptCount  int32              `json:"attempt_count"`
	MaxAttempts   int32              `json:"max_attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy     pgtype.Text        `json:"claimed_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RwaCommandRequest struct {
	CustomerReference string             `json:"customer_reference"`
	Scope             string             `json:"scope"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       string             `json:"request_hash"`
	ResourceID        pgtype.UUID        `json:"resource_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type RwaCustomerProfile struct {
	CustomerReference   string             `json:"customer_reference"`
	PaperAccountID      pgtype.UUID        `json:"paper_account_id"`
	CashLedgerAccountID pgtype.UUID        `json:"cash_ledger_account_id"`
	Status              string             `json:"status"`
	PolicyVersion       string             `json:"policy_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Version             int64              `json:"version"`
}

type RwaDividend struct {
	ID                pgtype.UUID        `json:"id"`
	AssetID           pgtype.UUID        `json:"asset_id"`
	ExternalReference string             `json:"external_reference"`
	UsdPerShare       money.Decimal      `json:"usd_per_share"`
	RecordAt          pgtype.Timestamptz `json:"record_at"`
	PayableAt         pgtype.Timestamptz `json:"payable_at"`
	Status            string             `json:"status"`
	PolicyVersion     string             `json:"policy_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Version           int64              `json:"version"`
}

// Cash-only USD dividend entitlements. DRIP is intentionally unsupported.
type RwaDividendEntitlement struct {
	ID                      pgtype.UUID        `json:"id"`
	DividendID              pgtype.UUID        `json:"dividend_id"`
	CustomerReference       string             `json:"customer_reference"`
	WholeShares             money.Decimal      `json:"whole_shares"`
	GrossUsd                money.Decimal      `json:"gross_usd"`
	WithholdingUsd          money.Decimal      `json:"withholding_usd"`
	NetUsd                  money.Decimal      `json:"net_usd"`
	CashLedgerTransactionID pgtype.UUID        `json:"cash_ledger_transaction_id"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type RwaExternalAddress struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	Address           string             `json:"address"`
	Status            string             `json:"status"`
	ProofReference    pgtype.Text        `json:"proof_reference"`
	ProofVerifiedAt   pgtype.Timestamptz `json:"proof_verified_at"`
	RiskReasonCode    pgtype.Text        `json:"risk_reason_code"`
	RiskReviewedAt    pgtype.Timestamptz `json:"risk_reviewed_at"`
	CoolingEndsAt     pgtype.Timestamptz `json:"cooling_ends_at"`
	ActivatedAt       pgtype.Timestamptz `json:"activated_at"`
	SuspendedAt       pgtype.Timestamptz `json:"suspended_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Version           int64              `json:"version"`
}

type RwaMintRequest struct {
	ID                   pgtype.UUID        `json:"id"`
	CustomerReference    string             `json:"customer_reference"`
	AssetID              pgtype.UUID        `json:"asset_id"`
	UnderlyingLockID     pgtype.UUID        `json:"underlying_lock_id"`
	Quantity             money.Decimal      `json:"quantity"`
	CustodyMode          string             `json:"custody_mode"`
	DestinationAddressID pgtype.UUID        `json:"destination_address_id"`
	DestinationAddress   string             `json:"destination_address"`
	OperationID          string             `json:"operation_id"`
	Status               string             `json:"status"`
	ChainTxHash          pgtype.Text        `json:"chain_tx_hash"`
	FailureCode          pgtype.Text        `json:"failure_code"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Version              int64              `json:"version"`
}

type RwaPolicy struct {
	PolicyVersion       string             `json:"policy_version"`
	ChainName           string             `json:"chain_name"`
	ChainID             int64              `json:"chain_id"`
	CustodyMode         string             `json:"custody_mode"`
	AddressCoolingHours int32              `json:"address_cooling_hours"`
	RecoveryMaxAttempts int32              `json:"recovery_max_attempts"`
	Active              bool               `json:"active"`
	EffectiveAt         pgtype.Timestamptz `json:"effective_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type RwaProviderEvent struct {
	Provider        string             `json:"provider"`
	ExternalEventID string             `json:"external_event_id"`
	EventType       string             `json:"event_type"`
	PayloadHash     string             `json:"payload_hash"`
	OperationID     string             `json:"operation_id"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
}

type RwaReconciliationRun struct {
	ID               pgtype.UUID        `json:"id"`
	AssetID          pgtype.UUID        `json:"asset_id"`
	ChainSupply      money.Decimal      `json:"chain_supply"`
	LockedShares     money.Decimal      `json:"locked_shares"`
	Difference       money.Decimal      `json:"difference"`
	Status           string             `json:"status"`
	ComplianceCaseID pgtype.UUID        `json:"compliance_case_id"`
	ObservedBlock    string             `json:"observed_block"`
	DailyKey         pgtype.Text        `json:"daily_key"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type RwaRedemptionRequest struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	AssetID           pgtype.UUID        `json:"asset_id"`
	UnderlyingLockID  pgtype.UUID        `json:"underlying_lock_id"`
	Quantity          money.Decimal      `json:"quantity"`
	SourceAddress     string             `json:"source_address"`
	OperationID       string             `json:"operation_id"`
	Forced            bool               `json:"forced"`
	Status            string             `json:"status"`
	ChainTxHash       pgtype.Text        `json:"chain_tx_hash"`
	FailureCode       pgtype.Text        `json:"failure_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	Version           int64              `json:"version"`
}

type RwaStateEvent struct {
	ID           pgtype.UUID        `json:"id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	FromStatus   pgtype.Text        `json:"from_status"`
	ToStatus     string             `json:"to_status"`
	ActorType    string             `json:"actor_type"`
	ActorID      string             `json:"actor_id"`
	ReasonCode   pgtype.Text        `json:"reason_code"`
	Metadata     []byte             `json:"metadata"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

// Whole settled shares reserved one-for-one before chain mint. Release is allowed only after confirmed burn.
type RwaUnderlyingLock struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	AssetID           pgtype.UUID        `json:"asset_id"`
	ReservationID     pgtype.UUID        `json:"reservation_id"`
	Quantity          money.Decimal      `json:"quantity"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ReleasedAt        pgtype.Timestamptz `json:"released_at"`
	Version           int64              `json:"version"`
}
