// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateExternalAddress(ctx context.Context, id pgtype.UUID) (RwaExternalAddress, error)
	ClaimChainOperations(ctx context.Context, arg ClaimChainOperationsParams) ([]RwaChainOperation, error)
	CreateChainOperation(ctx context.Context, arg CreateChainOperationParams) (RwaChainOperation, error)
	CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (RwaCustomerProfile, error)
	CreateDividend(ctx context.Context, arg CreateDividendParams) (RwaDividend, error)
	CreateExternalAddress(ctx context.Context, arg CreateExternalAddressParams) (RwaExternalAddress, error)
	CreateMintRequest(ctx context.Context, arg CreateMintRequestParams) (RwaMintRequest, error)
	CreateRedemptionRequest(ctx context.Context, arg CreateRedemptionRequestParams) (RwaRedemptionRequest, error)
	CreateUnderlyingLock(ctx context.Context, arg CreateUnderlyingLockParams) (RwaUnderlyingLock, error)
	GetActivePolicy(ctx context.Context) (RwaPolicy, error)
	GetAsset(ctx context.Context, id pgtype.UUID) (RwaAsset, error)
	GetAssetBySymbol(ctx context.Context, underlyingSymbol string) (RwaAsset, error)
	GetBeneficialHolding(ctx context.Context, arg GetBeneficialHoldingParams) (RwaBeneficialHolding, error)
	GetBeneficialHoldingForUpdate(ctx context.Context, arg GetBeneficialHoldingForUpdateParams) (RwaBeneficialHolding, error)
	GetChainOperation(ctx context.Context, operationID string) (RwaChainOperation, error)
	GetChainOperationForUpdate(ctx context.Context, operationID string) (RwaChainOperation, error)
	GetCommandRequest(ctx context.Context, arg GetCommandRequestParams) (RwaCommandRequest, error)
	GetCustomerExternalAddressForUpdate(ctx context.Context, arg GetCustomerExternalAddressForUpdateParams) (RwaExternalAddress, error)
	GetCustomerMintRequest(ctx context.Context, arg GetCustomerMintRequestParams) (RwaMintRequest, error)
	GetCustomerProfile(ctx context.Context, customerReference string) (RwaCustomerProfile, error)
	GetCustomerProfileForUpdate(ctx context.Context, customerReference string) (RwaCustomerProfile, error)
	GetCustomerRedemptionRequest(ctx context.Context, arg GetCustomerRedemptionRequestParams) (RwaRedemptionRequest, error)
	GetDividend(ctx context.Context, id pgtype.UUID) (RwaDividend, error)
	GetDividendEntitlementForUpdate(ctx context.Context, id pgtype.UUID) (RwaDividendEntitlement, error)
	GetDividendForUpdate(ctx context.Context, id pgtype.UUID) (RwaDividend, error)
	GetExternalAddress(ctx context.Context, id pgtype.UUID) (RwaExternalAddress, error)
	GetMintRequest(ctx context.Context, id pgtype.UUID) (RwaMintRequest, error)
	GetMintRequestForUpdate(ctx context.Context, id pgtype.UUID) (RwaMintRequest, error)
	GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (RwaProviderEvent, error)
	GetRedemptionRequest(ctx context.Context, id pgtype.UUID) (RwaRedemptionRequest, error)
	GetRedemptionRequestForUpdate(ctx context.Context, id pgtype.UUID) (RwaRedemptionRequest, error)
	GetUnderlyingLock(ctx context.Context, id pgtype.UUID) (RwaUnderlyingLock, error)
	GetUnderlyingLockForUpdate(ctx context.Context, id pgtype.UUID) (RwaUnderlyingLock, error)
	InsertCommandRequest(ctx context.Context, arg InsertCommandRequestParams) (RwaCommandRequest, error)
	InsertDividendEntitlement(ctx context.Context, arg InsertDividendEntitlementParams) (RwaDividendEntitlement, error)
	InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (RwaProviderEvent, error)
	InsertReconciliationRun(ctx context.Context, arg InsertReconciliationRunParams) (RwaReconciliationRun, error)
	InsertStateEvent(ctx context.Context, arg InsertStateEventParams) (RwaStateEvent, error)
	ListAssets(ctx context.Context) ([]RwaAsset, error)
	ListBeneficialHoldings(ctx context.Context, customerReference string) ([]RwaBeneficialHolding, error)
	ListDividendEntitlements(ctx context.Context, dividendID pgtype.UUID) ([]RwaDividendEntitlement, error)
	ListExternalAddresses(ctx context.Context, customerReference string) ([]RwaExternalAddress, error)
	ListMintRequests(ctx context.Context, customerReference string) ([]RwaMintRequest, error)
	ListPositiveHoldingsForAsset(ctx context.Context, assetID pgtype.UUID) ([]RwaBeneficialHolding, error)
	ListReconciliationRuns(ctx context.Context, arg ListReconciliationRunsParams) ([]RwaReconciliationRun, error)
	ListRedemptionRequests(ctx context.Context, customerReference string) ([]RwaRedemptionRequest, error)
	MarkAddressCooling(ctx context.Context, arg MarkAddressCoolingParams) (RwaExternalAddress, error)
	MarkAddressProofVerified(ctx context.Context, arg MarkAddressProofVerifiedParams) (RwaExternalAddress, error)
	MarkAddressRiskReview(ctx context.Context, id pgtype.UUID) (RwaExternalAddress, error)
	MarkDividendEntitlementCredited(ctx context.Context, arg MarkDividendEntitlementCreditedParams) (RwaDividendEntitlement, error)
	MoveExhaustedOperationsToDLQ(ctx context.Context) (int64, error)
	ReduceBeneficialHolding(ctx context.Context, arg ReduceBeneficialHoldingParams) (RwaBeneficialHolding, error)
	RejectExternalAddress(ctx context.Context, arg RejectExternalAddressParams) (RwaExternalAddress, error)
	ReleaseUnderlyingLock(ctx context.Context, id pgtype.UUID) (RwaUnderlyingLock, error)
	SumLockedSharesByAsset(ctx context.Context, assetID pgtype.UUID) (money.Decimal, error)
	SuspendExternalAddress(ctx context.Context, id pgtype.UUID) (RwaExternalAddress, error)
	UpdateChainOperation(ctx context.Context, arg UpdateChainOperationParams) (RwaChainOperation, error)
	UpdateDividendStatus(ctx context.Context, arg UpdateDividendStatusParams) (RwaDividend, error)
	UpdateMintState(ctx context.Context, arg UpdateMintStateParams) (RwaMintRequest, error)
	UpdateRedemptionState(ctx context.Context, arg UpdateRedemptionStateParams) (RwaRedemptionRequest, error)
	UpsertBeneficialHolding(ctx context.Context, arg UpsertBeneficialHoldingParams) (RwaBeneficialHolding, error)
}

var _ Querier = (*Queries)(nil)
