// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rwa.sql

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateExternalAddress = `-- name: ActivateExternalAddress :one
UPDATE rwa.external_addresses
SET status = 'ACTIVE', activated_at = clock_timestamp(), updated_at = clock_timestamp(), version = version + 1
WHERE id = $1 AND status = 'COOLING' AND cooling_ends_at <= clock_timestamp()
RETURNING id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version
`

func (q *Queries) ActivateExternalAddress(ctx context.Context, id pgtype.UUID) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, activateExternalAddress, id)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const claimChainOperations = `-- name: ClaimChainOperations :many
WITH candidates AS (
    SELECT operation_id FROM rwa.chain_operations
    WHERE status IN ('PENDING', 'UNKNOWN')
      AND next_attempt_at <= clock_timestamp()
      AND attempt_count < max_attempts
      AND claimed_at IS NULL
    ORDER BY next_attempt_at, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
UPDATE rwa.chain_operations AS operation
SET claimed_at = clock_timestamp(), claimed_by = $1, updated_at = clock_timestamp()
FROM candidates
WHERE operation.operation_id = candidates.operation_id
RETURNING operation.operation_id, operation.resource_type, operation.resource_id, operation.operation_type, operation.status, operation.tx_hash, operation.attempt_count, operation.max_attempts, operation.next_attempt_at, operation.last_error_code, operation.claimed_at, operation.claimed_by, operation.created_at, operation.updated_at
`

type ClaimChainOperationsParams struct {
	WorkerID  pgtype.Text `json:"worker_id"`
	BatchSize int32       `json:"batch_size"`
}

func (q *Queries) ClaimChainOperations(ctx context.Context, arg ClaimChainOperationsParams) ([]RwaChainOperation, error) {
	rows, err := q.db.Query(ctx, claimChainOperations, arg.WorkerID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaChainOperation
	for rows.Next() {
		var i RwaChainOperation
		if err := rows.Scan(
			&i.OperationID,
			&i.ResourceType,
			&i.ResourceID,
			&i.OperationType,
			&i.Status,
			&i.TxHash,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastErrorCode,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createChainOperation = `-- name: CreateChainOperation :one
INSERT INTO rwa.chain_operations (
    operation_id, resource_type, resource_id, operation_type, max_attempts
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING operation_id, resource_type, resource_id, operation_type, status, tx_hash, attempt_count, max_attempts, next_attempt_at, last_error_code, claimed_at, claimed_by, created_at, updated_at
`

type CreateChainOperationParams struct {
	OperationID   string      `json:"operation_id"`
	ResourceType  string      `json:"resource_type"`
	ResourceID    pgtype.UUID `json:"resource_id"`
	OperationType string      `json:"operation_type"`
	MaxAttempts   int32       `json:"max_attempts"`
}

func (q *Queries) CreateChainOperation(ctx context.Context, arg CreateChainOperationParams) (RwaChainOperation, error) {
	row := q.db.QueryRow(ctx, createChainOperation,
		arg.OperationID,
		arg.ResourceType,
		arg.ResourceID,
		arg.OperationType,
		arg.MaxAttempts,
	)
	var i RwaChainOperation
	err := row.Scan(
		&i.OperationID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OperationType,
		&i.Status,
		&i.TxHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomerProfile = `-- name: CreateCustomerProfile :one
INSERT INTO rwa.customer_profiles (
    customer_reference, paper_account_id, cash_ledger_account_id, policy_version
) VALUES (
    $1, $2,
    $3, $4
)
ON CONFLICT (customer_reference) DO NOTHING
RETURNING customer_reference, paper_account_id, cash_ledger_account_id, status, policy_version, created_at, updated_at, version
`

type CreateCustomerProfileParams struct {
	CustomerReference   string      `json:"customer_reference"`
	PaperAccountID      pgtype.UUID `json:"paper_account_id"`
	CashLedgerAccountID pgtype.UUID `json:"cash_ledger_account_id"`
	PolicyVersion       string      `json:"policy_version"`
}

func (q *Queries) CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (RwaCustomerProfile, error) {
	row := q.db.QueryRow(ctx, createCustomerProfile,
		arg.CustomerReference,
		arg.PaperAccountID,
		arg.CashLedgerAccountID,
		arg.PolicyVersion,
	)
	var i RwaCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.Status,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createDividend = `-- name: CreateDividend :one
INSERT INTO rwa.dividends (
    id, asset_id, external_reference, usd_per_share, record_at, payable_at, policy_version
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
RETURNING id, asset_id, external_reference, usd_per_share, record_at, payable_at, status, policy_version, created_at, updated_at, version
`

type CreateDividendParams struct {
	ID                pgtype.UUID        `json:"id"`
	AssetID           pgtype.UUID        `json:"asset_id"`
	ExternalReference string             `json:"external_reference"`
	UsdPerShare       money.Decimal      `json:"usd_per_share"`
	RecordAt          pgtype.Timestamptz `json:"record_at"`
	PayableAt         pgtype.Timestamptz `json:"payable_at"`
	PolicyVersion     string             `json:"policy_version"`
}

func (q *Queries) CreateDividend(ctx context.Context, arg CreateDividendParams) (RwaDividend, error) {
	row := q.db.QueryRow(ctx, createDividend,
		arg.ID,
		arg.AssetID,
		arg.ExternalReference,
		arg.UsdPerShare,
		arg.RecordAt,
		arg.PayableAt,
		arg.PolicyVersion,
	)
	var i RwaDividend
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ExternalReference,
		&i.UsdPerShare,
		&i.RecordAt,
		&i.PayableAt,
		&i.Status,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createExternalAddress = `-- name: CreateExternalAddress :one
INSERT INTO rwa.external_addresses (id, customer_reference, address)
VALUES ($1, $2, $3)
RETURNING id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version
`

type CreateExternalAddressParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
	Address           string      `json:"address"`
}

func (q *Queries) CreateExternalAddress(ctx context.Context, arg CreateExternalAddressParams) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, createExternalAddress, arg.ID, arg.CustomerReference, arg.Address)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createMintRequest = `-- name: CreateMintRequest :one
INSERT INTO rwa.mint_requests (
    id, customer_reference, asset_id, underlying_lock_id, quantity, custody_mode,
    destination_address_id, destination_address, operation_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
RETURNING id, customer_reference, asset_id, underlying_lock_id, quantity, custody_mode, destination_address_id, destination_address, operation_id, status, chain_tx_hash, failure_code, created_at, updated_at, version
`

type CreateMintRequestParams struct {
	ID                   pgtype.UUID   `json:"id"`
	CustomerReference    string        `json:"customer_reference"`
	AssetID              pgtype.UUID   `json:"asset_id"`
	UnderlyingLockID     pgtype.UUID   `json:"underlying_lock_id"`
	Quantity             money.Decimal `json:"quantity"`
	CustodyMode          string        `json:"custody_mode"`
	DestinationAddressID pgtype.UUID   `json:"destination_address_id"`
	DestinationAddress   string        `json:"destination_address"`
	OperationID          string        `json:"operation_id"`
}

func (q *Queries) CreateMintRequest(ctx context.Context, arg CreateMintRequestParams) (RwaMintRequest, error) {
	row := q.db.QueryRow(ctx, createMintRequest,
		arg.ID,
		arg.CustomerReference,
		arg.AssetID,
		arg.UnderlyingLockID,
		arg.Quantity,
		arg.CustodyMode,
		arg.DestinationAddressID,
		arg.DestinationAddress,
		arg.OperationID,
	)
	var i RwaMintRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.CustodyMode,
		&i.DestinationAddressID,
		&i.DestinationAddress,
		&i.OperationID,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createRedemptionRequest = `-- name: CreateRedemptionRequest :one
INSERT INTO rwa.redemption_requests (
    id, customer_reference, asset_id, underlying_lock_id, quantity,
    source_address, operation_id, forced
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
RETURNING id, customer_reference, asset_id, underlying_lock_id, quantity, source_address, operation_id, forced, status, chain_tx_hash, failure_code, created_at, updated_at, completed_at, version
`

type CreateRedemptionRequestParams struct {
	ID                pgtype.UUID   `json:"id"`
	CustomerReference string        `json:"customer_reference"`
	AssetID           pgtype.UUID   `json:"asset_id"`
	UnderlyingLockID  pgtype.UUID   `json:"underlying_lock_id"`
	Quantity          money.Decimal `json:"quantity"`
	SourceAddress     string        `json:"source_address"`
	OperationID       string        `json:"operation_id"`
	Forced            bool          `json:"forced"`
}

func (q *Queries) CreateRedemptionRequest(ctx context.Context, arg CreateRedemptionRequestParams) (RwaRedemptionRequest, error) {
	row := q.db.QueryRow(ctx, createRedemptionRequest,
		arg.ID,
		arg.CustomerReference,
		arg.AssetID,
		arg.UnderlyingLockID,
		arg.Quantity,
		arg.SourceAddress,
		arg.OperationID,
		arg.Forced,
	)
	var i RwaRedemptionRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.SourceAddress,
		&i.OperationID,
		&i.Forced,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const createUnderlyingLock = `-- name: CreateUnderlyingLock :one
INSERT INTO rwa.underlying_locks (
    id, customer_reference, asset_id, reservation_id, quantity
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING id, customer_reference, asset_id, reservation_id, quantity, status, created_at, released_at, version
`

type CreateUnderlyingLockParams struct {
	ID                pgtype.UUID   `json:"id"`
	CustomerReference string        `json:"customer_reference"`
	AssetID           pgtype.UUID   `json:"asset_id"`
	ReservationID     pgtype.UUID   `json:"reservation_id"`
	Quantity          money.Decimal `json:"quantity"`
}

func (q *Queries) CreateUnderlyingLock(ctx context.Context, arg CreateUnderlyingLockParams) (RwaUnderlyingLock, error) {
	row := q.db.QueryRow(ctx, createUnderlyingLock,
		arg.ID,
		arg.CustomerReference,
		arg.AssetID,
		arg.ReservationID,
		arg.Quantity,
	)
	var i RwaUnderlyingLock
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.ReservationID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Version,
	)
	return i, err
}

const getActivePolicy = `-- name: GetActivePolicy :one
SELECT policy_version, chain_name, chain_id, custody_mode, address_cooling_hours, recovery_max_attempts, active, effective_at, created_at FROM rwa.policies
WHERE active AND effective_at <= clock_timestamp()
ORDER BY effective_at DESC LIMIT 1
`

func (q *Queries) GetActivePolicy(ctx context.Context) (RwaPolicy, error) {
	row := q.db.QueryRow(ctx, getActivePolicy)
	var i RwaPolicy
	err := row.Scan(
		&i.PolicyVersion,
		&i.ChainName,
		&i.ChainID,
		&i.CustodyMode,
		&i.AddressCoolingHours,
		&i.RecoveryMaxAttempts,
		&i.Active,
		&i.EffectiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, instrument_id, underlying_symbol, token_name, token_symbol, token_decimals, contract_address, platform_vault_address, enabled, simulation_disclaimer, policy_version, created_at FROM rwa.assets WHERE id = $1 AND enabled
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (RwaAsset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i RwaAsset
	err := row.Scan(
		&i.ID,
		&i.InstrumentID,
		&i.UnderlyingSymbol,
		&i.TokenName,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.ContractAddress,
		&i.PlatformVaultAddress,
		&i.Enabled,
		&i.SimulationDisclaimer,
		&i.PolicyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetBySymbol = `-- name: GetAssetBySymbol :one
SELECT id, instrument_id, underlying_symbol, token_name, token_symbol, token_decimals, contract_address, platform_vault_address, enabled, simulation_disclaimer, policy_version, created_at FROM rwa.assets WHERE underlying_symbol = $1 AND enabled
`

func (q *Queries) GetAssetBySymbol(ctx context.Context, underlyingSymbol string) (RwaAsset, error) {
	row := q.db.QueryRow(ctx, getAssetBySymbol, underlyingSymbol)
	var i RwaAsset
	err := row.Scan(
		&i.ID,
		&i.InstrumentID,
		&i.UnderlyingSymbol,
		&i.TokenName,
		&i.TokenSymbol,
		&i.TokenDecimals,
		&i.ContractAddress,
		&i.PlatformVaultAddress,
		&i.Enabled,
		&i.SimulationDisclaimer,
		&i.PolicyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getBeneficialHolding = `-- name: GetBeneficialHolding :one
SELECT customer_reference, asset_id, custody_mode, destination_address, quantity, updated_at, version FROM rwa.beneficial_holdings
WHERE customer_reference = $1 AND asset_id = $2
`

type GetBeneficialHoldingParams struct {
	CustomerReference string      `json:"customer_reference"`
	AssetID           pgtype.UUID `json:"asset_id"`
}

func (q *Queries) GetBeneficialHolding(ctx context.Context, arg GetBeneficialHoldingParams) (RwaBeneficialHolding, error) {
	row := q.db.QueryRow(ctx, getBeneficialHolding, arg.CustomerReference, arg.AssetID)
	var i RwaBeneficialHolding
	err := row.Scan(
		&i.CustomerReference,
		&i.AssetID,
		&i.CustodyMode,
		&i.DestinationAddress,
		&i.Quantity,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getBeneficialHoldingForUpdate = `-- name: GetBeneficialHoldingForUpdate :one
SELECT customer_reference, asset_id, custody_mode, destination_address, quantity, updated_at, version FROM rwa.beneficial_holdings
WHERE customer_reference = $1 AND asset_id = $2
FOR UPDATE
`

type GetBeneficialHoldingForUpdateParams struct {
	CustomerReference string      `json:"customer_reference"`
	AssetID           pgtype.UUID `json:"asset_id"`
}

func (q *Queries) GetBeneficialHoldingForUpdate(ctx context.Context, arg GetBeneficialHoldingForUpdateParams) (RwaBeneficialHolding, error) {
	row := q.db.QueryRow(ctx, getBeneficialHoldingForUpdate, arg.CustomerReference, arg.AssetID)
	var i RwaBeneficialHolding
	err := row.Scan(
		&i.CustomerReference,
		&i.AssetID,
		&i.CustodyMode,
		&i.DestinationAddress,
		&i.Quantity,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getChainOperation = `-- name: GetChainOperation :one
SELECT operation_id, resource_type, resource_id, operation_type, status, tx_hash, attempt_count, max_attempts, next_attempt_at, last_error_code, claimed_at, claimed_by, created_at, updated_at FROM rwa.chain_operations WHERE operation_id = $1
`

func (q *Queries) GetChainOperation(ctx context.Context, operationID string) (RwaChainOperation, error) {
	row := q.db.QueryRow(ctx, getChainOperation, operationID)
	var i RwaChainOperation
	err := row.Scan(
		&i.OperationID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OperationType,
		&i.Status,
		&i.TxHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChainOperationForUpdate = `-- name: GetChainOperationForUpdate :one
SELECT operation_id, resource_type, resource_id, operation_type, status, tx_hash, attempt_count, max_attempts, next_attempt_at, last_error_code, claimed_at, claimed_by, created_at, updated_at FROM rwa.chain_operations WHERE operation_id = $1 FOR UPDATE
`

func (q *Queries) GetChainOperationForUpdate(ctx context.Context, operationID string) (RwaChainOperation, error) {
	row := q.db.QueryRow(ctx, getChainOperationForUpdate, operationID)
	var i RwaChainOperation
	err := row.Scan(
		&i.OperationID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OperationType,
		&i.Status,
		&i.TxHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommandRequest = `-- name: GetCommandRequest :one
SELECT customer_reference, scope, idempotency_key, request_hash, resource_id, created_at FROM rwa.command_requests
WHERE customer_reference = $1
  AND scope = $2
  AND idempotency_key = $3
`

type GetCommandRequestParams struct {
	CustomerReference string `json:"customer_reference"`
	Scope             string `json:"scope"`
	IdempotencyKey    string `json:"idempotency_key"`
}

func (q *Queries) GetCommandRequest(ctx context.Context, arg GetCommandRequestParams) (RwaCommandRequest, error) {
	row := q.db.QueryRow(ctx, getCommandRequest, arg.CustomerReference, arg.Scope, arg.IdempotencyKey)
	var i RwaCommandRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerExternalAddressForUpdate = `-- name: GetCustomerExternalAddressForUpdate :one
SELECT id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version FROM rwa.external_addresses
WHERE id = $1 AND customer_reference = $2
FOR UPDATE
`

type GetCustomerExternalAddressForUpdateParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
}

func (q *Queries) GetCustomerExternalAddressForUpdate(ctx context.Context, arg GetCustomerExternalAddressForUpdateParams) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, getCustomerExternalAddressForUpdate, arg.ID, arg.CustomerReference)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerMintRequest = `-- name: GetCustomerMintRequest :one
SELECT id, customer_reference, asset_id, underlying_lock_id, quantity, custody_mode, destination_address_id, destination_address, operation_id, status, chain_tx_hash, failure_code, created_at, updated_at, version FROM rwa.mint_requests
WHERE id = $1 AND customer_reference = $2
`

type GetCustomerMintRequestParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
}

func (q *Queries) GetCustomerMintRequest(ctx context.Context, arg GetCustomerMintRequestParams) (RwaMintRequest, error) {
	row := q.db.QueryRow(ctx, getCustomerMintRequest, arg.ID, arg.CustomerReference)
	var i RwaMintRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.CustodyMode,
		&i.DestinationAddressID,
		&i.DestinationAddress,
		&i.OperationID,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerProfile = `-- name: GetCustomerProfile :one
SELECT customer_reference, paper_account_id, cash_ledger_account_id, status, policy_version, created_at, updated_at, version FROM rwa.customer_profiles WHERE customer_reference = $1
`

func (q *Queries) GetCustomerProfile(ctx context.Context, customerReference string) (RwaCustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfile, customerReference)
	var i RwaCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.Status,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerProfileForUpdate = `-- name: GetCustomerProfileForUpdate :one
SELECT customer_reference, paper_account_id, cash_ledger_account_id, status, policy_version, created_at, updated_at, version FROM rwa.customer_profiles WHERE customer_reference = $1 FOR UPDATE
`

func (q *Queries) GetCustomerProfileForUpdate(ctx context.Context, customerReference string) (RwaCustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfileForUpdate, customerReference)
	var i RwaCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.Status,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerRedemptionRequest = `-- name: GetCustomerRedemptionRequest :one
SELECT id, customer_reference, asset_id, underlying_lock_id, quantity, source_address, operation_id, forced, status, chain_tx_hash, failure_code, created_at, updated_at, completed_at, version FROM rwa.redemption_requests
WHERE id = $1 AND customer_reference = $2
`

type GetCustomerRedemptionRequestParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
}

func (q *Queries) GetCustomerRedemptionRequest(ctx context.Context, arg GetCustomerRedemptionRequestParams) (RwaRedemptionRequest, error) {
	row := q.db.QueryRow(ctx, getCustomerRedemptionRequest, arg.ID, arg.CustomerReference)
	var i RwaRedemptionRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.SourceAddress,
		&i.OperationID,
		&i.Forced,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const getDividend = `-- name: GetDividend :one
SELECT id, asset_id, external_reference, usd_per_share, record_at, payable_at, status, policy_version, created_at, updated_at, version FROM rwa.dividends WHERE id = $1
`

func (q *Queries) GetDividend(ctx context.Context, id pgtype.UUID) (RwaDividend, error) {
	row := q.db.QueryRow(ctx, getDividend, id)
	var i RwaDividend
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ExternalReference,
		&i.UsdPerShare,
		&i.RecordAt,
		&i.PayableAt,
		&i.Status,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getDividendEntitlementForUpdate = `-- name: GetDividendEntitlementForUpdate :one
SELECT id, dividend_id, customer_reference, whole_shares, gross_usd, withholding_usd, net_usd, cash_ledger_transaction_id, status, created_at, updated_at FROM rwa.dividend_entitlements WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetDividendEntitlementForUpdate(ctx context.Context, id pgtype.UUID) (RwaDividendEntitlement, error) {
	row := q.db.QueryRow(ctx, getDividendEntitlementForUpdate, id)
	var i RwaDividendEntitlement
	err := row.Scan(
		&i.ID,
		&i.DividendID,
		&i.CustomerReference,
		&i.WholeShares,
		&i.GrossUsd,
		&i.WithholdingUsd,
		&i.NetUsd,
		&i.CashLedgerTransactionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDividendForUpdate = `-- name: GetDividendForUpdate :one
SELECT id, asset_id, external_reference, usd_per_share, record_at, payable_at, status, policy_version, created_at, updated_at, version FROM rwa.dividends WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetDividendForUpdate(ctx context.Context, id pgtype.UUID) (RwaDividend, error) {
	row := q.db.QueryRow(ctx, getDividendForUpdate, id)
	var i RwaDividend
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ExternalReference,
		&i.UsdPerShare,
		&i.RecordAt,
		&i.PayableAt,
		&i.Status,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getExternalAddress = `-- name: GetExternalAddress :one
SELECT id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version FROM rwa.external_addresses WHERE id = $1
`

func (q *Queries) GetExternalAddress(ctx context.Context, id pgtype.UUID) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, getExternalAddress, id)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getMintRequest = `-- name: GetMintRequest :one
SELECT id, customer_reference, asset_id, underlying_lock_id, quantity, custody_mode, destination_address_id, destination_address, operation_id, status, chain_tx_hash, failure_code, created_at, updated_at, version FROM rwa.mint_requests WHERE id = $1
`

func (q *Queries) GetMintRequest(ctx context.Context, id pgtype.UUID) (RwaMintRequest, error) {
	row := q.db.QueryRow(ctx, getMintRequest, id)
	var i RwaMintRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.CustodyMode,
		&i.DestinationAddressID,
		&i.DestinationAddress,
		&i.OperationID,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getMintRequestForUpdate = `-- name: GetMintRequestForUpdate :one
SELECT id, customer_reference, asset_id, underlying_lock_id, quantity, custody_mode, destination_address_id, destination_address, operation_id, status, chain_tx_hash, failure_code, created_at, updated_at, version FROM rwa.mint_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetMintRequestForUpdate(ctx context.Context, id pgtype.UUID) (RwaMintRequest, error) {
	row := q.db.QueryRow(ctx, getMintRequestForUpdate, id)
	var i RwaMintRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.CustodyMode,
		&i.DestinationAddressID,
		&i.DestinationAddress,
		&i.OperationID,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getProviderEvent = `-- name: GetProviderEvent :one
SELECT provider, external_event_id, event_type, payload_hash, operation_id, received_at FROM rwa.provider_events
WHERE provider = $1 AND external_event_id = $2
`

type GetProviderEventParams struct {
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (RwaProviderEvent, error) {
	row := q.db.QueryRow(ctx, getProviderEvent, arg.Provider, arg.ExternalEventID)
	var i RwaProviderEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.EventType,
		&i.PayloadHash,
		&i.OperationID,
		&i.ReceivedAt,
	)
	return i, err
}

const getRedemptionRequest = `-- name: GetRedemptionRequest :one
SELECT id, customer_reference, asset_id, underlying_lock_id, quantity, source_address, operation_id, forced, status, chain_tx_hash, failure_code, created_at, updated_at, completed_at, version FROM rwa.redemption_requests WHERE id = $1
`

func (q *Queries) GetRedemptionRequest(ctx context.Context, id pgtype.UUID) (RwaRedemptionRequest, error) {
	row := q.db.QueryRow(ctx, getRedemptionRequest, id)
	var i RwaRedemptionRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.SourceAddress,
		&i.OperationID,
		&i.Forced,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const getRedemptionRequestForUpdate = `-- name: GetRedemptionRequestForUpdate :one
SELECT id, customer_reference, asset_id, underlying_lock_id, quantity, source_address, operation_id, forced, status, chain_tx_hash, failure_code, created_at, updated_at, completed_at, version FROM rwa.redemption_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRedemptionRequestForUpdate(ctx context.Context, id pgtype.UUID) (RwaRedemptionRequest, error) {
	row := q.db.QueryRow(ctx, getRedemptionRequestForUpdate, id)
	var i RwaRedemptionRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.SourceAddress,
		&i.OperationID,
		&i.Forced,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const getUnderlyingLock = `-- name: GetUnderlyingLock :one
SELECT id, customer_reference, asset_id, reservation_id, quantity, status, created_at, released_at, version FROM rwa.underlying_locks WHERE id = $1
`

func (q *Queries) GetUnderlyingLock(ctx context.Context, id pgtype.UUID) (RwaUnderlyingLock, error) {
	row := q.db.QueryRow(ctx, getUnderlyingLock, id)
	var i RwaUnderlyingLock
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.ReservationID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Version,
	)
	return i, err
}

const getUnderlyingLockForUpdate = `-- name: GetUnderlyingLockForUpdate :one
SELECT id, customer_reference, asset_id, reservation_id, quantity, status, created_at, released_at, version FROM rwa.underlying_locks WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUnderlyingLockForUpdate(ctx context.Context, id pgtype.UUID) (RwaUnderlyingLock, error) {
	row := q.db.QueryRow(ctx, getUnderlyingLockForUpdate, id)
	var i RwaUnderlyingLock
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.ReservationID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Version,
	)
	return i, err
}

const insertCommandRequest = `-- name: InsertCommandRequest :one
INSERT INTO rwa.command_requests (
    customer_reference, scope, idempotency_key, request_hash, resource_id
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (customer_reference, scope, idempotency_key) DO NOTHING
RETURNING customer_reference, scope, idempotency_key, request_hash, resource_id, created_at
`

type InsertCommandRequestParams struct {
	CustomerReference string      `json:"customer_reference"`
	Scope             string      `json:"scope"`
	IdempotencyKey    string      `json:"idempotency_key"`
	RequestHash       string      `json:"request_hash"`
	ResourceID        pgtype.UUID `json:"resource_id"`
}

func (q *Queries) InsertCommandRequest(ctx context.Context, arg InsertCommandRequestParams) (RwaCommandRequest, error) {
	row := q.db.QueryRow(ctx, insertCommandRequest,
		arg.CustomerReference,
		arg.Scope,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResourceID,
	)
	var i RwaCommandRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const insertDividendEntitlement = `-- name: InsertDividendEntitlement :one
INSERT INTO rwa.dividend_entitlements (
    id, dividend_id, customer_reference, whole_shares, gross_usd, withholding_usd, net_usd
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (dividend_id, customer_reference) DO NOTHING
RETURNING id, dividend_id, customer_reference, whole_shares, gross_usd, withholding_usd, net_usd, cash_ledger_transaction_id, status, created_at, updated_at
`

type InsertDividendEntitlementParams struct {
	ID                pgtype.UUID   `json:"id"`
	DividendID        pgtype.UUID   `json:"dividend_id"`
	CustomerReference string        `json:"customer_reference"`
	WholeShares       money.Decimal `json:"whole_shares"`
	GrossUsd          money.Decimal `json:"gross_usd"`
	WithholdingUsd    money.Decimal `json:"withholding_usd"`
	NetUsd            money.Decimal `json:"net_usd"`
}

func (q *Queries) InsertDividendEntitlement(ctx context.Context, arg InsertDividendEntitlementParams) (RwaDividendEntitlement, error) {
	row := q.db.QueryRow(ctx, insertDividendEntitlement,
		arg.ID,
		arg.DividendID,
		arg.CustomerReference,
		arg.WholeShares,
		arg.GrossUsd,
		arg.WithholdingUsd,
		arg.NetUsd,
	)
	var i RwaDividendEntitlement
	err := row.Scan(
		&i.ID,
		&i.DividendID,
		&i.CustomerReference,
		&i.WholeShares,
		&i.GrossUsd,
		&i.WithholdingUsd,
		&i.NetUsd,
		&i.CashLedgerTransactionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProviderEvent = `-- name: InsertProviderEvent :one
INSERT INTO rwa.provider_events (
    provider, external_event_id, event_type, payload_hash, operation_id
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (provider, external_event_id) DO NOTHING
RETURNING provider, external_event_id, event_type, payload_hash, operation_id, received_at
`

type InsertProviderEventParams struct {
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
	EventType       string `json:"event_type"`
	PayloadHash     string `json:"payload_hash"`
	OperationID     string `json:"operation_id"`
}

func (q *Queries) InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (RwaProviderEvent, error) {
	row := q.db.QueryRow(ctx, insertProviderEvent,
		arg.Provider,
		arg.ExternalEventID,
		arg.EventType,
		arg.PayloadHash,
		arg.OperationID,
	)
	var i RwaProviderEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.EventType,
		&i.PayloadHash,
		&i.OperationID,
		&i.ReceivedAt,
	)
	return i, err
}

const insertReconciliationRun = `-- name: InsertReconciliationRun :one
INSERT INTO rwa.reconciliation_runs (
    id, asset_id, chain_supply, locked_shares, difference, status,
    compliance_case_id, observed_block, daily_key
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9
)
RETURNING id, asset_id, chain_supply, locked_shares, difference, status, compliance_case_id, observed_block, daily_key, started_at, completed_at
`

type InsertReconciliationRunParams struct {
	ID               pgtype.UUID   `json:"id"`
	AssetID          pgtype.UUID   `json:"asset_id"`
	ChainSupply      money.Decimal `json:"chain_supply"`
	LockedShares     money.Decimal `json:"locked_shares"`
	Difference       money.Decimal `json:"difference"`
	Status           string        `json:"status"`
	ComplianceCaseID pgtype.UUID   `json:"compliance_case_id"`
	ObservedBlock    string        `json:"observed_block"`
	DailyKey         pgtype.Text   `json:"daily_key"`
}

func (q *Queries) InsertReconciliationRun(ctx context.Context, arg InsertReconciliationRunParams) (RwaReconciliationRun, error) {
	row := q.db.QueryRow(ctx, insertReconciliationRun,
		arg.ID,
		arg.AssetID,
		arg.ChainSupply,
		arg.LockedShares,
		arg.Difference,
		arg.Status,
		arg.ComplianceCaseID,
		arg.ObservedBlock,
		arg.DailyKey,
	)
	var i RwaReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ChainSupply,
		&i.LockedShares,
		&i.Difference,
		&i.Status,
		&i.ComplianceCaseID,
		&i.ObservedBlock,
		&i.DailyKey,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertStateEvent = `-- name: InsertStateEvent :one
INSERT INTO rwa.state_events (
    resource_type, resource_id, from_status, to_status, actor_type, actor_id, reason_code, metadata
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
RETURNING id, resource_type, resource_id, from_status, to_status, actor_type, actor_id, reason_code, metadata, occurred_at
`

type InsertStateEventParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	FromStatus   pgtype.Text `json:"from_status"`
	ToStatus     string      `json:"to_status"`
	ActorType    string      `json:"actor_type"`
	ActorID      string      `json:"actor_id"`
	ReasonCode   pgtype.Text `json:"reason_code"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) InsertStateEvent(ctx context.Context, arg InsertStateEventParams) (RwaStateEvent, error) {
	row := q.db.QueryRow(ctx, insertStateEvent,
		arg.ResourceType,
		arg.ResourceID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorType,
		arg.ActorID,
		arg.ReasonCode,
		arg.Metadata,
	)
	var i RwaStateEvent
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorType,
		&i.ActorID,
		&i.ReasonCode,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, instrument_id, underlying_symbol, token_name, token_symbol, token_decimals, contract_address, platform_vault_address, enabled, simulation_disclaimer, policy_version, created_at FROM rwa.assets WHERE enabled ORDER BY underlying_symbol
`

func (q *Queries) ListAssets(ctx context.Context) ([]RwaAsset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaAsset
	for rows.Next() {
		var i RwaAsset
		if err := rows.Scan(
			&i.ID,
			&i.InstrumentID,
			&i.UnderlyingSymbol,
			&i.TokenName,
			&i.TokenSymbol,
			&i.TokenDecimals,
			&i.ContractAddress,
			&i.PlatformVaultAddress,
			&i.Enabled,
			&i.SimulationDisclaimer,
			&i.PolicyVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeneficialHoldings = `-- name: ListBeneficialHoldings :many
SELECT customer_reference, asset_id, custody_mode, destination_address, quantity, updated_at, version FROM rwa.beneficial_holdings
WHERE customer_reference = $1 AND quantity > 0
ORDER BY asset_id
`

func (q *Queries) ListBeneficialHoldings(ctx context.Context, customerReference string) ([]RwaBeneficialHolding, error) {
	rows, err := q.db.Query(ctx, listBeneficialHoldings, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaBeneficialHolding
	for rows.Next() {
		var i RwaBeneficialHolding
		if err := rows.Scan(
			&i.CustomerReference,
			&i.AssetID,
			&i.CustodyMode,
			&i.DestinationAddress,
			&i.Quantity,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDividendEntitlements = `-- name: ListDividendEntitlements :many
SELECT id, dividend_id, customer_reference, whole_shares, gross_usd, withholding_usd, net_usd, cash_ledger_transaction_id, status, created_at, updated_at FROM rwa.dividend_entitlements
WHERE dividend_id = $1
ORDER BY customer_reference
`

func (q *Queries) ListDividendEntitlements(ctx context.Context, dividendID pgtype.UUID) ([]RwaDividendEntitlement, error) {
	rows, err := q.db.Query(ctx, listDividendEntitlements, dividendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaDividendEntitlement
	for rows.Next() {
		var i RwaDividendEntitlement
		if err := rows.Scan(
			&i.ID,
			&i.DividendID,
			&i.CustomerReference,
			&i.WholeShares,
			&i.GrossUsd,
			&i.WithholdingUsd,
			&i.NetUsd,
			&i.CashLedgerTransactionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalAddresses = `-- name: ListExternalAddresses :many
SELECT id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version FROM rwa.external_addresses
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListExternalAddresses(ctx context.Context, customerReference string) ([]RwaExternalAddress, error) {
	rows, err := q.db.Query(ctx, listExternalAddresses, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaExternalAddress
	for rows.Next() {
		var i RwaExternalAddress
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.Address,
			&i.Status,
			&i.ProofReference,
			&i.ProofVerifiedAt,
			&i.RiskReasonCode,
			&i.RiskReviewedAt,
			&i.CoolingEndsAt,
			&i.ActivatedAt,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMintRequests = `-- name: ListMintRequests :many
SELECT id, customer_reference, asset_id, underlying_lock_id, quantity, custody_mode, destination_address_id, destination_address, operation_id, status, chain_tx_hash, failure_code, created_at, updated_at, version FROM rwa.mint_requests
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListMintRequests(ctx context.Context, customerReference string) ([]RwaMintRequest, error) {
	rows, err := q.db.Query(ctx, listMintRequests, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaMintRequest
	for rows.Next() {
		var i RwaMintRequest
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.AssetID,
			&i.UnderlyingLockID,
			&i.Quantity,
			&i.CustodyMode,
			&i.DestinationAddressID,
			&i.DestinationAddress,
			&i.OperationID,
			&i.Status,
			&i.ChainTxHash,
			&i.FailureCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositiveHoldingsForAsset = `-- name: ListPositiveHoldingsForAsset :many
SELECT customer_reference, asset_id, custody_mode, destination_address, quantity, updated_at, version FROM rwa.beneficial_holdings
WHERE asset_id = $1 AND quantity > 0
ORDER BY customer_reference
`

func (q *Queries) ListPositiveHoldingsForAsset(ctx context.Context, assetID pgtype.UUID) ([]RwaBeneficialHolding, error) {
	rows, err := q.db.Query(ctx, listPositiveHoldingsForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaBeneficialHolding
	for rows.Next() {
		var i RwaBeneficialHolding
		if err := rows.Scan(
			&i.CustomerReference,
			&i.AssetID,
			&i.CustodyMode,
			&i.DestinationAddress,
			&i.Quantity,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationRuns = `-- name: ListReconciliationRuns :many
SELECT id, asset_id, chain_supply, locked_shares, difference, status, compliance_case_id, observed_block, daily_key, started_at, completed_at FROM rwa.reconciliation_runs
WHERE asset_id = $1
ORDER BY started_at DESC, id DESC
LIMIT $2
`

type ListReconciliationRunsParams struct {
	AssetID  pgtype.UUID `json:"asset_id"`
	PageSize int32       `json:"page_size"`
}

func (q *Queries) ListReconciliationRuns(ctx context.Context, arg ListReconciliationRunsParams) ([]RwaReconciliationRun, error) {
	rows, err := q.db.Query(ctx, listReconciliationRuns, arg.AssetID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaReconciliationRun
	for rows.Next() {
		var i RwaReconciliationRun
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.ChainSupply,
			&i.LockedShares,
			&i.Difference,
			&i.Status,
			&i.ComplianceCaseID,
			&i.ObservedBlock,
			&i.DailyKey,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedemptionRequests = `-- name: ListRedemptionRequests :many
SELECT id, customer_reference, asset_id, underlying_lock_id, quantity, source_address, operation_id, forced, status, chain_tx_hash, failure_code, created_at, updated_at, completed_at, version FROM rwa.redemption_requests
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListRedemptionRequests(ctx context.Context, customerReference string) ([]RwaRedemptionRequest, error) {
	rows, err := q.db.Query(ctx, listRedemptionRequests, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RwaRedemptionRequest
	for rows.Next() {
		var i RwaRedemptionRequest
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.AssetID,
			&i.UnderlyingLockID,
			&i.Quantity,
			&i.SourceAddress,
			&i.OperationID,
			&i.Forced,
			&i.Status,
			&i.ChainTxHash,
			&i.FailureCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAddressCooling = `-- name: MarkAddressCooling :one
UPDATE rwa.external_addresses
SET status = 'COOLING', risk_reason_code = $1,
    risk_reviewed_at = clock_timestamp(), cooling_ends_at = $2,
    updated_at = clock_timestamp(), version = version + 1
WHERE id = $3 AND status = 'RISK_REVIEW'
RETURNING id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version
`

type MarkAddressCoolingParams struct {
	RiskReasonCode pgtype.Text        `json:"risk_reason_code"`
	CoolingEndsAt  pgtype.Timestamptz `json:"cooling_ends_at"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkAddressCooling(ctx context.Context, arg MarkAddressCoolingParams) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, markAddressCooling, arg.RiskReasonCode, arg.CoolingEndsAt, arg.ID)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const markAddressProofVerified = `-- name: MarkAddressProofVerified :one
UPDATE rwa.external_addresses
SET status = 'PROOF_VERIFIED', proof_reference = $1,
    proof_verified_at = clock_timestamp(), updated_at = clock_timestamp(), version = version + 1
WHERE id = $2 AND status = 'PENDING_PROOF'
RETURNING id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version
`

type MarkAddressProofVerifiedParams struct {
	ProofReference pgtype.Text `json:"proof_reference"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) MarkAddressProofVerified(ctx context.Context, arg MarkAddressProofVerifiedParams) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, markAddressProofVerified, arg.ProofReference, arg.ID)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const markAddressRiskReview = `-- name: MarkAddressRiskReview :one
UPDATE rwa.external_addresses
SET status = 'RISK_REVIEW', updated_at = clock_timestamp(), version = version + 1
WHERE id = $1 AND status = 'PROOF_VERIFIED'
RETURNING id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version
`

func (q *Queries) MarkAddressRiskReview(ctx context.Context, id pgtype.UUID) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, markAddressRiskReview, id)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const markDividendEntitlementCredited = `-- name: MarkDividendEntitlementCredited :one
UPDATE rwa.dividend_entitlements
SET status = 'USD_CASH_CREDITED', cash_ledger_transaction_id = $1,
    updated_at = clock_timestamp()
WHERE id = $2 AND status = 'CALCULATED'
RETURNING id, dividend_id, customer_reference, whole_shares, gross_usd, withholding_usd, net_usd, cash_ledger_transaction_id, status, created_at, updated_at
`

type MarkDividendEntitlementCreditedParams struct {
	CashLedgerTransactionID pgtype.UUID `json:"cash_ledger_transaction_id"`
	ID                      pgtype.UUID `json:"id"`
}

func (q *Queries) MarkDividendEntitlementCredited(ctx context.Context, arg MarkDividendEntitlementCreditedParams) (RwaDividendEntitlement, error) {
	row := q.db.QueryRow(ctx, markDividendEntitlementCredited, arg.CashLedgerTransactionID, arg.ID)
	var i RwaDividendEntitlement
	err := row.Scan(
		&i.ID,
		&i.DividendID,
		&i.CustomerReference,
		&i.WholeShares,
		&i.GrossUsd,
		&i.WithholdingUsd,
		&i.NetUsd,
		&i.CashLedgerTransactionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveExhaustedOperationsToDLQ = `-- name: MoveExhaustedOperationsToDLQ :execrows
UPDATE rwa.chain_operations
SET status = 'DLQ', claimed_at = NULL, claimed_by = NULL, updated_at = clock_timestamp()
WHERE status IN ('PENDING', 'UNKNOWN', 'FAILED') AND attempt_count >= max_attempts
`

func (q *Queries) MoveExhaustedOperationsToDLQ(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, moveExhaustedOperationsToDLQ)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reduceBeneficialHolding = `-- name: ReduceBeneficialHolding :one
UPDATE rwa.beneficial_holdings
SET quantity = quantity - $1, updated_at = clock_timestamp(), version = version + 1
WHERE customer_reference = $2
  AND asset_id = $3
  AND quantity >= $1
RETURNING customer_reference, asset_id, custody_mode, destination_address, quantity, updated_at, version
`

type ReduceBeneficialHoldingParams struct {
	Quantity          money.Decimal `json:"quantity"`
	CustomerReference string        `json:"customer_reference"`
	AssetID           pgtype.UUID   `json:"asset_id"`
}

func (q *Queries) ReduceBeneficialHolding(ctx context.Context, arg ReduceBeneficialHoldingParams) (RwaBeneficialHolding, error) {
	row := q.db.QueryRow(ctx, reduceBeneficialHolding, arg.Quantity, arg.CustomerReference, arg.AssetID)
	var i RwaBeneficialHolding
	err := row.Scan(
		&i.CustomerReference,
		&i.AssetID,
		&i.CustodyMode,
		&i.DestinationAddress,
		&i.Quantity,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const rejectExternalAddress = `-- name: RejectExternalAddress :one
UPDATE rwa.external_addresses
SET status = 'REJECTED', risk_reason_code = $1,
    risk_reviewed_at = clock_timestamp(), updated_at = clock_timestamp(), version = version + 1
WHERE id = $2 AND status = 'RISK_REVIEW'
RETURNING id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version
`

type RejectExternalAddressParams struct {
	RiskReasonCode pgtype.Text `json:"risk_reason_code"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) RejectExternalAddress(ctx context.Context, arg RejectExternalAddressParams) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, rejectExternalAddress, arg.RiskReasonCode, arg.ID)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const releaseUnderlyingLock = `-- name: ReleaseUnderlyingLock :one
UPDATE rwa.underlying_locks
SET status = 'RELEASED', released_at = clock_timestamp(), version = version + 1
WHERE id = $1 AND status = 'LOCKED'
RETURNING id, customer_reference, asset_id, reservation_id, quantity, status, created_at, released_at, version
`

func (q *Queries) ReleaseUnderlyingLock(ctx context.Context, id pgtype.UUID) (RwaUnderlyingLock, error) {
	row := q.db.QueryRow(ctx, releaseUnderlyingLock, id)
	var i RwaUnderlyingLock
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.ReservationID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Version,
	)
	return i, err
}

const sumLockedSharesByAsset = `-- name: SumLockedSharesByAsset :one
SELECT COALESCE(sum(quantity), 0)::numeric AS quantity
FROM rwa.underlying_locks
WHERE asset_id = $1 AND status = 'LOCKED'
`

func (q *Queries) SumLockedSharesByAsset(ctx context.Context, assetID pgtype.UUID) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumLockedSharesByAsset, assetID)
	var quantity money.Decimal
	err := row.Scan(&quantity)
	return quantity, err
}

const suspendExternalAddress = `-- name: SuspendExternalAddress :one
UPDATE rwa.external_addresses
SET status = 'SUSPENDED', suspended_at = clock_timestamp(), activated_at = NULL,
    updated_at = clock_timestamp(), version = version + 1
WHERE id = $1 AND status = 'ACTIVE'
RETURNING id, customer_reference, address, status, proof_reference, proof_verified_at, risk_reason_code, risk_reviewed_at, cooling_ends_at, activated_at, suspended_at, created_at, updated_at, version
`

func (q *Queries) SuspendExternalAddress(ctx context.Context, id pgtype.UUID) (RwaExternalAddress, error) {
	row := q.db.QueryRow(ctx, suspendExternalAddress, id)
	var i RwaExternalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Address,
		&i.Status,
		&i.ProofReference,
		&i.ProofVerifiedAt,
		&i.RiskReasonCode,
		&i.RiskReviewedAt,
		&i.CoolingEndsAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateChainOperation = `-- name: UpdateChainOperation :one
UPDATE rwa.chain_operations
SET status = $1, tx_hash = $2,
    attempt_count = attempt_count + 1, last_error_code = $3,
    next_attempt_at = $4, claimed_at = NULL, claimed_by = NULL,
    updated_at = clock_timestamp()
WHERE operation_id = $5
RETURNING operation_id, resource_type, resource_id, operation_type, status, tx_hash, attempt_count, max_attempts, next_attempt_at, last_error_code, claimed_at, claimed_by, created_at, updated_at
`

type UpdateChainOperationParams struct {
	Status        string             `json:"status"`
	TxHash        pgtype.Text        `json:"tx_hash"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	OperationID   string             `json:"operation_id"`
}

func (q *Queries) UpdateChainOperation(ctx context.Context, arg UpdateChainOperationParams) (RwaChainOperation, error) {
	row := q.db.QueryRow(ctx, updateChainOperation,
		arg.Status,
		arg.TxHash,
		arg.LastErrorCode,
		arg.NextAttemptAt,
		arg.OperationID,
	)
	var i RwaChainOperation
	err := row.Scan(
		&i.OperationID,
		&i.ResourceType,
		&i.ResourceID,
		&i.OperationType,
		&i.Status,
		&i.TxHash,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDividendStatus = `-- name: UpdateDividendStatus :one
UPDATE rwa.dividends
SET status = $1, updated_at = clock_timestamp(), version = version + 1
WHERE id = $2
RETURNING id, asset_id, external_reference, usd_per_share, record_at, payable_at, status, policy_version, created_at, updated_at, version
`

type UpdateDividendStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDividendStatus(ctx context.Context, arg UpdateDividendStatusParams) (RwaDividend, error) {
	row := q.db.QueryRow(ctx, updateDividendStatus, arg.Status, arg.ID)
	var i RwaDividend
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ExternalReference,
		&i.UsdPerShare,
		&i.RecordAt,
		&i.PayableAt,
		&i.Status,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateMintState = `-- name: UpdateMintState :one
UPDATE rwa.mint_requests
SET status = $1, chain_tx_hash = $2,
    failure_code = $3, updated_at = clock_timestamp(), version = version + 1
WHERE id = $4
RETURNING id, customer_reference, asset_id, underlying_lock_id, quantity, custody_mode, destination_address_id, destination_address, operation_id, status, chain_tx_hash, failure_code, created_at, updated_at, version
`

type UpdateMintStateParams struct {
	Status      string      `json:"status"`
	ChainTxHash pgtype.Text `json:"chain_tx_hash"`
	FailureCode pgtype.Text `json:"failure_code"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMintState(ctx context.Context, arg UpdateMintStateParams) (RwaMintRequest, error) {
	row := q.db.QueryRow(ctx, updateMintState,
		arg.Status,
		arg.ChainTxHash,
		arg.FailureCode,
		arg.ID,
	)
	var i RwaMintRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.CustodyMode,
		&i.DestinationAddressID,
		&i.DestinationAddress,
		&i.OperationID,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateRedemptionState = `-- name: UpdateRedemptionState :one
UPDATE rwa.redemption_requests
SET status = $1, chain_tx_hash = $2,
    failure_code = $3,
    completed_at = CASE WHEN $1::text = 'COMPLETED' THEN clock_timestamp() ELSE NULL END,
    updated_at = clock_timestamp(), version = version + 1
WHERE id = $4
RETURNING id, customer_reference, asset_id, underlying_lock_id, quantity, source_address, operation_id, forced, status, chain_tx_hash, failure_code, created_at, updated_at, completed_at, version
`

type UpdateRedemptionStateParams struct {
	Status      string      `json:"status"`
	ChainTxHash pgtype.Text `json:"chain_tx_hash"`
	FailureCode pgtype.Text `json:"failure_code"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRedemptionState(ctx context.Context, arg UpdateRedemptionStateParams) (RwaRedemptionRequest, error) {
	row := q.db.QueryRow(ctx, updateRedemptionState,
		arg.Status,
		arg.ChainTxHash,
		arg.FailureCode,
		arg.ID,
	)
	var i RwaRedemptionRequest
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetID,
		&i.UnderlyingLockID,
		&i.Quantity,
		&i.SourceAddress,
		&i.OperationID,
		&i.Forced,
		&i.Status,
		&i.ChainTxHash,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Version,
	)
	return i, err
}

const upsertBeneficialHolding = `-- name: UpsertBeneficialHolding :one
INSERT INTO rwa.beneficial_holdings (
    customer_reference, asset_id, custody_mode, destination_address, quantity
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (customer_reference, asset_id) DO UPDATE
SET quantity = rwa.beneficial_holdings.quantity + EXCLUDED.quantity,
    custody_mode = EXCLUDED.custody_mode,
    destination_address = EXCLUDED.destination_address,
    updated_at = clock_timestamp(), version = rwa.beneficial_holdings.version + 1
RETURNING customer_reference, asset_id, custody_mode, destination_address, quantity, updated_at, version
`

type UpsertBeneficialHoldingParams struct {
	CustomerReference  string        `json:"customer_reference"`
	AssetID            pgtype.UUID   `json:"asset_id"`
	CustodyMode        string        `json:"custody_mode"`
	DestinationAddress string        `json:"destination_address"`
	Quantity           money.Decimal `json:"quantity"`
}

func (q *Queries) UpsertBeneficialHolding(ctx context.Context, arg UpsertBeneficialHoldingParams) (RwaBeneficialHolding, error) {
	row := q.db.QueryRow(ctx, upsertBeneficialHolding,
		arg.CustomerReference,
		arg.AssetID,
		arg.CustodyMode,
		arg.DestinationAddress,
		arg.Quantity,
	)
	var i RwaBeneficialHolding
	err := row.Scan(
		&i.CustomerReference,
		&i.AssetID,
		&i.CustodyMode,
		&i.DestinationAddress,
		&i.Quantity,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
