// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banking.sql

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearBankAccountFunding = `-- name: ClearBankAccountFunding :one
UPDATE banking.bank_accounts
SET successfully_funded_at = NULL
WHERE id = $1
RETURNING id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
`

func (q *Queries) ClearBankAccountFunding(ctx context.Context, id pgtype.UUID) (BankingBankAccount, error) {
	row := q.db.QueryRow(ctx, clearBankAccountFunding, id)
	var i BankingBankAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Provider,
		&i.ExternalAccountReference,
		&i.RailSupport,
		&i.OwnerRelation,
		&i.OwnershipStatus,
		&i.Status,
		&i.RiskClass,
		&i.SuccessfullyFundedAt,
		&i.CoolingUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const completeReconciliationRun = `-- name: CompleteReconciliationRun :one
UPDATE banking.reconciliation_runs
SET status = $1,
    completed_at = clock_timestamp()
WHERE id = $2
  AND status = 'RUNNING'
RETURNING id, scope, status, policy_version, started_at, completed_at
`

type CompleteReconciliationRunParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) CompleteReconciliationRun(ctx context.Context, arg CompleteReconciliationRunParams) (BankingReconciliationRun, error) {
	row := q.db.QueryRow(ctx, completeReconciliationRun, arg.Status, arg.ID)
	var i BankingReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Status,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO banking.bank_accounts (
    id,
    customer_reference,
    provider,
    external_account_reference,
    rail_support,
    owner_relation,
    ownership_status,
    status,
    risk_class,
    cooling_until,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (customer_reference, provider, external_account_reference) DO NOTHING
RETURNING id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
`

type CreateBankAccountParams struct {
	ID                       pgtype.UUID        `json:"id"`
	CustomerReference        string             `json:"customer_reference"`
	Provider                 string             `json:"provider"`
	ExternalAccountReference string             `json:"external_account_reference"`
	RailSupport              string             `json:"rail_support"`
	OwnerRelation            string             `json:"owner_relation"`
	OwnershipStatus          string             `json:"ownership_status"`
	Status                   string             `json:"status"`
	RiskClass                string             `json:"risk_class"`
	CoolingUntil             pgtype.Timestamptz `json:"cooling_until"`
	PolicyVersion            string             `json:"policy_version"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankingBankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.ID,
		arg.CustomerReference,
		arg.Provider,
		arg.ExternalAccountReference,
		arg.RailSupport,
		arg.OwnerRelation,
		arg.OwnershipStatus,
		arg.Status,
		arg.RiskClass,
		arg.CoolingUntil,
		arg.PolicyVersion,
	)
	var i BankingBankAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Provider,
		&i.ExternalAccountReference,
		&i.RailSupport,
		&i.OwnerRelation,
		&i.OwnershipStatus,
		&i.Status,
		&i.RiskClass,
		&i.SuccessfullyFundedAt,
		&i.CoolingUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createCustomerProfile = `-- name: CreateCustomerProfile :one
INSERT INTO banking.customer_profiles (
    customer_reference,
    paper_account_id,
    cash_ledger_account_id,
    provider_clearing_ledger_account_id,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (customer_reference) DO NOTHING
RETURNING customer_reference, paper_account_id, cash_ledger_account_id, provider_clearing_ledger_account_id, policy_version, created_at
`

type CreateCustomerProfileParams struct {
	CustomerReference               string      `json:"customer_reference"`
	PaperAccountID                  pgtype.UUID `json:"paper_account_id"`
	CashLedgerAccountID             pgtype.UUID `json:"cash_ledger_account_id"`
	ProviderClearingLedgerAccountID pgtype.UUID `json:"provider_clearing_ledger_account_id"`
	PolicyVersion                   string      `json:"policy_version"`
}

func (q *Queries) CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (BankingCustomerProfile, error) {
	row := q.db.QueryRow(ctx, createCustomerProfile,
		arg.CustomerReference,
		arg.PaperAccountID,
		arg.CashLedgerAccountID,
		arg.ProviderClearingLedgerAccountID,
		arg.PolicyVersion,
	)
	var i BankingCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.PolicyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createFundingTransfer = `-- name: CreateFundingTransfer :one
INSERT INTO banking.funding_transfers (
    id,
    customer_reference,
    bank_account_id,
    rail,
    amount,
    status,
    provider,
    provider_transfer_id,
    pending_ledger_transaction_id,
    reason_code,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, customer_reference, bank_account_id, rail, amount, status, provider, provider_transfer_id, pending_ledger_transaction_id, pending_release_transaction_id, settled_ledger_transaction_id, return_reversal_transaction_id, reason_code, policy_version, created_at, updated_at, version
`

type CreateFundingTransferParams struct {
	ID                         pgtype.UUID   `json:"id"`
	CustomerReference          string        `json:"customer_reference"`
	BankAccountID              pgtype.UUID   `json:"bank_account_id"`
	Rail                       string        `json:"rail"`
	Amount                     money.Decimal `json:"amount"`
	Status                     string        `json:"status"`
	Provider                   string        `json:"provider"`
	ProviderTransferID         string        `json:"provider_transfer_id"`
	PendingLedgerTransactionID pgtype.UUID   `json:"pending_ledger_transaction_id"`
	ReasonCode                 pgtype.Text   `json:"reason_code"`
	PolicyVersion              string        `json:"policy_version"`
}

func (q *Queries) CreateFundingTransfer(ctx context.Context, arg CreateFundingTransferParams) (BankingFundingTransfer, error) {
	row := q.db.QueryRow(ctx, createFundingTransfer,
		arg.ID,
		arg.CustomerReference,
		arg.BankAccountID,
		arg.Rail,
		arg.Amount,
		arg.Status,
		arg.Provider,
		arg.ProviderTransferID,
		arg.PendingLedgerTransactionID,
		arg.ReasonCode,
		arg.PolicyVersion,
	)
	var i BankingFundingTransfer
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Rail,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PendingLedgerTransactionID,
		&i.PendingReleaseTransactionID,
		&i.SettledLedgerTransactionID,
		&i.ReturnReversalTransactionID,
		&i.ReasonCode,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createReconciliationRun = `-- name: CreateReconciliationRun :one
INSERT INTO banking.reconciliation_runs (
    id,
    scope,
    policy_version
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, scope, status, policy_version, started_at, completed_at
`

type CreateReconciliationRunParams struct {
	ID            pgtype.UUID `json:"id"`
	Scope         string      `json:"scope"`
	PolicyVersion string      `json:"policy_version"`
}

func (q *Queries) CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (BankingReconciliationRun, error) {
	row := q.db.QueryRow(ctx, createReconciliationRun, arg.ID, arg.Scope, arg.PolicyVersion)
	var i BankingReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Status,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO banking.withdrawals (
    id,
    customer_reference,
    bank_account_id,
    amount,
    status,
    reason_code,
    next_action,
    compliance_case_id,
    cooling_until,
    reservation_ledger_transaction_id,
    provider,
    provider_transfer_id,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, customer_reference, bank_account_id, amount, status, reason_code, next_action, compliance_case_id, cooling_until, reservation_ledger_transaction_id, submitted_ledger_transaction_id, return_reservation_reversal_id, return_submitted_reversal_id, provider, provider_transfer_id, policy_version, created_at, updated_at, version
`

type CreateWithdrawalParams struct {
	ID                             pgtype.UUID        `json:"id"`
	CustomerReference              string             `json:"customer_reference"`
	BankAccountID                  pgtype.UUID        `json:"bank_account_id"`
	Amount                         money.Decimal      `json:"amount"`
	Status                         string             `json:"status"`
	ReasonCode                     string             `json:"reason_code"`
	NextAction                     string             `json:"next_action"`
	ComplianceCaseID               pgtype.UUID        `json:"compliance_case_id"`
	CoolingUntil                   pgtype.Timestamptz `json:"cooling_until"`
	ReservationLedgerTransactionID pgtype.UUID        `json:"reservation_ledger_transaction_id"`
	Provider                       string             `json:"provider"`
	ProviderTransferID             string             `json:"provider_transfer_id"`
	PolicyVersion                  string             `json:"policy_version"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (BankingWithdrawal, error) {
	row := q.db.QueryRow(ctx, createWithdrawal,
		arg.ID,
		arg.CustomerReference,
		arg.BankAccountID,
		arg.Amount,
		arg.Status,
		arg.ReasonCode,
		arg.NextAction,
		arg.ComplianceCaseID,
		arg.CoolingUntil,
		arg.ReservationLedgerTransactionID,
		arg.Provider,
		arg.ProviderTransferID,
		arg.PolicyVersion,
	)
	var i BankingWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Amount,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.ComplianceCaseID,
		&i.CoolingUntil,
		&i.ReservationLedgerTransactionID,
		&i.SubmittedLedgerTransactionID,
		&i.ReturnReservationReversalID,
		&i.ReturnSubmittedReversalID,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
FROM banking.bank_accounts
WHERE id = $1
`

func (q *Queries) GetBankAccount(ctx context.Context, id pgtype.UUID) (BankingBankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccount, id)
	var i BankingBankAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Provider,
		&i.ExternalAccountReference,
		&i.RailSupport,
		&i.OwnerRelation,
		&i.OwnershipStatus,
		&i.Status,
		&i.RiskClass,
		&i.SuccessfullyFundedAt,
		&i.CoolingUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getBankAccountByExternalReference = `-- name: GetBankAccountByExternalReference :one
SELECT id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
FROM banking.bank_accounts
WHERE customer_reference = $1
  AND provider = $2
  AND external_account_reference = $3
`

type GetBankAccountByExternalReferenceParams struct {
	CustomerReference        string `json:"customer_reference"`
	Provider                 string `json:"provider"`
	ExternalAccountReference string `json:"external_account_reference"`
}

func (q *Queries) GetBankAccountByExternalReference(ctx context.Context, arg GetBankAccountByExternalReferenceParams) (BankingBankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccountByExternalReference, arg.CustomerReference, arg.Provider, arg.ExternalAccountReference)
	var i BankingBankAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Provider,
		&i.ExternalAccountReference,
		&i.RailSupport,
		&i.OwnerRelation,
		&i.OwnershipStatus,
		&i.Status,
		&i.RiskClass,
		&i.SuccessfullyFundedAt,
		&i.CoolingUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getBankAccountForUpdate = `-- name: GetBankAccountForUpdate :one
SELECT id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
FROM banking.bank_accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetBankAccountForUpdate(ctx context.Context, id pgtype.UUID) (BankingBankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccountForUpdate, id)
	var i BankingBankAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Provider,
		&i.ExternalAccountReference,
		&i.RailSupport,
		&i.OwnerRelation,
		&i.OwnershipStatus,
		&i.Status,
		&i.RiskClass,
		&i.SuccessfullyFundedAt,
		&i.CoolingUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerProfile = `-- name: GetCustomerProfile :one
SELECT customer_reference, paper_account_id, cash_ledger_account_id, provider_clearing_ledger_account_id, policy_version, created_at
FROM banking.customer_profiles
WHERE customer_reference = $1
`

func (q *Queries) GetCustomerProfile(ctx context.Context, customerReference string) (BankingCustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfile, customerReference)
	var i BankingCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.PolicyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerProfileForUpdate = `-- name: GetCustomerProfileForUpdate :one
SELECT customer_reference, paper_account_id, cash_ledger_account_id, provider_clearing_ledger_account_id, policy_version, created_at
FROM banking.customer_profiles
WHERE customer_reference = $1
FOR UPDATE
`

func (q *Queries) GetCustomerProfileForUpdate(ctx context.Context, customerReference string) (BankingCustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfileForUpdate, customerReference)
	var i BankingCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.ProviderClearingLedgerAccountID,
		&i.PolicyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getFundingRequest = `-- name: GetFundingRequest :one
SELECT customer_reference, idempotency_key, request_hash, transfer_id, created_at
FROM banking.funding_requests
WHERE customer_reference = $1
  AND idempotency_key = $2
`

type GetFundingRequestParams struct {
	CustomerReference string `json:"customer_reference"`
	IdempotencyKey    string `json:"idempotency_key"`
}

func (q *Queries) GetFundingRequest(ctx context.Context, arg GetFundingRequestParams) (BankingFundingRequest, error) {
	row := q.db.QueryRow(ctx, getFundingRequest, arg.CustomerReference, arg.IdempotencyKey)
	var i BankingFundingRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.TransferID,
		&i.CreatedAt,
	)
	return i, err
}

const getFundingTransfer = `-- name: GetFundingTransfer :one
SELECT id, customer_reference, bank_account_id, rail, amount, status, provider, provider_transfer_id, pending_ledger_transaction_id, pending_release_transaction_id, settled_ledger_transaction_id, return_reversal_transaction_id, reason_code, policy_version, created_at, updated_at, version
FROM banking.funding_transfers
WHERE id = $1
`

func (q *Queries) GetFundingTransfer(ctx context.Context, id pgtype.UUID) (BankingFundingTransfer, error) {
	row := q.db.QueryRow(ctx, getFundingTransfer, id)
	var i BankingFundingTransfer
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Rail,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PendingLedgerTransactionID,
		&i.PendingReleaseTransactionID,
		&i.SettledLedgerTransactionID,
		&i.ReturnReversalTransactionID,
		&i.ReasonCode,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getFundingTransferForUpdate = `-- name: GetFundingTransferForUpdate :one
SELECT id, customer_reference, bank_account_id, rail, amount, status, provider, provider_transfer_id, pending_ledger_transaction_id, pending_release_transaction_id, settled_ledger_transaction_id, return_reversal_transaction_id, reason_code, policy_version, created_at, updated_at, version
FROM banking.funding_transfers
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetFundingTransferForUpdate(ctx context.Context, id pgtype.UUID) (BankingFundingTransfer, error) {
	row := q.db.QueryRow(ctx, getFundingTransferForUpdate, id)
	var i BankingFundingTransfer
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Rail,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PendingLedgerTransactionID,
		&i.PendingReleaseTransactionID,
		&i.SettledLedgerTransactionID,
		&i.ReturnReversalTransactionID,
		&i.ReasonCode,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPreferredWithdrawalAccount = `-- name: GetPreferredWithdrawalAccount :one
SELECT id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
FROM banking.bank_accounts
WHERE customer_reference = $1
  AND owner_relation = 'SAME_NAME'
  AND ownership_status = 'VERIFIED'
  AND status = 'ACTIVE'
  AND successfully_funded_at IS NOT NULL
ORDER BY successfully_funded_at DESC, created_at
LIMIT 1
`

func (q *Queries) GetPreferredWithdrawalAccount(ctx context.Context, customerReference string) (BankingBankAccount, error) {
	row := q.db.QueryRow(ctx, getPreferredWithdrawalAccount, customerReference)
	var i BankingBankAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Provider,
		&i.ExternalAccountReference,
		&i.RailSupport,
		&i.OwnerRelation,
		&i.OwnershipStatus,
		&i.Status,
		&i.RiskClass,
		&i.SuccessfullyFundedAt,
		&i.CoolingUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getProviderEvent = `-- name: GetProviderEvent :one
SELECT provider, external_event_id, resource_type, resource_id, event_type, payload_hash, ledger_transaction_id, processed_at
FROM banking.provider_events
WHERE provider = $1
  AND external_event_id = $2
`

type GetProviderEventParams struct {
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (BankingProviderEvent, error) {
	row := q.db.QueryRow(ctx, getProviderEvent, arg.Provider, arg.ExternalEventID)
	var i BankingProviderEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.ResourceType,
		&i.ResourceID,
		&i.EventType,
		&i.PayloadHash,
		&i.LedgerTransactionID,
		&i.ProcessedAt,
	)
	return i, err
}

const getWithdrawal = `-- name: GetWithdrawal :one
SELECT id, customer_reference, bank_account_id, amount, status, reason_code, next_action, compliance_case_id, cooling_until, reservation_ledger_transaction_id, submitted_ledger_transaction_id, return_reservation_reversal_id, return_submitted_reversal_id, provider, provider_transfer_id, policy_version, created_at, updated_at, version
FROM banking.withdrawals
WHERE id = $1
`

func (q *Queries) GetWithdrawal(ctx context.Context, id pgtype.UUID) (BankingWithdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawal, id)
	var i BankingWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Amount,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.ComplianceCaseID,
		&i.CoolingUntil,
		&i.ReservationLedgerTransactionID,
		&i.SubmittedLedgerTransactionID,
		&i.ReturnReservationReversalID,
		&i.ReturnSubmittedReversalID,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getWithdrawalByCaseForUpdate = `-- name: GetWithdrawalByCaseForUpdate :one
SELECT id, customer_reference, bank_account_id, amount, status, reason_code, next_action, compliance_case_id, cooling_until, reservation_ledger_transaction_id, submitted_ledger_transaction_id, return_reservation_reversal_id, return_submitted_reversal_id, provider, provider_transfer_id, policy_version, created_at, updated_at, version
FROM banking.withdrawals
WHERE compliance_case_id = $1
FOR UPDATE
`

func (q *Queries) GetWithdrawalByCaseForUpdate(ctx context.Context, complianceCaseID pgtype.UUID) (BankingWithdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawalByCaseForUpdate, complianceCaseID)
	var i BankingWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Amount,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.ComplianceCaseID,
		&i.CoolingUntil,
		&i.ReservationLedgerTransactionID,
		&i.SubmittedLedgerTransactionID,
		&i.ReturnReservationReversalID,
		&i.ReturnSubmittedReversalID,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getWithdrawalForUpdate = `-- name: GetWithdrawalForUpdate :one
SELECT id, customer_reference, bank_account_id, amount, status, reason_code, next_action, compliance_case_id, cooling_until, reservation_ledger_transaction_id, submitted_ledger_transaction_id, return_reservation_reversal_id, return_submitted_reversal_id, provider, provider_transfer_id, policy_version, created_at, updated_at, version
FROM banking.withdrawals
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetWithdrawalForUpdate(ctx context.Context, id pgtype.UUID) (BankingWithdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawalForUpdate, id)
	var i BankingWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Amount,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.ComplianceCaseID,
		&i.CoolingUntil,
		&i.ReservationLedgerTransactionID,
		&i.SubmittedLedgerTransactionID,
		&i.ReturnReservationReversalID,
		&i.ReturnSubmittedReversalID,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getWithdrawalRequest = `-- name: GetWithdrawalRequest :one
SELECT customer_reference, idempotency_key, request_hash, withdrawal_id, created_at
FROM banking.withdrawal_requests
WHERE customer_reference = $1
  AND idempotency_key = $2
`

type GetWithdrawalRequestParams struct {
	CustomerReference string `json:"customer_reference"`
	IdempotencyKey    string `json:"idempotency_key"`
}

func (q *Queries) GetWithdrawalRequest(ctx context.Context, arg GetWithdrawalRequestParams) (BankingWithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, getWithdrawalRequest, arg.CustomerReference, arg.IdempotencyKey)
	var i BankingWithdrawalRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.WithdrawalID,
		&i.CreatedAt,
	)
	return i, err
}

const insertBankAccountEvent = `-- name: InsertBankAccountEvent :one
INSERT INTO banking.bank_account_events (
    bank_account_id,
    event_type,
    actor_type,
    actor_id,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, bank_account_id, event_type, actor_type, actor_id, metadata, occurred_at
`

type InsertBankAccountEventParams struct {
	BankAccountID pgtype.UUID `json:"bank_account_id"`
	EventType     string      `json:"event_type"`
	ActorType     string      `json:"actor_type"`
	ActorID       string      `json:"actor_id"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) InsertBankAccountEvent(ctx context.Context, arg InsertBankAccountEventParams) (BankingBankAccountEvent, error) {
	row := q.db.QueryRow(ctx, insertBankAccountEvent,
		arg.BankAccountID,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.Metadata,
	)
	var i BankingBankAccountEvent
	err := row.Scan(
		&i.ID,
		&i.BankAccountID,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const insertFundingRequest = `-- name: InsertFundingRequest :one
INSERT INTO banking.funding_requests (
    customer_reference,
    idempotency_key,
    request_hash,
    transfer_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (customer_reference, idempotency_key) DO NOTHING
RETURNING transfer_id
`

type InsertFundingRequestParams struct {
	CustomerReference string      `json:"customer_reference"`
	IdempotencyKey    string      `json:"idempotency_key"`
	RequestHash       string      `json:"request_hash"`
	TransferID        pgtype.UUID `json:"transfer_id"`
}

func (q *Queries) InsertFundingRequest(ctx context.Context, arg InsertFundingRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertFundingRequest,
		arg.CustomerReference,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.TransferID,
	)
	var transfer_id pgtype.UUID
	err := row.Scan(&transfer_id)
	return transfer_id, err
}

const insertProviderEvent = `-- name: InsertProviderEvent :one
INSERT INTO banking.provider_events (
    provider,
    external_event_id,
    resource_type,
    resource_id,
    event_type,
    payload_hash,
    ledger_transaction_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (provider, external_event_id) DO NOTHING
RETURNING provider, external_event_id, resource_type, resource_id, event_type, payload_hash, ledger_transaction_id, processed_at
`

type InsertProviderEventParams struct {
	Provider            string      `json:"provider"`
	ExternalEventID     string      `json:"external_event_id"`
	ResourceType        string      `json:"resource_type"`
	ResourceID          pgtype.UUID `json:"resource_id"`
	EventType           string      `json:"event_type"`
	PayloadHash         string      `json:"payload_hash"`
	LedgerTransactionID pgtype.UUID `json:"ledger_transaction_id"`
}

func (q *Queries) InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (BankingProviderEvent, error) {
	row := q.db.QueryRow(ctx, insertProviderEvent,
		arg.Provider,
		arg.ExternalEventID,
		arg.ResourceType,
		arg.ResourceID,
		arg.EventType,
		arg.PayloadHash,
		arg.LedgerTransactionID,
	)
	var i BankingProviderEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.ResourceType,
		&i.ResourceID,
		&i.EventType,
		&i.PayloadHash,
		&i.LedgerTransactionID,
		&i.ProcessedAt,
	)
	return i, err
}

const insertReconciliationItem = `-- name: InsertReconciliationItem :one
INSERT INTO banking.reconciliation_items (
    run_id,
    customer_reference,
    ledger_amount,
    provider_amount,
    difference,
    status,
    compliance_case_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, run_id, customer_reference, ledger_amount, provider_amount, difference, status, compliance_case_id, created_at
`

type InsertReconciliationItemParams struct {
	RunID             pgtype.UUID   `json:"run_id"`
	CustomerReference string        `json:"customer_reference"`
	LedgerAmount      money.Decimal `json:"ledger_amount"`
	ProviderAmount    money.Decimal `json:"provider_amount"`
	Difference        money.Decimal `json:"difference"`
	Status            string        `json:"status"`
	ComplianceCaseID  pgtype.UUID   `json:"compliance_case_id"`
}

func (q *Queries) InsertReconciliationItem(ctx context.Context, arg InsertReconciliationItemParams) (BankingReconciliationItem, error) {
	row := q.db.QueryRow(ctx, insertReconciliationItem,
		arg.RunID,
		arg.CustomerReference,
		arg.LedgerAmount,
		arg.ProviderAmount,
		arg.Difference,
		arg.Status,
		arg.ComplianceCaseID,
	)
	var i BankingReconciliationItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.CustomerReference,
		&i.LedgerAmount,
		&i.ProviderAmount,
		&i.Difference,
		&i.Status,
		&i.ComplianceCaseID,
		&i.CreatedAt,
	)
	return i, err
}

const insertWithdrawalRequest = `-- name: InsertWithdrawalRequest :one
INSERT INTO banking.withdrawal_requests (
    customer_reference,
    idempotency_key,
    request_hash,
    withdrawal_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (customer_reference, idempotency_key) DO NOTHING
RETURNING withdrawal_id
`

type InsertWithdrawalRequestParams struct {
	CustomerReference string      `json:"customer_reference"`
	IdempotencyKey    string      `json:"idempotency_key"`
	RequestHash       string      `json:"request_hash"`
	WithdrawalID      pgtype.UUID `json:"withdrawal_id"`
}

func (q *Queries) InsertWithdrawalRequest(ctx context.Context, arg InsertWithdrawalRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertWithdrawalRequest,
		arg.CustomerReference,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.WithdrawalID,
	)
	var withdrawal_id pgtype.UUID
	err := row.Scan(&withdrawal_id)
	return withdrawal_id, err
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
FROM banking.bank_accounts
WHERE customer_reference = $1
ORDER BY successfully_funded_at DESC NULLS LAST, created_at, id
`

func (q *Queries) ListBankAccounts(ctx context.Context, customerReference string) ([]BankingBankAccount, error) {
	rows, err := q.db.Query(ctx, listBankAccounts, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankingBankAccount
	for rows.Next() {
		var i BankingBankAccount
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.Provider,
			&i.ExternalAccountReference,
			&i.RailSupport,
			&i.OwnerRelation,
			&i.OwnershipStatus,
			&i.Status,
			&i.RiskClass,
			&i.SuccessfullyFundedAt,
			&i.CoolingUntil,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFundingTransfers = `-- name: ListFundingTransfers :many
SELECT id, customer_reference, bank_account_id, rail, amount, status, provider, provider_transfer_id, pending_ledger_transaction_id, pending_release_transaction_id, settled_ledger_transaction_id, return_reversal_transaction_id, reason_code, policy_version, created_at, updated_at, version
FROM banking.funding_transfers
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListFundingTransfersParams struct {
	CustomerReference string `json:"customer_reference"`
	PageSize          int32  `json:"page_size"`
}

func (q *Queries) ListFundingTransfers(ctx context.Context, arg ListFundingTransfersParams) ([]BankingFundingTransfer, error) {
	rows, err := q.db.Query(ctx, listFundingTransfers, arg.CustomerReference, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankingFundingTransfer
	for rows.Next() {
		var i BankingFundingTransfer
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.BankAccountID,
			&i.Rail,
			&i.Amount,
			&i.Status,
			&i.Provider,
			&i.ProviderTransferID,
			&i.PendingLedgerTransactionID,
			&i.PendingReleaseTransactionID,
			&i.SettledLedgerTransactionID,
			&i.ReturnReversalTransactionID,
			&i.ReasonCode,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationItems = `-- name: ListReconciliationItems :many
SELECT id, run_id, customer_reference, ledger_amount, provider_amount, difference, status, compliance_case_id, created_at
FROM banking.reconciliation_items
WHERE run_id = $1
ORDER BY customer_reference
`

func (q *Queries) ListReconciliationItems(ctx context.Context, runID pgtype.UUID) ([]BankingReconciliationItem, error) {
	rows, err := q.db.Query(ctx, listReconciliationItems, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankingReconciliationItem
	for rows.Next() {
		var i BankingReconciliationItem
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.CustomerReference,
			&i.LedgerAmount,
			&i.ProviderAmount,
			&i.Difference,
			&i.Status,
			&i.ComplianceCaseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawals = `-- name: ListWithdrawals :many
SELECT id, customer_reference, bank_account_id, amount, status, reason_code, next_action, compliance_case_id, cooling_until, reservation_ledger_transaction_id, submitted_ledger_transaction_id, return_reservation_reversal_id, return_submitted_reversal_id, provider, provider_transfer_id, policy_version, created_at, updated_at, version
FROM banking.withdrawals
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListWithdrawalsParams struct {
	CustomerReference string `json:"customer_reference"`
	PageSize          int32  `json:"page_size"`
}

func (q *Queries) ListWithdrawals(ctx context.Context, arg ListWithdrawalsParams) ([]BankingWithdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawals, arg.CustomerReference, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankingWithdrawal
	for rows.Next() {
		var i BankingWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.BankAccountID,
			&i.Amount,
			&i.Status,
			&i.ReasonCode,
			&i.NextAction,
			&i.ComplianceCaseID,
			&i.CoolingUntil,
			&i.ReservationLedgerTransactionID,
			&i.SubmittedLedgerTransactionID,
			&i.ReturnReservationReversalID,
			&i.ReturnSubmittedReversalID,
			&i.Provider,
			&i.ProviderTransferID,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBankAccountFunded = `-- name: MarkBankAccountFunded :one
UPDATE banking.bank_accounts
SET successfully_funded_at = COALESCE(successfully_funded_at, clock_timestamp())
WHERE id = $1
RETURNING id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
`

func (q *Queries) MarkBankAccountFunded(ctx context.Context, id pgtype.UUID) (BankingBankAccount, error) {
	row := q.db.QueryRow(ctx, markBankAccountFunded, id)
	var i BankingBankAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Provider,
		&i.ExternalAccountReference,
		&i.RailSupport,
		&i.OwnerRelation,
		&i.OwnershipStatus,
		&i.Status,
		&i.RiskClass,
		&i.SuccessfullyFundedAt,
		&i.CoolingUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const sumLedgerBankingSettled = `-- name: SumLedgerBankingSettled :one
SELECT COALESCE(SUM(
    CASE entry.direction
        WHEN 'DEBIT' THEN entry.amount
        ELSE -entry.amount
    END
), 0)::NUMERIC(38, 18) AS amount
FROM ledger.entries AS entry
JOIN ledger.transactions AS transaction ON transaction.id = entry.transaction_id
WHERE entry.account_id = $1
  AND entry.currency = 'USD'
  AND entry.balance_dimension = 'SETTLED'
  AND (
      transaction.transaction_type IN ('ACH_FUNDING_SETTLED', 'WIRE_FUNDING_CREDITED', 'BANK_WITHDRAWAL_SUBMITTED')
      OR (
          transaction.transaction_type = 'REVERSAL'
          AND EXISTS (
              SELECT 1
              FROM ledger.reversals AS reversal
              JOIN ledger.transactions AS original
                ON original.id = reversal.original_transaction_id
              WHERE reversal.reversal_transaction_id = transaction.id
                AND original.transaction_type IN ('ACH_FUNDING_SETTLED', 'WIRE_FUNDING_CREDITED', 'BANK_WITHDRAWAL_SUBMITTED')
          )
      )
  )
`

func (q *Queries) SumLedgerBankingSettled(ctx context.Context, cashLedgerAccountID pgtype.UUID) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumLedgerBankingSettled, cashLedgerAccountID)
	var amount money.Decimal
	err := row.Scan(&amount)
	return amount, err
}

const sumProviderSettledFunding = `-- name: SumProviderSettledFunding :one
SELECT COALESCE(SUM(
    CASE
        WHEN rail = 'ACH' AND status = 'SETTLED' THEN amount
        WHEN rail = 'WIRE' AND status = 'CREDITED' THEN amount
        ELSE 0
    END
), 0)::NUMERIC(38, 18) AS amount
FROM banking.funding_transfers
WHERE customer_reference = $1
`

func (q *Queries) SumProviderSettledFunding(ctx context.Context, customerReference string) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumProviderSettledFunding, customerReference)
	var amount money.Decimal
	err := row.Scan(&amount)
	return amount, err
}

const sumProviderSettledWithdrawals = `-- name: SumProviderSettledWithdrawals :one
SELECT COALESCE(SUM(CASE WHEN status = 'SETTLED' THEN amount ELSE 0 END), 0)::NUMERIC(38, 18) AS amount
FROM banking.withdrawals
WHERE customer_reference = $1
`

func (q *Queries) SumProviderSettledWithdrawals(ctx context.Context, customerReference string) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumProviderSettledWithdrawals, customerReference)
	var amount money.Decimal
	err := row.Scan(&amount)
	return amount, err
}

const transitionFundingTransfer = `-- name: TransitionFundingTransfer :one
UPDATE banking.funding_transfers
SET status = $1,
    reason_code = $2,
    pending_release_transaction_id = COALESCE($3, pending_release_transaction_id),
    settled_ledger_transaction_id = COALESCE($4, settled_ledger_transaction_id),
    return_reversal_transaction_id = COALESCE($5, return_reversal_transaction_id)
WHERE id = $6
RETURNING id, customer_reference, bank_account_id, rail, amount, status, provider, provider_transfer_id, pending_ledger_transaction_id, pending_release_transaction_id, settled_ledger_transaction_id, return_reversal_transaction_id, reason_code, policy_version, created_at, updated_at, version
`

type TransitionFundingTransferParams struct {
	Status                      string      `json:"status"`
	ReasonCode                  pgtype.Text `json:"reason_code"`
	PendingReleaseTransactionID pgtype.UUID `json:"pending_release_transaction_id"`
	SettledLedgerTransactionID  pgtype.UUID `json:"settled_ledger_transaction_id"`
	ReturnReversalTransactionID pgtype.UUID `json:"return_reversal_transaction_id"`
	ID                          pgtype.UUID `json:"id"`
}

func (q *Queries) TransitionFundingTransfer(ctx context.Context, arg TransitionFundingTransferParams) (BankingFundingTransfer, error) {
	row := q.db.QueryRow(ctx, transitionFundingTransfer,
		arg.Status,
		arg.ReasonCode,
		arg.PendingReleaseTransactionID,
		arg.SettledLedgerTransactionID,
		arg.ReturnReversalTransactionID,
		arg.ID,
	)
	var i BankingFundingTransfer
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Rail,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PendingLedgerTransactionID,
		&i.PendingReleaseTransactionID,
		&i.SettledLedgerTransactionID,
		&i.ReturnReversalTransactionID,
		&i.ReasonCode,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const transitionWithdrawal = `-- name: TransitionWithdrawal :one
UPDATE banking.withdrawals
SET status = $1,
    reason_code = $2,
    next_action = $3,
    compliance_case_id = COALESCE($4, compliance_case_id),
    cooling_until = COALESCE($5, cooling_until),
    reservation_ledger_transaction_id = COALESCE($6, reservation_ledger_transaction_id),
    submitted_ledger_transaction_id = COALESCE($7, submitted_ledger_transaction_id),
    return_reservation_reversal_id = COALESCE($8, return_reservation_reversal_id),
    return_submitted_reversal_id = COALESCE($9, return_submitted_reversal_id)
WHERE id = $10
RETURNING id, customer_reference, bank_account_id, amount, status, reason_code, next_action, compliance_case_id, cooling_until, reservation_ledger_transaction_id, submitted_ledger_transaction_id, return_reservation_reversal_id, return_submitted_reversal_id, provider, provider_transfer_id, policy_version, created_at, updated_at, version
`

type TransitionWithdrawalParams struct {
	Status                         string             `json:"status"`
	ReasonCode                     string             `json:"reason_code"`
	NextAction                     string             `json:"next_action"`
	ComplianceCaseID               pgtype.UUID        `json:"compliance_case_id"`
	CoolingUntil                   pgtype.Timestamptz `json:"cooling_until"`
	ReservationLedgerTransactionID pgtype.UUID        `json:"reservation_ledger_transaction_id"`
	SubmittedLedgerTransactionID   pgtype.UUID        `json:"submitted_ledger_transaction_id"`
	ReturnReservationReversalID    pgtype.UUID        `json:"return_reservation_reversal_id"`
	ReturnSubmittedReversalID      pgtype.UUID        `json:"return_submitted_reversal_id"`
	ID                             pgtype.UUID        `json:"id"`
}

func (q *Queries) TransitionWithdrawal(ctx context.Context, arg TransitionWithdrawalParams) (BankingWithdrawal, error) {
	row := q.db.QueryRow(ctx, transitionWithdrawal,
		arg.Status,
		arg.ReasonCode,
		arg.NextAction,
		arg.ComplianceCaseID,
		arg.CoolingUntil,
		arg.ReservationLedgerTransactionID,
		arg.SubmittedLedgerTransactionID,
		arg.ReturnReservationReversalID,
		arg.ReturnSubmittedReversalID,
		arg.ID,
	)
	var i BankingWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.BankAccountID,
		&i.Amount,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.ComplianceCaseID,
		&i.CoolingUntil,
		&i.ReservationLedgerTransactionID,
		&i.SubmittedLedgerTransactionID,
		&i.ReturnReservationReversalID,
		&i.ReturnSubmittedReversalID,
		&i.Provider,
		&i.ProviderTransferID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateBankAccountOwnership = `-- name: UpdateBankAccountOwnership :one
UPDATE banking.bank_accounts
SET ownership_status = $1,
    cooling_until = $2
WHERE id = $3
RETURNING id, customer_reference, provider, external_account_reference, rail_support, owner_relation, ownership_status, status, risk_class, successfully_funded_at, cooling_until, policy_version, created_at, updated_at, version
`

type UpdateBankAccountOwnershipParams struct {
	OwnershipStatus string             `json:"ownership_status"`
	CoolingUntil    pgtype.Timestamptz `json:"cooling_until"`
	ID              pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateBankAccountOwnership(ctx context.Context, arg UpdateBankAccountOwnershipParams) (BankingBankAccount, error) {
	row := q.db.QueryRow(ctx, updateBankAccountOwnership, arg.OwnershipStatus, arg.CoolingUntil, arg.ID)
	var i BankingBankAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.Provider,
		&i.ExternalAccountReference,
		&i.RailSupport,
		&i.OwnerRelation,
		&i.OwnershipStatus,
		&i.Status,
		&i.RiskClass,
		&i.SuccessfullyFundedAt,
		&i.CoolingUntil,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
