// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type BankingBankAccount struct {
	ID                       pgtype.UUID `json:"id"`
	CustomerReference        string      `json:"customer_reference"`
	Provider                 string      `json:"provider"`
	ExternalAccountReference string      `json:"external_account_reference"`
	RailSupport              string      `json:"rail_support"`
	// THIRD_PARTY is permanently ineligible for MVP withdrawals and can never become VERIFIED.
	OwnerRelation        string             `json:"owner_relation"`
	OwnershipStatus      string             `json:"ownership_status"`
	Status               string             `json:"status"`
	RiskClass            string             `json:"risk_class"`
	SuccessfullyFundedAt pgtype.Timestamptz `json:"successfully_funded_at"`
	// Dynamic policy output. APIs expose the date and next action, never the internal risk weights or thresholds.
	CoolingUntil  pgtype.Timestamptz `json:"cooling_until"`
	PolicyVersion string             `json:"policy_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Version       int64              `json:"version"`
}

type BankingBankAccountEvent struct {
	ID            pgtype.UUID        `json:"id"`
	BankAccountID pgtype.UUID        `json:"bank_account_id"`
	EventType     string             `json:"event_type"`
	ActorType     string             `json:"actor_type"`
	ActorID       string             `json:"actor_id"`
	Metadata      []byte             `json:"metadata"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type BankingCustomerProfile struct {
	CustomerReference               string             `json:"customer_reference"`
	PaperAccountID                  pgtype.UUID        `json:"paper_account_id"`
	CashLedgerAccountID             pgtype.UUID        `json:"cash_ledger_account_id"`
	ProviderClearingLedgerAccountID pgtype.UUID        `json:"provider_clearing_ledger_account_id"`
	PolicyVersion                   string             `json:"policy_version"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
}

type BankingFundingRequest struct {
	CustomerReference string             `json:"customer_reference"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       string             `json:"request_hash"`
	TransferID        pgtype.UUID        `json:"transfer_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type BankingFundingTransfer struct {
	ID                          pgtype.UUID        `json:"id"`
	CustomerReference           string             `json:"customer_reference"`
	BankAccountID               pgtype.UUID        `json:"bank_account_id"`
	Rail                        string             `json:"rail"`
	Amount                      money.Decimal      `json:"amount"`
	Status                      string             `json:"status"`
	Provider                    string             `json:"provider"`
	ProviderTransferID          string             `json:"provider_transfer_id"`
	PendingLedgerTransactionID  pgtype.UUID        `json:"pending_ledger_transaction_id"`
	PendingReleaseTransactionID pgtype.UUID        `json:"pending_release_transaction_id"`
	SettledLedgerTransactionID  pgtype.UUID        `json:"settled_ledger_transaction_id"`
	ReturnReversalTransactionID pgtype.UUID        `json:"return_reversal_transaction_id"`
	ReasonCode                  pgtype.Text        `json:"reason_code"`
	PolicyVersion               string             `json:"policy_version"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	Version                     int64              `json:"version"`
}

// Immutable provider callback inbox. Adapters never mutate Ledger or balance projections directly.
type BankingProviderEvent struct {
	Provider            string             `json:"provider"`
	ExternalEventID     string             `json:"external_event_id"`
	ResourceType        string             `json:"resource_type"`
	ResourceID          pgtype.UUID        `json:"resource_id"`
	EventType           string             `json:"event_type"`
	PayloadHash         string             `json:"payload_hash"`
	LedgerTransactionID pgtype.UUID        `json:"ledger_transaction_id"`
	ProcessedAt         pgtype.Timestamptz `json:"processed_at"`
}

type BankingReconciliationItem struct {
	ID                pgtype.UUID        `json:"id"`
	RunID             pgtype.UUID        `json:"run_id"`
	CustomerReference string             `json:"customer_reference"`
	LedgerAmount      money.Decimal      `json:"ledger_amount"`
	ProviderAmount    money.Decimal      `json:"provider_amount"`
	Difference        money.Decimal      `json:"difference"`
	Status            string             `json:"status"`
	ComplianceCaseID  pgtype.UUID        `json:"compliance_case_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type BankingReconciliationRun struct {
	ID            pgtype.UUID        `json:"id"`
	Scope         string             `json:"scope"`
	Status        string             `json:"status"`
	PolicyVersion string             `json:"policy_version"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type BankingWithdrawal struct {
	ID                             pgtype.UUID        `json:"id"`
	CustomerReference              string             `json:"customer_reference"`
	BankAccountID                  pgtype.UUID        `json:"bank_account_id"`
	Amount                         money.Decimal      `json:"amount"`
	Status                         string             `json:"status"`
	ReasonCode                     string             `json:"reason_code"`
	NextAction                     string             `json:"next_action"`
	ComplianceCaseID               pgtype.UUID        `json:"compliance_case_id"`
	CoolingUntil                   pgtype.Timestamptz `json:"cooling_until"`
	ReservationLedgerTransactionID pgtype.UUID        `json:"reservation_ledger_transaction_id"`
	SubmittedLedgerTransactionID   pgtype.UUID        `json:"submitted_ledger_transaction_id"`
	ReturnReservationReversalID    pgtype.UUID        `json:"return_reservation_reversal_id"`
	ReturnSubmittedReversalID      pgtype.UUID        `json:"return_submitted_reversal_id"`
	Provider                       string             `json:"provider"`
	ProviderTransferID             string             `json:"provider_transfer_id"`
	PolicyVersion                  string             `json:"policy_version"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	Version                        int64              `json:"version"`
}

type BankingWithdrawalRequest struct {
	CustomerReference string             `json:"customer_reference"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       string             `json:"request_hash"`
	WithdrawalID      pgtype.UUID        `json:"withdrawal_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
