// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearBankAccountFunding(ctx context.Context, id pgtype.UUID) (BankingBankAccount, error)
	CompleteReconciliationRun(ctx context.Context, arg CompleteReconciliationRunParams) (BankingReconciliationRun, error)
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankingBankAccount, error)
	CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (BankingCustomerProfile, error)
	CreateFundingTransfer(ctx context.Context, arg CreateFundingTransferParams) (BankingFundingTransfer, error)
	CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (BankingReconciliationRun, error)
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (BankingWithdrawal, error)
	GetBankAccount(ctx context.Context, id pgtype.UUID) (BankingBankAccount, error)
	GetBankAccountByExternalReference(ctx context.Context, arg GetBankAccountByExternalReferenceParams) (BankingBankAccount, error)
	GetBankAccountForUpdate(ctx context.Context, id pgtype.UUID) (BankingBankAccount, error)
	GetCustomerProfile(ctx context.Context, customerReference string) (BankingCustomerProfile, error)
	GetCustomerProfileForUpdate(ctx context.Context, customerReference string) (BankingCustomerProfile, error)
	GetFundingRequest(ctx context.Context, arg GetFundingRequestParams) (BankingFundingRequest, error)
	GetFundingTransfer(ctx context.Context, id pgtype.UUID) (BankingFundingTransfer, error)
	GetFundingTransferForUpdate(ctx context.Context, id pgtype.UUID) (BankingFundingTransfer, error)
	GetPreferredWithdrawalAccount(ctx context.Context, customerReference string) (BankingBankAccount, error)
	GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (BankingProviderEvent, error)
	GetWithdrawal(ctx context.Context, id pgtype.UUID) (BankingWithdrawal, error)
	GetWithdrawalByCaseForUpdate(ctx context.Context, complianceCaseID pgtype.UUID) (BankingWithdrawal, error)
	GetWithdrawalForUpdate(ctx context.Context, id pgtype.UUID) (BankingWithdrawal, error)
	GetWithdrawalRequest(ctx context.Context, arg GetWithdrawalRequestParams) (BankingWithdrawalRequest, error)
	InsertBankAccountEvent(ctx context.Context, arg InsertBankAccountEventParams) (BankingBankAccountEvent, error)
	InsertFundingRequest(ctx context.Context, arg InsertFundingRequestParams) (pgtype.UUID, error)
	InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (BankingProviderEvent, error)
	InsertReconciliationItem(ctx context.Context, arg InsertReconciliationItemParams) (BankingReconciliationItem, error)
	InsertWithdrawalRequest(ctx context.Context, arg InsertWithdrawalRequestParams) (pgtype.UUID, error)
	ListBankAccounts(ctx context.Context, customerReference string) ([]BankingBankAccount, error)
	ListFundingTransfers(ctx context.Context, arg ListFundingTransfersParams) ([]BankingFundingTransfer, error)
	ListReconciliationItems(ctx context.Context, runID pgtype.UUID) ([]BankingReconciliationItem, error)
	ListWithdrawals(ctx context.Context, arg ListWithdrawalsParams) ([]BankingWithdrawal, error)
	MarkBankAccountFunded(ctx context.Context, id pgtype.UUID) (BankingBankAccount, error)
	SumLedgerBankingSettled(ctx context.Context, cashLedgerAccountID pgtype.UUID) (money.Decimal, error)
	SumProviderSettledFunding(ctx context.Context, customerReference string) (money.Decimal, error)
	SumProviderSettledWithdrawals(ctx context.Context, customerReference string) (money.Decimal, error)
	TransitionFundingTransfer(ctx context.Context, arg TransitionFundingTransferParams) (BankingFundingTransfer, error)
	TransitionWithdrawal(ctx context.Context, arg TransitionWithdrawalParams) (BankingWithdrawal, error)
	UpdateBankAccountOwnership(ctx context.Context, arg UpdateBankAccountOwnershipParams) (BankingBankAccount, error)
}

var _ Querier = (*Queries)(nil)
