// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crypto.sql

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeConversion = `-- name: CompleteConversion :one
UPDATE crypto.conversions
SET status = $1,
    reason_code = $2,
    next_action = $3,
    routing_metadata = $4,
    compliance_case_id = $5
WHERE id = $6
  AND status = 'ROUTING'
RETURNING id, customer_reference, source_asset, destination_asset, source_amount, simulation_scenario, status, reason_code, next_action, routing_metadata, policy_version, reservation_ledger_transaction_id, compliance_case_id, created_at, updated_at, version
`

type CompleteConversionParams struct {
	Status           string      `json:"status"`
	ReasonCode       pgtype.Text `json:"reason_code"`
	NextAction       string      `json:"next_action"`
	RoutingMetadata  []byte      `json:"routing_metadata"`
	ComplianceCaseID pgtype.UUID `json:"compliance_case_id"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) CompleteConversion(ctx context.Context, arg CompleteConversionParams) (CryptoConversion, error) {
	row := q.db.QueryRow(ctx, completeConversion,
		arg.Status,
		arg.ReasonCode,
		arg.NextAction,
		arg.RoutingMetadata,
		arg.ComplianceCaseID,
		arg.ID,
	)
	var i CryptoConversion
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.SourceAsset,
		&i.DestinationAsset,
		&i.SourceAmount,
		&i.SimulationScenario,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.RoutingMetadata,
		&i.PolicyVersion,
		&i.ReservationLedgerTransactionID,
		&i.ComplianceCaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createConversion = `-- name: CreateConversion :one
INSERT INTO crypto.conversions (
    id,
    customer_reference,
    source_asset,
    destination_asset,
    source_amount,
    simulation_scenario,
    policy_version,
    reservation_ledger_transaction_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, customer_reference, source_asset, destination_asset, source_amount, simulation_scenario, status, reason_code, next_action, routing_metadata, policy_version, reservation_ledger_transaction_id, compliance_case_id, created_at, updated_at, version
`

type CreateConversionParams struct {
	ID                             pgtype.UUID   `json:"id"`
	CustomerReference              string        `json:"customer_reference"`
	SourceAsset                    string        `json:"source_asset"`
	DestinationAsset               string        `json:"destination_asset"`
	SourceAmount                   money.Decimal `json:"source_amount"`
	SimulationScenario             string        `json:"simulation_scenario"`
	PolicyVersion                  string        `json:"policy_version"`
	ReservationLedgerTransactionID pgtype.UUID   `json:"reservation_ledger_transaction_id"`
}

func (q *Queries) CreateConversion(ctx context.Context, arg CreateConversionParams) (CryptoConversion, error) {
	row := q.db.QueryRow(ctx, createConversion,
		arg.ID,
		arg.CustomerReference,
		arg.SourceAsset,
		arg.DestinationAsset,
		arg.SourceAmount,
		arg.SimulationScenario,
		arg.PolicyVersion,
		arg.ReservationLedgerTransactionID,
	)
	var i CryptoConversion
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.SourceAsset,
		&i.DestinationAsset,
		&i.SourceAmount,
		&i.SimulationScenario,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.RoutingMetadata,
		&i.PolicyVersion,
		&i.ReservationLedgerTransactionID,
		&i.ComplianceCaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createCustomerProfile = `-- name: CreateCustomerProfile :one
INSERT INTO crypto.customer_profiles (
    customer_reference,
    paper_account_id,
    cash_ledger_account_id,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (customer_reference) DO NOTHING
RETURNING customer_reference, paper_account_id, cash_ledger_account_id, policy_version, created_at, version
`

type CreateCustomerProfileParams struct {
	CustomerReference   string      `json:"customer_reference"`
	PaperAccountID      pgtype.UUID `json:"paper_account_id"`
	CashLedgerAccountID pgtype.UUID `json:"cash_ledger_account_id"`
	PolicyVersion       string      `json:"policy_version"`
}

func (q *Queries) CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CryptoCustomerProfile, error) {
	row := q.db.QueryRow(ctx, createCustomerProfile,
		arg.CustomerReference,
		arg.PaperAccountID,
		arg.CashLedgerAccountID,
		arg.PolicyVersion,
	)
	var i CryptoCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO crypto.deposits (
    id,
    customer_reference,
    deposit_address_id,
    asset_symbol,
    network_code,
    quantity,
    status,
    provider,
    provider_transaction_id,
    ledger_transaction_id,
    reason_code
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, customer_reference, deposit_address_id, asset_symbol, network_code, quantity, status, provider, provider_transaction_id, ledger_transaction_id, reason_code, created_at, updated_at, version
`

type CreateDepositParams struct {
	ID                    pgtype.UUID   `json:"id"`
	CustomerReference     string        `json:"customer_reference"`
	DepositAddressID      pgtype.UUID   `json:"deposit_address_id"`
	AssetSymbol           string        `json:"asset_symbol"`
	NetworkCode           string        `json:"network_code"`
	Quantity              money.Decimal `json:"quantity"`
	Status                string        `json:"status"`
	Provider              string        `json:"provider"`
	ProviderTransactionID string        `json:"provider_transaction_id"`
	LedgerTransactionID   pgtype.UUID   `json:"ledger_transaction_id"`
	ReasonCode            pgtype.Text   `json:"reason_code"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (CryptoDeposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.ID,
		arg.CustomerReference,
		arg.DepositAddressID,
		arg.AssetSymbol,
		arg.NetworkCode,
		arg.Quantity,
		arg.Status,
		arg.Provider,
		arg.ProviderTransactionID,
		arg.LedgerTransactionID,
		arg.ReasonCode,
	)
	var i CryptoDeposit
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.DepositAddressID,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Quantity,
		&i.Status,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.LedgerTransactionID,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createDepositAddress = `-- name: CreateDepositAddress :one
INSERT INTO crypto.deposit_addresses (
    id,
    customer_reference,
    asset_symbol,
    network_code,
    provider,
    external_address,
    memo
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (customer_reference, asset_symbol, network_code) DO NOTHING
RETURNING id, customer_reference, asset_symbol, network_code, provider, external_address, memo, status, created_at
`

type CreateDepositAddressParams struct {
	ID                pgtype.UUID `json:"id"`
	CustomerReference string      `json:"customer_reference"`
	AssetSymbol       string      `json:"asset_symbol"`
	NetworkCode       string      `json:"network_code"`
	Provider          string      `json:"provider"`
	ExternalAddress   string      `json:"external_address"`
	Memo              pgtype.Text `json:"memo"`
}

func (q *Queries) CreateDepositAddress(ctx context.Context, arg CreateDepositAddressParams) (CryptoDepositAddress, error) {
	row := q.db.QueryRow(ctx, createDepositAddress,
		arg.ID,
		arg.CustomerReference,
		arg.AssetSymbol,
		arg.NetworkCode,
		arg.Provider,
		arg.ExternalAddress,
		arg.Memo,
	)
	var i CryptoDepositAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Provider,
		&i.ExternalAddress,
		&i.Memo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createReconciliationRun = `-- name: CreateReconciliationRun :one
INSERT INTO crypto.reconciliation_runs (
    id,
    customer_reference,
    asset_symbol,
    ledger_amount,
    custody_amount,
    difference,
    status,
    compliance_case_id,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, customer_reference, asset_symbol, ledger_amount, custody_amount, difference, status, compliance_case_id, policy_version, started_at, completed_at
`

type CreateReconciliationRunParams struct {
	ID                pgtype.UUID   `json:"id"`
	CustomerReference string        `json:"customer_reference"`
	AssetSymbol       string        `json:"asset_symbol"`
	LedgerAmount      money.Decimal `json:"ledger_amount"`
	CustodyAmount     money.Decimal `json:"custody_amount"`
	Difference        money.Decimal `json:"difference"`
	Status            string        `json:"status"`
	ComplianceCaseID  pgtype.UUID   `json:"compliance_case_id"`
	PolicyVersion     string        `json:"policy_version"`
}

func (q *Queries) CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (CryptoReconciliationRun, error) {
	row := q.db.QueryRow(ctx, createReconciliationRun,
		arg.ID,
		arg.CustomerReference,
		arg.AssetSymbol,
		arg.LedgerAmount,
		arg.CustodyAmount,
		arg.Difference,
		arg.Status,
		arg.ComplianceCaseID,
		arg.PolicyVersion,
	)
	var i CryptoReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.LedgerAmount,
		&i.CustodyAmount,
		&i.Difference,
		&i.Status,
		&i.ComplianceCaseID,
		&i.PolicyVersion,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWithdrawal = `-- name: CreateWithdrawal :one
INSERT INTO crypto.withdrawals (
    id,
    customer_reference,
    withdrawal_address_id,
    asset_symbol,
    network_code,
    quantity,
    status,
    reason_code,
    next_action,
    provider,
    provider_withdrawal_id,
    reservation_ledger_transaction_id,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, customer_reference, withdrawal_address_id, asset_symbol, network_code, quantity, status, reason_code, next_action, provider, provider_withdrawal_id, reservation_ledger_transaction_id, broadcast_ledger_transaction_id, reservation_reversal_transaction_id, broadcast_reversal_transaction_id, policy_version, created_at, updated_at, version
`

type CreateWithdrawalParams struct {
	ID                             pgtype.UUID   `json:"id"`
	CustomerReference              string        `json:"customer_reference"`
	WithdrawalAddressID            pgtype.UUID   `json:"withdrawal_address_id"`
	AssetSymbol                    string        `json:"asset_symbol"`
	NetworkCode                    string        `json:"network_code"`
	Quantity                       money.Decimal `json:"quantity"`
	Status                         string        `json:"status"`
	ReasonCode                     string        `json:"reason_code"`
	NextAction                     string        `json:"next_action"`
	Provider                       string        `json:"provider"`
	ProviderWithdrawalID           string        `json:"provider_withdrawal_id"`
	ReservationLedgerTransactionID pgtype.UUID   `json:"reservation_ledger_transaction_id"`
	PolicyVersion                  string        `json:"policy_version"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (CryptoWithdrawal, error) {
	row := q.db.QueryRow(ctx, createWithdrawal,
		arg.ID,
		arg.CustomerReference,
		arg.WithdrawalAddressID,
		arg.AssetSymbol,
		arg.NetworkCode,
		arg.Quantity,
		arg.Status,
		arg.ReasonCode,
		arg.NextAction,
		arg.Provider,
		arg.ProviderWithdrawalID,
		arg.ReservationLedgerTransactionID,
		arg.PolicyVersion,
	)
	var i CryptoWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.WithdrawalAddressID,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Quantity,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.Provider,
		&i.ProviderWithdrawalID,
		&i.ReservationLedgerTransactionID,
		&i.BroadcastLedgerTransactionID,
		&i.ReservationReversalTransactionID,
		&i.BroadcastReversalTransactionID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const createWithdrawalAddress = `-- name: CreateWithdrawalAddress :one
INSERT INTO crypto.withdrawal_addresses (
    id,
    customer_reference,
    asset_symbol,
    network_code,
    external_address,
    label,
    status,
    risk_level,
    cooling_until,
    cooling_reason,
    policy_version
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, customer_reference, asset_symbol, network_code, external_address, label, status, risk_level, cooling_until, cooling_reason, policy_version, created_at, updated_at, version
`

type CreateWithdrawalAddressParams struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	AssetSymbol       string             `json:"asset_symbol"`
	NetworkCode       string             `json:"network_code"`
	ExternalAddress   string             `json:"external_address"`
	Label             string             `json:"label"`
	Status            string             `json:"status"`
	RiskLevel         string             `json:"risk_level"`
	CoolingUntil      pgtype.Timestamptz `json:"cooling_until"`
	CoolingReason     string             `json:"cooling_reason"`
	PolicyVersion     string             `json:"policy_version"`
}

func (q *Queries) CreateWithdrawalAddress(ctx context.Context, arg CreateWithdrawalAddressParams) (CryptoWithdrawalAddress, error) {
	row := q.db.QueryRow(ctx, createWithdrawalAddress,
		arg.ID,
		arg.CustomerReference,
		arg.AssetSymbol,
		arg.NetworkCode,
		arg.ExternalAddress,
		arg.Label,
		arg.Status,
		arg.RiskLevel,
		arg.CoolingUntil,
		arg.CoolingReason,
		arg.PolicyVersion,
	)
	var i CryptoWithdrawalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.ExternalAddress,
		&i.Label,
		&i.Status,
		&i.RiskLevel,
		&i.CoolingUntil,
		&i.CoolingReason,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getActivePolicy = `-- name: GetActivePolicy :one
SELECT policy_version, platform_fee_rate, conversion_review_single_usd, conversion_review_rolling_usd, conversion_review_window_days, address_cooling_base_hours, address_cooling_device_hours, address_cooling_security_hours, address_cooling_recovery_hours, address_cooling_max_hours, quote_max_age_seconds, effective_at, active, created_at
FROM crypto.policies
WHERE active
  AND effective_at <= clock_timestamp()
ORDER BY effective_at DESC
LIMIT 1
`

func (q *Queries) GetActivePolicy(ctx context.Context) (CryptoPolicy, error) {
	row := q.db.QueryRow(ctx, getActivePolicy)
	var i CryptoPolicy
	err := row.Scan(
		&i.PolicyVersion,
		&i.PlatformFeeRate,
		&i.ConversionReviewSingleUsd,
		&i.ConversionReviewRollingUsd,
		&i.ConversionReviewWindowDays,
		&i.AddressCoolingBaseHours,
		&i.AddressCoolingDeviceHours,
		&i.AddressCoolingSecurityHours,
		&i.AddressCoolingRecoveryHours,
		&i.AddressCoolingMaxHours,
		&i.QuoteMaxAgeSeconds,
		&i.EffectiveAt,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT symbol, display_name, is_stablecoin, tradable, precision, created_at
FROM crypto.assets
WHERE symbol = $1
  AND tradable
`

func (q *Queries) GetAsset(ctx context.Context, symbol string) (CryptoAsset, error) {
	row := q.db.QueryRow(ctx, getAsset, symbol)
	var i CryptoAsset
	err := row.Scan(
		&i.Symbol,
		&i.DisplayName,
		&i.IsStablecoin,
		&i.Tradable,
		&i.Precision,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetLedgerAccounts = `-- name: GetAssetLedgerAccounts :one
SELECT customer_reference, asset_symbol, customer_ledger_account_id, custody_inventory_ledger_account_id, created_at
FROM crypto.asset_ledger_accounts
WHERE customer_reference = $1
  AND asset_symbol = $2
`

type GetAssetLedgerAccountsParams struct {
	CustomerReference string `json:"customer_reference"`
	AssetSymbol       string `json:"asset_symbol"`
}

func (q *Queries) GetAssetLedgerAccounts(ctx context.Context, arg GetAssetLedgerAccountsParams) (CryptoAssetLedgerAccount, error) {
	row := q.db.QueryRow(ctx, getAssetLedgerAccounts, arg.CustomerReference, arg.AssetSymbol)
	var i CryptoAssetLedgerAccount
	err := row.Scan(
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.CustomerLedgerAccountID,
		&i.CustodyInventoryLedgerAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetNetwork = `-- name: GetAssetNetwork :one
SELECT asset_networks.asset_symbol, asset_networks.network_code, asset_networks.native_deployment, asset_networks.deposit_enabled, asset_networks.withdrawal_enabled, asset_networks.created_at
FROM crypto.asset_networks AS asset_networks
JOIN crypto.networks AS networks
    ON networks.network_code = asset_networks.network_code
WHERE asset_networks.asset_symbol = $1
  AND asset_networks.network_code = $2
  AND networks.active
`

type GetAssetNetworkParams struct {
	AssetSymbol string `json:"asset_symbol"`
	NetworkCode string `json:"network_code"`
}

func (q *Queries) GetAssetNetwork(ctx context.Context, arg GetAssetNetworkParams) (CryptoAssetNetwork, error) {
	row := q.db.QueryRow(ctx, getAssetNetwork, arg.AssetSymbol, arg.NetworkCode)
	var i CryptoAssetNetwork
	err := row.Scan(
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.NativeDeployment,
		&i.DepositEnabled,
		&i.WithdrawalEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getConversion = `-- name: GetConversion :one
SELECT id, customer_reference, source_asset, destination_asset, source_amount, simulation_scenario, status, reason_code, next_action, routing_metadata, policy_version, reservation_ledger_transaction_id, compliance_case_id, created_at, updated_at, version
FROM crypto.conversions
WHERE id = $1
`

func (q *Queries) GetConversion(ctx context.Context, id pgtype.UUID) (CryptoConversion, error) {
	row := q.db.QueryRow(ctx, getConversion, id)
	var i CryptoConversion
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.SourceAsset,
		&i.DestinationAsset,
		&i.SourceAmount,
		&i.SimulationScenario,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.RoutingMetadata,
		&i.PolicyVersion,
		&i.ReservationLedgerTransactionID,
		&i.ComplianceCaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getConversionForUpdate = `-- name: GetConversionForUpdate :one
SELECT id, customer_reference, source_asset, destination_asset, source_amount, simulation_scenario, status, reason_code, next_action, routing_metadata, policy_version, reservation_ledger_transaction_id, compliance_case_id, created_at, updated_at, version
FROM crypto.conversions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetConversionForUpdate(ctx context.Context, id pgtype.UUID) (CryptoConversion, error) {
	row := q.db.QueryRow(ctx, getConversionForUpdate, id)
	var i CryptoConversion
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.SourceAsset,
		&i.DestinationAsset,
		&i.SourceAmount,
		&i.SimulationScenario,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.RoutingMetadata,
		&i.PolicyVersion,
		&i.ReservationLedgerTransactionID,
		&i.ComplianceCaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getConversionRequest = `-- name: GetConversionRequest :one
SELECT customer_reference, idempotency_key, request_hash, conversion_id, created_at
FROM crypto.conversion_requests
WHERE customer_reference = $1
  AND idempotency_key = $2
`

type GetConversionRequestParams struct {
	CustomerReference string `json:"customer_reference"`
	IdempotencyKey    string `json:"idempotency_key"`
}

func (q *Queries) GetConversionRequest(ctx context.Context, arg GetConversionRequestParams) (CryptoConversionRequest, error) {
	row := q.db.QueryRow(ctx, getConversionRequest, arg.CustomerReference, arg.IdempotencyKey)
	var i CryptoConversionRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ConversionID,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerProfile = `-- name: GetCustomerProfile :one
SELECT customer_reference, paper_account_id, cash_ledger_account_id, policy_version, created_at, version
FROM crypto.customer_profiles
WHERE customer_reference = $1
`

func (q *Queries) GetCustomerProfile(ctx context.Context, customerReference string) (CryptoCustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfile, customerReference)
	var i CryptoCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getCustomerProfileForUpdate = `-- name: GetCustomerProfileForUpdate :one
SELECT customer_reference, paper_account_id, cash_ledger_account_id, policy_version, created_at, version
FROM crypto.customer_profiles
WHERE customer_reference = $1
FOR UPDATE
`

func (q *Queries) GetCustomerProfileForUpdate(ctx context.Context, customerReference string) (CryptoCustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfileForUpdate, customerReference)
	var i CryptoCustomerProfile
	err := row.Scan(
		&i.CustomerReference,
		&i.PaperAccountID,
		&i.CashLedgerAccountID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getDeposit = `-- name: GetDeposit :one
SELECT id, customer_reference, deposit_address_id, asset_symbol, network_code, quantity, status, provider, provider_transaction_id, ledger_transaction_id, reason_code, created_at, updated_at, version
FROM crypto.deposits
WHERE id = $1
`

func (q *Queries) GetDeposit(ctx context.Context, id pgtype.UUID) (CryptoDeposit, error) {
	row := q.db.QueryRow(ctx, getDeposit, id)
	var i CryptoDeposit
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.DepositAddressID,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Quantity,
		&i.Status,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.LedgerTransactionID,
		&i.ReasonCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getDepositAddress = `-- name: GetDepositAddress :one
SELECT id, customer_reference, asset_symbol, network_code, provider, external_address, memo, status, created_at
FROM crypto.deposit_addresses
WHERE id = $1
`

func (q *Queries) GetDepositAddress(ctx context.Context, id pgtype.UUID) (CryptoDepositAddress, error) {
	row := q.db.QueryRow(ctx, getDepositAddress, id)
	var i CryptoDepositAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Provider,
		&i.ExternalAddress,
		&i.Memo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDepositAddressByAssetNetwork = `-- name: GetDepositAddressByAssetNetwork :one
SELECT id, customer_reference, asset_symbol, network_code, provider, external_address, memo, status, created_at
FROM crypto.deposit_addresses
WHERE customer_reference = $1
  AND asset_symbol = $2
  AND network_code = $3
`

type GetDepositAddressByAssetNetworkParams struct {
	CustomerReference string `json:"customer_reference"`
	AssetSymbol       string `json:"asset_symbol"`
	NetworkCode       string `json:"network_code"`
}

func (q *Queries) GetDepositAddressByAssetNetwork(ctx context.Context, arg GetDepositAddressByAssetNetworkParams) (CryptoDepositAddress, error) {
	row := q.db.QueryRow(ctx, getDepositAddressByAssetNetwork, arg.CustomerReference, arg.AssetSymbol, arg.NetworkCode)
	var i CryptoDepositAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Provider,
		&i.ExternalAddress,
		&i.Memo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDepositAddressRequest = `-- name: GetDepositAddressRequest :one
SELECT customer_reference, idempotency_key, request_hash, deposit_address_id, created_at
FROM crypto.deposit_address_requests
WHERE customer_reference = $1
  AND idempotency_key = $2
`

type GetDepositAddressRequestParams struct {
	CustomerReference string `json:"customer_reference"`
	IdempotencyKey    string `json:"idempotency_key"`
}

func (q *Queries) GetDepositAddressRequest(ctx context.Context, arg GetDepositAddressRequestParams) (CryptoDepositAddressRequest, error) {
	row := q.db.QueryRow(ctx, getDepositAddressRequest, arg.CustomerReference, arg.IdempotencyKey)
	var i CryptoDepositAddressRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.DepositAddressID,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT policy_version, platform_fee_rate, conversion_review_single_usd, conversion_review_rolling_usd, conversion_review_window_days, address_cooling_base_hours, address_cooling_device_hours, address_cooling_security_hours, address_cooling_recovery_hours, address_cooling_max_hours, quote_max_age_seconds, effective_at, active, created_at
FROM crypto.policies
WHERE policy_version = $1
`

func (q *Queries) GetPolicy(ctx context.Context, policyVersion string) (CryptoPolicy, error) {
	row := q.db.QueryRow(ctx, getPolicy, policyVersion)
	var i CryptoPolicy
	err := row.Scan(
		&i.PolicyVersion,
		&i.PlatformFeeRate,
		&i.ConversionReviewSingleUsd,
		&i.ConversionReviewRollingUsd,
		&i.ConversionReviewWindowDays,
		&i.AddressCoolingBaseHours,
		&i.AddressCoolingDeviceHours,
		&i.AddressCoolingSecurityHours,
		&i.AddressCoolingRecoveryHours,
		&i.AddressCoolingMaxHours,
		&i.QuoteMaxAgeSeconds,
		&i.EffectiveAt,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderEvent = `-- name: GetProviderEvent :one
SELECT provider, external_event_id, resource_type, resource_id, event_type, payload_hash, domain_record_id, processed_at
FROM crypto.provider_events
WHERE provider = $1
  AND external_event_id = $2
`

type GetProviderEventParams struct {
	Provider        string `json:"provider"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (CryptoProviderEvent, error) {
	row := q.db.QueryRow(ctx, getProviderEvent, arg.Provider, arg.ExternalEventID)
	var i CryptoProviderEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.ResourceType,
		&i.ResourceID,
		&i.EventType,
		&i.PayloadHash,
		&i.DomainRecordID,
		&i.ProcessedAt,
	)
	return i, err
}

const getWithdrawal = `-- name: GetWithdrawal :one
SELECT id, customer_reference, withdrawal_address_id, asset_symbol, network_code, quantity, status, reason_code, next_action, provider, provider_withdrawal_id, reservation_ledger_transaction_id, broadcast_ledger_transaction_id, reservation_reversal_transaction_id, broadcast_reversal_transaction_id, policy_version, created_at, updated_at, version
FROM crypto.withdrawals
WHERE id = $1
`

func (q *Queries) GetWithdrawal(ctx context.Context, id pgtype.UUID) (CryptoWithdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawal, id)
	var i CryptoWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.WithdrawalAddressID,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Quantity,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.Provider,
		&i.ProviderWithdrawalID,
		&i.ReservationLedgerTransactionID,
		&i.BroadcastLedgerTransactionID,
		&i.ReservationReversalTransactionID,
		&i.BroadcastReversalTransactionID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getWithdrawalAddress = `-- name: GetWithdrawalAddress :one
SELECT id, customer_reference, asset_symbol, network_code, external_address, label, status, risk_level, cooling_until, cooling_reason, policy_version, created_at, updated_at, version
FROM crypto.withdrawal_addresses
WHERE id = $1
`

func (q *Queries) GetWithdrawalAddress(ctx context.Context, id pgtype.UUID) (CryptoWithdrawalAddress, error) {
	row := q.db.QueryRow(ctx, getWithdrawalAddress, id)
	var i CryptoWithdrawalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.ExternalAddress,
		&i.Label,
		&i.Status,
		&i.RiskLevel,
		&i.CoolingUntil,
		&i.CoolingReason,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getWithdrawalAddressForUpdate = `-- name: GetWithdrawalAddressForUpdate :one
SELECT id, customer_reference, asset_symbol, network_code, external_address, label, status, risk_level, cooling_until, cooling_reason, policy_version, created_at, updated_at, version
FROM crypto.withdrawal_addresses
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetWithdrawalAddressForUpdate(ctx context.Context, id pgtype.UUID) (CryptoWithdrawalAddress, error) {
	row := q.db.QueryRow(ctx, getWithdrawalAddressForUpdate, id)
	var i CryptoWithdrawalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.ExternalAddress,
		&i.Label,
		&i.Status,
		&i.RiskLevel,
		&i.CoolingUntil,
		&i.CoolingReason,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getWithdrawalAddressRequest = `-- name: GetWithdrawalAddressRequest :one
SELECT customer_reference, idempotency_key, request_hash, address_id, created_at
FROM crypto.withdrawal_address_requests
WHERE customer_reference = $1
  AND idempotency_key = $2
`

type GetWithdrawalAddressRequestParams struct {
	CustomerReference string `json:"customer_reference"`
	IdempotencyKey    string `json:"idempotency_key"`
}

func (q *Queries) GetWithdrawalAddressRequest(ctx context.Context, arg GetWithdrawalAddressRequestParams) (CryptoWithdrawalAddressRequest, error) {
	row := q.db.QueryRow(ctx, getWithdrawalAddressRequest, arg.CustomerReference, arg.IdempotencyKey)
	var i CryptoWithdrawalAddressRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.AddressID,
		&i.CreatedAt,
	)
	return i, err
}

const getWithdrawalForUpdate = `-- name: GetWithdrawalForUpdate :one
SELECT id, customer_reference, withdrawal_address_id, asset_symbol, network_code, quantity, status, reason_code, next_action, provider, provider_withdrawal_id, reservation_ledger_transaction_id, broadcast_ledger_transaction_id, reservation_reversal_transaction_id, broadcast_reversal_transaction_id, policy_version, created_at, updated_at, version
FROM crypto.withdrawals
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetWithdrawalForUpdate(ctx context.Context, id pgtype.UUID) (CryptoWithdrawal, error) {
	row := q.db.QueryRow(ctx, getWithdrawalForUpdate, id)
	var i CryptoWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.WithdrawalAddressID,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Quantity,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.Provider,
		&i.ProviderWithdrawalID,
		&i.ReservationLedgerTransactionID,
		&i.BroadcastLedgerTransactionID,
		&i.ReservationReversalTransactionID,
		&i.BroadcastReversalTransactionID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getWithdrawalRequest = `-- name: GetWithdrawalRequest :one
SELECT customer_reference, idempotency_key, request_hash, withdrawal_id, created_at
FROM crypto.withdrawal_requests
WHERE customer_reference = $1
  AND idempotency_key = $2
`

type GetWithdrawalRequestParams struct {
	CustomerReference string `json:"customer_reference"`
	IdempotencyKey    string `json:"idempotency_key"`
}

func (q *Queries) GetWithdrawalRequest(ctx context.Context, arg GetWithdrawalRequestParams) (CryptoWithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, getWithdrawalRequest, arg.CustomerReference, arg.IdempotencyKey)
	var i CryptoWithdrawalRequest
	err := row.Scan(
		&i.CustomerReference,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.WithdrawalID,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssetLedgerAccounts = `-- name: InsertAssetLedgerAccounts :one
INSERT INTO crypto.asset_ledger_accounts (
    customer_reference,
    asset_symbol,
    customer_ledger_account_id,
    custody_inventory_ledger_account_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (customer_reference, asset_symbol) DO NOTHING
RETURNING customer_reference, asset_symbol, customer_ledger_account_id, custody_inventory_ledger_account_id, created_at
`

type InsertAssetLedgerAccountsParams struct {
	CustomerReference               string      `json:"customer_reference"`
	AssetSymbol                     string      `json:"asset_symbol"`
	CustomerLedgerAccountID         pgtype.UUID `json:"customer_ledger_account_id"`
	CustodyInventoryLedgerAccountID pgtype.UUID `json:"custody_inventory_ledger_account_id"`
}

func (q *Queries) InsertAssetLedgerAccounts(ctx context.Context, arg InsertAssetLedgerAccountsParams) (CryptoAssetLedgerAccount, error) {
	row := q.db.QueryRow(ctx, insertAssetLedgerAccounts,
		arg.CustomerReference,
		arg.AssetSymbol,
		arg.CustomerLedgerAccountID,
		arg.CustodyInventoryLedgerAccountID,
	)
	var i CryptoAssetLedgerAccount
	err := row.Scan(
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.CustomerLedgerAccountID,
		&i.CustodyInventoryLedgerAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const insertChildOrder = `-- name: InsertChildOrder :one
INSERT INTO crypto.child_orders (
    id,
    leg_id,
    child_sequence,
    venue_code,
    client_order_id,
    provider_order_id,
    requested_quantity,
    filled_quantity,
    quote_bid,
    quote_ask,
    venue_fee_rate,
    effective_unit_price,
    execution_price,
    gross_usd,
    venue_fee_usd,
    status,
    failure_code,
    quote_observed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
RETURNING id, leg_id, child_sequence, venue_code, client_order_id, provider_order_id, requested_quantity, filled_quantity, quote_bid, quote_ask, venue_fee_rate, effective_unit_price, execution_price, gross_usd, venue_fee_usd, status, failure_code, quote_observed_at, created_at
`

type InsertChildOrderParams struct {
	ID                 pgtype.UUID        `json:"id"`
	LegID              pgtype.UUID        `json:"leg_id"`
	ChildSequence      int16              `json:"child_sequence"`
	VenueCode          string             `json:"venue_code"`
	ClientOrderID      string             `json:"client_order_id"`
	ProviderOrderID    pgtype.Text        `json:"provider_order_id"`
	RequestedQuantity  money.Decimal      `json:"requested_quantity"`
	FilledQuantity     money.Decimal      `json:"filled_quantity"`
	QuoteBid           money.Decimal      `json:"quote_bid"`
	QuoteAsk           money.Decimal      `json:"quote_ask"`
	VenueFeeRate       money.Decimal      `json:"venue_fee_rate"`
	EffectiveUnitPrice money.Decimal      `json:"effective_unit_price"`
	ExecutionPrice     money.Decimal      `json:"execution_price"`
	GrossUsd           money.Decimal      `json:"gross_usd"`
	VenueFeeUsd        money.Decimal      `json:"venue_fee_usd"`
	Status             string             `json:"status"`
	FailureCode        pgtype.Text        `json:"failure_code"`
	QuoteObservedAt    pgtype.Timestamptz `json:"quote_observed_at"`
}

func (q *Queries) InsertChildOrder(ctx context.Context, arg InsertChildOrderParams) (CryptoChildOrder, error) {
	row := q.db.QueryRow(ctx, insertChildOrder,
		arg.ID,
		arg.LegID,
		arg.ChildSequence,
		arg.VenueCode,
		arg.ClientOrderID,
		arg.ProviderOrderID,
		arg.RequestedQuantity,
		arg.FilledQuantity,
		arg.QuoteBid,
		arg.QuoteAsk,
		arg.VenueFeeRate,
		arg.EffectiveUnitPrice,
		arg.ExecutionPrice,
		arg.GrossUsd,
		arg.VenueFeeUsd,
		arg.Status,
		arg.FailureCode,
		arg.QuoteObservedAt,
	)
	var i CryptoChildOrder
	err := row.Scan(
		&i.ID,
		&i.LegID,
		&i.ChildSequence,
		&i.VenueCode,
		&i.ClientOrderID,
		&i.ProviderOrderID,
		&i.RequestedQuantity,
		&i.FilledQuantity,
		&i.QuoteBid,
		&i.QuoteAsk,
		&i.VenueFeeRate,
		&i.EffectiveUnitPrice,
		&i.ExecutionPrice,
		&i.GrossUsd,
		&i.VenueFeeUsd,
		&i.Status,
		&i.FailureCode,
		&i.QuoteObservedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertConversionRequest = `-- name: InsertConversionRequest :one
INSERT INTO crypto.conversion_requests (
    customer_reference,
    idempotency_key,
    request_hash,
    conversion_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (customer_reference, idempotency_key) DO NOTHING
RETURNING conversion_id
`

type InsertConversionRequestParams struct {
	CustomerReference string      `json:"customer_reference"`
	IdempotencyKey    string      `json:"idempotency_key"`
	RequestHash       string      `json:"request_hash"`
	ConversionID      pgtype.UUID `json:"conversion_id"`
}

func (q *Queries) InsertConversionRequest(ctx context.Context, arg InsertConversionRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertConversionRequest,
		arg.CustomerReference,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ConversionID,
	)
	var conversion_id pgtype.UUID
	err := row.Scan(&conversion_id)
	return conversion_id, err
}

const insertDepositAddressRequest = `-- name: InsertDepositAddressRequest :one
INSERT INTO crypto.deposit_address_requests (
    customer_reference,
    idempotency_key,
    request_hash,
    deposit_address_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (customer_reference, idempotency_key) DO NOTHING
RETURNING deposit_address_id
`

type InsertDepositAddressRequestParams struct {
	CustomerReference string      `json:"customer_reference"`
	IdempotencyKey    string      `json:"idempotency_key"`
	RequestHash       string      `json:"request_hash"`
	DepositAddressID  pgtype.UUID `json:"deposit_address_id"`
}

func (q *Queries) InsertDepositAddressRequest(ctx context.Context, arg InsertDepositAddressRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDepositAddressRequest,
		arg.CustomerReference,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.DepositAddressID,
	)
	var deposit_address_id pgtype.UUID
	err := row.Scan(&deposit_address_id)
	return deposit_address_id, err
}

const insertFill = `-- name: InsertFill :one
INSERT INTO crypto.fills (
    id,
    child_order_id,
    venue_code,
    external_fill_id,
    quantity,
    price,
    gross_usd,
    venue_fee_usd,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, child_order_id, venue_code, external_fill_id, quantity, price, gross_usd, venue_fee_usd, occurred_at, created_at
`

type InsertFillParams struct {
	ID             pgtype.UUID        `json:"id"`
	ChildOrderID   pgtype.UUID        `json:"child_order_id"`
	VenueCode      string             `json:"venue_code"`
	ExternalFillID string             `json:"external_fill_id"`
	Quantity       money.Decimal      `json:"quantity"`
	Price          money.Decimal      `json:"price"`
	GrossUsd       money.Decimal      `json:"gross_usd"`
	VenueFeeUsd    money.Decimal      `json:"venue_fee_usd"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertFill(ctx context.Context, arg InsertFillParams) (CryptoFill, error) {
	row := q.db.QueryRow(ctx, insertFill,
		arg.ID,
		arg.ChildOrderID,
		arg.VenueCode,
		arg.ExternalFillID,
		arg.Quantity,
		arg.Price,
		arg.GrossUsd,
		arg.VenueFeeUsd,
		arg.OccurredAt,
	)
	var i CryptoFill
	err := row.Scan(
		&i.ID,
		&i.ChildOrderID,
		&i.VenueCode,
		&i.ExternalFillID,
		&i.Quantity,
		&i.Price,
		&i.GrossUsd,
		&i.VenueFeeUsd,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertLeg = `-- name: InsertLeg :one
INSERT INTO crypto.legs (
    id,
    conversion_id,
    leg_sequence,
    side,
    asset_symbol,
    input_amount,
    filled_quantity,
    reference_price,
    average_execution_price,
    gross_usd,
    venue_fee_usd,
    platform_fee_usd,
    final_customer_usd,
    price_improvement_usd,
    status,
    failure_code,
    ledger_transaction_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
RETURNING id, conversion_id, leg_sequence, side, asset_symbol, quote_currency, input_amount, filled_quantity, reference_price, average_execution_price, gross_usd, venue_fee_usd, platform_fee_usd, final_customer_usd, price_improvement_usd, status, failure_code, ledger_transaction_id, created_at
`

type InsertLegParams struct {
	ID                    pgtype.UUID   `json:"id"`
	ConversionID          pgtype.UUID   `json:"conversion_id"`
	LegSequence           int16         `json:"leg_sequence"`
	Side                  string        `json:"side"`
	AssetSymbol           string        `json:"asset_symbol"`
	InputAmount           money.Decimal `json:"input_amount"`
	FilledQuantity        money.Decimal `json:"filled_quantity"`
	ReferencePrice        money.Decimal `json:"reference_price"`
	AverageExecutionPrice money.Decimal `json:"average_execution_price"`
	GrossUsd              money.Decimal `json:"gross_usd"`
	VenueFeeUsd           money.Decimal `json:"venue_fee_usd"`
	PlatformFeeUsd        money.Decimal `json:"platform_fee_usd"`
	FinalCustomerUsd      money.Decimal `json:"final_customer_usd"`
	PriceImprovementUsd   money.Decimal `json:"price_improvement_usd"`
	Status                string        `json:"status"`
	FailureCode           pgtype.Text   `json:"failure_code"`
	LedgerTransactionID   pgtype.UUID   `json:"ledger_transaction_id"`
}

func (q *Queries) InsertLeg(ctx context.Context, arg InsertLegParams) (CryptoLeg, error) {
	row := q.db.QueryRow(ctx, insertLeg,
		arg.ID,
		arg.ConversionID,
		arg.LegSequence,
		arg.Side,
		arg.AssetSymbol,
		arg.InputAmount,
		arg.FilledQuantity,
		arg.ReferencePrice,
		arg.AverageExecutionPrice,
		arg.GrossUsd,
		arg.VenueFeeUsd,
		arg.PlatformFeeUsd,
		arg.FinalCustomerUsd,
		arg.PriceImprovementUsd,
		arg.Status,
		arg.FailureCode,
		arg.LedgerTransactionID,
	)
	var i CryptoLeg
	err := row.Scan(
		&i.ID,
		&i.ConversionID,
		&i.LegSequence,
		&i.Side,
		&i.AssetSymbol,
		&i.QuoteCurrency,
		&i.InputAmount,
		&i.FilledQuantity,
		&i.ReferencePrice,
		&i.AverageExecutionPrice,
		&i.GrossUsd,
		&i.VenueFeeUsd,
		&i.PlatformFeeUsd,
		&i.FinalCustomerUsd,
		&i.PriceImprovementUsd,
		&i.Status,
		&i.FailureCode,
		&i.LedgerTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderEvent = `-- name: InsertProviderEvent :one
INSERT INTO crypto.provider_events (
    provider,
    external_event_id,
    resource_type,
    resource_id,
    event_type,
    payload_hash,
    domain_record_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (provider, external_event_id) DO NOTHING
RETURNING provider, external_event_id, resource_type, resource_id, event_type, payload_hash, domain_record_id, processed_at
`

type InsertProviderEventParams struct {
	Provider        string      `json:"provider"`
	ExternalEventID string      `json:"external_event_id"`
	ResourceType    string      `json:"resource_type"`
	ResourceID      pgtype.UUID `json:"resource_id"`
	EventType       string      `json:"event_type"`
	PayloadHash     string      `json:"payload_hash"`
	DomainRecordID  pgtype.UUID `json:"domain_record_id"`
}

func (q *Queries) InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (CryptoProviderEvent, error) {
	row := q.db.QueryRow(ctx, insertProviderEvent,
		arg.Provider,
		arg.ExternalEventID,
		arg.ResourceType,
		arg.ResourceID,
		arg.EventType,
		arg.PayloadHash,
		arg.DomainRecordID,
	)
	var i CryptoProviderEvent
	err := row.Scan(
		&i.Provider,
		&i.ExternalEventID,
		&i.ResourceType,
		&i.ResourceID,
		&i.EventType,
		&i.PayloadHash,
		&i.DomainRecordID,
		&i.ProcessedAt,
	)
	return i, err
}

const insertWithdrawalAddressEvent = `-- name: InsertWithdrawalAddressEvent :one
INSERT INTO crypto.withdrawal_address_events (
    address_id,
    from_status,
    to_status,
    actor_type,
    actor_id,
    reason_code,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, address_id, from_status, to_status, actor_type, actor_id, reason_code, metadata, occurred_at
`

type InsertWithdrawalAddressEventParams struct {
	AddressID  pgtype.UUID `json:"address_id"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	ActorType  string      `json:"actor_type"`
	ActorID    string      `json:"actor_id"`
	ReasonCode string      `json:"reason_code"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) InsertWithdrawalAddressEvent(ctx context.Context, arg InsertWithdrawalAddressEventParams) (CryptoWithdrawalAddressEvent, error) {
	row := q.db.QueryRow(ctx, insertWithdrawalAddressEvent,
		arg.AddressID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorType,
		arg.ActorID,
		arg.ReasonCode,
		arg.Metadata,
	)
	var i CryptoWithdrawalAddressEvent
	err := row.Scan(
		&i.ID,
		&i.AddressID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorType,
		&i.ActorID,
		&i.ReasonCode,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const insertWithdrawalAddressRequest = `-- name: InsertWithdrawalAddressRequest :one
INSERT INTO crypto.withdrawal_address_requests (
    customer_reference,
    idempotency_key,
    request_hash,
    address_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (customer_reference, idempotency_key) DO NOTHING
RETURNING address_id
`

type InsertWithdrawalAddressRequestParams struct {
	CustomerReference string      `json:"customer_reference"`
	IdempotencyKey    string      `json:"idempotency_key"`
	RequestHash       string      `json:"request_hash"`
	AddressID         pgtype.UUID `json:"address_id"`
}

func (q *Queries) InsertWithdrawalAddressRequest(ctx context.Context, arg InsertWithdrawalAddressRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertWithdrawalAddressRequest,
		arg.CustomerReference,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.AddressID,
	)
	var address_id pgtype.UUID
	err := row.Scan(&address_id)
	return address_id, err
}

const insertWithdrawalRequest = `-- name: InsertWithdrawalRequest :one
INSERT INTO crypto.withdrawal_requests (
    customer_reference,
    idempotency_key,
    request_hash,
    withdrawal_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (customer_reference, idempotency_key) DO NOTHING
RETURNING withdrawal_id
`

type InsertWithdrawalRequestParams struct {
	CustomerReference string      `json:"customer_reference"`
	IdempotencyKey    string      `json:"idempotency_key"`
	RequestHash       string      `json:"request_hash"`
	WithdrawalID      pgtype.UUID `json:"withdrawal_id"`
}

func (q *Queries) InsertWithdrawalRequest(ctx context.Context, arg InsertWithdrawalRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertWithdrawalRequest,
		arg.CustomerReference,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.WithdrawalID,
	)
	var withdrawal_id pgtype.UUID
	err := row.Scan(&withdrawal_id)
	return withdrawal_id, err
}

const listAssetNetworks = `-- name: ListAssetNetworks :many
SELECT
    asset_networks.asset_symbol,
    asset_networks.network_code,
    networks.display_name,
    asset_networks.deposit_enabled,
    asset_networks.withdrawal_enabled,
    asset_networks.native_deployment
FROM crypto.asset_networks AS asset_networks
JOIN crypto.networks AS networks
    ON networks.network_code = asset_networks.network_code
WHERE asset_networks.asset_symbol = $1
  AND networks.active
ORDER BY asset_networks.network_code
`

type ListAssetNetworksRow struct {
	AssetSymbol       string `json:"asset_symbol"`
	NetworkCode       string `json:"network_code"`
	DisplayName       string `json:"display_name"`
	DepositEnabled    bool   `json:"deposit_enabled"`
	WithdrawalEnabled bool   `json:"withdrawal_enabled"`
	NativeDeployment  bool   `json:"native_deployment"`
}

func (q *Queries) ListAssetNetworks(ctx context.Context, assetSymbol string) ([]ListAssetNetworksRow, error) {
	rows, err := q.db.Query(ctx, listAssetNetworks, assetSymbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetNetworksRow
	for rows.Next() {
		var i ListAssetNetworksRow
		if err := rows.Scan(
			&i.AssetSymbol,
			&i.NetworkCode,
			&i.DisplayName,
			&i.DepositEnabled,
			&i.WithdrawalEnabled,
			&i.NativeDeployment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT symbol, display_name, is_stablecoin, tradable, precision, created_at
FROM crypto.assets
WHERE tradable
ORDER BY symbol
`

func (q *Queries) ListAssets(ctx context.Context) ([]CryptoAsset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoAsset
	for rows.Next() {
		var i CryptoAsset
		if err := rows.Scan(
			&i.Symbol,
			&i.DisplayName,
			&i.IsStablecoin,
			&i.Tradable,
			&i.Precision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildOrders = `-- name: ListChildOrders :many
SELECT child_orders.id, child_orders.leg_id, child_orders.child_sequence, child_orders.venue_code, child_orders.client_order_id, child_orders.provider_order_id, child_orders.requested_quantity, child_orders.filled_quantity, child_orders.quote_bid, child_orders.quote_ask, child_orders.venue_fee_rate, child_orders.effective_unit_price, child_orders.execution_price, child_orders.gross_usd, child_orders.venue_fee_usd, child_orders.status, child_orders.failure_code, child_orders.quote_observed_at, child_orders.created_at
FROM crypto.child_orders AS child_orders
JOIN crypto.legs AS legs ON legs.id = child_orders.leg_id
WHERE legs.conversion_id = $1
ORDER BY legs.leg_sequence, child_orders.child_sequence
`

func (q *Queries) ListChildOrders(ctx context.Context, conversionID pgtype.UUID) ([]CryptoChildOrder, error) {
	rows, err := q.db.Query(ctx, listChildOrders, conversionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoChildOrder
	for rows.Next() {
		var i CryptoChildOrder
		if err := rows.Scan(
			&i.ID,
			&i.LegID,
			&i.ChildSequence,
			&i.VenueCode,
			&i.ClientOrderID,
			&i.ProviderOrderID,
			&i.RequestedQuantity,
			&i.FilledQuantity,
			&i.QuoteBid,
			&i.QuoteAsk,
			&i.VenueFeeRate,
			&i.EffectiveUnitPrice,
			&i.ExecutionPrice,
			&i.GrossUsd,
			&i.VenueFeeUsd,
			&i.Status,
			&i.FailureCode,
			&i.QuoteObservedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversions = `-- name: ListConversions :many
SELECT id, customer_reference, source_asset, destination_asset, source_amount, simulation_scenario, status, reason_code, next_action, routing_metadata, policy_version, reservation_ledger_transaction_id, compliance_case_id, created_at, updated_at, version
FROM crypto.conversions
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListConversionsParams struct {
	CustomerReference string `json:"customer_reference"`
	PageSize          int32  `json:"page_size"`
}

func (q *Queries) ListConversions(ctx context.Context, arg ListConversionsParams) ([]CryptoConversion, error) {
	rows, err := q.db.Query(ctx, listConversions, arg.CustomerReference, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoConversion
	for rows.Next() {
		var i CryptoConversion
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.SourceAsset,
			&i.DestinationAsset,
			&i.SourceAmount,
			&i.SimulationScenario,
			&i.Status,
			&i.ReasonCode,
			&i.NextAction,
			&i.RoutingMetadata,
			&i.PolicyVersion,
			&i.ReservationLedgerTransactionID,
			&i.ComplianceCaseID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositAddresses = `-- name: ListDepositAddresses :many
SELECT id, customer_reference, asset_symbol, network_code, provider, external_address, memo, status, created_at
FROM crypto.deposit_addresses
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDepositAddresses(ctx context.Context, customerReference string) ([]CryptoDepositAddress, error) {
	rows, err := q.db.Query(ctx, listDepositAddresses, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoDepositAddress
	for rows.Next() {
		var i CryptoDepositAddress
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.AssetSymbol,
			&i.NetworkCode,
			&i.Provider,
			&i.ExternalAddress,
			&i.Memo,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeposits = `-- name: ListDeposits :many
SELECT id, customer_reference, deposit_address_id, asset_symbol, network_code, quantity, status, provider, provider_transaction_id, ledger_transaction_id, reason_code, created_at, updated_at, version
FROM crypto.deposits
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListDepositsParams struct {
	CustomerReference string `json:"customer_reference"`
	PageSize          int32  `json:"page_size"`
}

func (q *Queries) ListDeposits(ctx context.Context, arg ListDepositsParams) ([]CryptoDeposit, error) {
	rows, err := q.db.Query(ctx, listDeposits, arg.CustomerReference, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoDeposit
	for rows.Next() {
		var i CryptoDeposit
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.DepositAddressID,
			&i.AssetSymbol,
			&i.NetworkCode,
			&i.Quantity,
			&i.Status,
			&i.Provider,
			&i.ProviderTransactionID,
			&i.LedgerTransactionID,
			&i.ReasonCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFills = `-- name: ListFills :many
SELECT fills.id, fills.child_order_id, fills.venue_code, fills.external_fill_id, fills.quantity, fills.price, fills.gross_usd, fills.venue_fee_usd, fills.occurred_at, fills.created_at
FROM crypto.fills AS fills
JOIN crypto.child_orders AS child_orders ON child_orders.id = fills.child_order_id
JOIN crypto.legs AS legs ON legs.id = child_orders.leg_id
WHERE legs.conversion_id = $1
ORDER BY legs.leg_sequence, child_orders.child_sequence, fills.occurred_at, fills.id
`

func (q *Queries) ListFills(ctx context.Context, conversionID pgtype.UUID) ([]CryptoFill, error) {
	rows, err := q.db.Query(ctx, listFills, conversionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoFill
	for rows.Next() {
		var i CryptoFill
		if err := rows.Scan(
			&i.ID,
			&i.ChildOrderID,
			&i.VenueCode,
			&i.ExternalFillID,
			&i.Quantity,
			&i.Price,
			&i.GrossUsd,
			&i.VenueFeeUsd,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegs = `-- name: ListLegs :many
SELECT id, conversion_id, leg_sequence, side, asset_symbol, quote_currency, input_amount, filled_quantity, reference_price, average_execution_price, gross_usd, venue_fee_usd, platform_fee_usd, final_customer_usd, price_improvement_usd, status, failure_code, ledger_transaction_id, created_at
FROM crypto.legs
WHERE conversion_id = $1
ORDER BY leg_sequence
`

func (q *Queries) ListLegs(ctx context.Context, conversionID pgtype.UUID) ([]CryptoLeg, error) {
	rows, err := q.db.Query(ctx, listLegs, conversionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoLeg
	for rows.Next() {
		var i CryptoLeg
		if err := rows.Scan(
			&i.ID,
			&i.ConversionID,
			&i.LegSequence,
			&i.Side,
			&i.AssetSymbol,
			&i.QuoteCurrency,
			&i.InputAmount,
			&i.FilledQuantity,
			&i.ReferencePrice,
			&i.AverageExecutionPrice,
			&i.GrossUsd,
			&i.VenueFeeUsd,
			&i.PlatformFeeUsd,
			&i.FinalCustomerUsd,
			&i.PriceImprovementUsd,
			&i.Status,
			&i.FailureCode,
			&i.LedgerTransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolioBalances = `-- name: ListPortfolioBalances :many
SELECT
    accounts.asset_symbol,
    COALESCE(settled.debit_balance, 0)::NUMERIC(38, 18) AS settled,
    COALESCE(held.debit_balance, 0)::NUMERIC(38, 18) AS held,
    COALESCE(frozen.debit_balance, 0)::NUMERIC(38, 18) AS frozen
FROM crypto.asset_ledger_accounts AS accounts
LEFT JOIN ledger.account_balances AS settled
    ON settled.account_id = accounts.customer_ledger_account_id
    AND settled.currency = accounts.asset_symbol
    AND settled.balance_dimension = 'SETTLED'
LEFT JOIN ledger.account_balances AS held
    ON held.account_id = accounts.customer_ledger_account_id
    AND held.currency = accounts.asset_symbol
    AND held.balance_dimension = 'HELD'
LEFT JOIN ledger.account_balances AS frozen
    ON frozen.account_id = accounts.customer_ledger_account_id
    AND frozen.currency = accounts.asset_symbol
    AND frozen.balance_dimension = 'FROZEN'
WHERE accounts.customer_reference = $1
ORDER BY accounts.asset_symbol
`

type ListPortfolioBalancesRow struct {
	AssetSymbol string        `json:"asset_symbol"`
	Settled     money.Decimal `json:"settled"`
	Held        money.Decimal `json:"held"`
	Frozen      money.Decimal `json:"frozen"`
}

func (q *Queries) ListPortfolioBalances(ctx context.Context, customerReference string) ([]ListPortfolioBalancesRow, error) {
	rows, err := q.db.Query(ctx, listPortfolioBalances, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPortfolioBalancesRow
	for rows.Next() {
		var i ListPortfolioBalancesRow
		if err := rows.Scan(
			&i.AssetSymbol,
			&i.Settled,
			&i.Held,
			&i.Frozen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenues = `-- name: ListVenues :many
SELECT venue_code, display_name, mode, enabled, created_at
FROM crypto.venues
WHERE enabled
ORDER BY venue_code
`

func (q *Queries) ListVenues(ctx context.Context) ([]CryptoVenue, error) {
	rows, err := q.db.Query(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoVenue
	for rows.Next() {
		var i CryptoVenue
		if err := rows.Scan(
			&i.VenueCode,
			&i.DisplayName,
			&i.Mode,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalAddresses = `-- name: ListWithdrawalAddresses :many
SELECT id, customer_reference, asset_symbol, network_code, external_address, label, status, risk_level, cooling_until, cooling_reason, policy_version, created_at, updated_at, version
FROM crypto.withdrawal_addresses
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListWithdrawalAddresses(ctx context.Context, customerReference string) ([]CryptoWithdrawalAddress, error) {
	rows, err := q.db.Query(ctx, listWithdrawalAddresses, customerReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoWithdrawalAddress
	for rows.Next() {
		var i CryptoWithdrawalAddress
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.AssetSymbol,
			&i.NetworkCode,
			&i.ExternalAddress,
			&i.Label,
			&i.Status,
			&i.RiskLevel,
			&i.CoolingUntil,
			&i.CoolingReason,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawals = `-- name: ListWithdrawals :many
SELECT id, customer_reference, withdrawal_address_id, asset_symbol, network_code, quantity, status, reason_code, next_action, provider, provider_withdrawal_id, reservation_ledger_transaction_id, broadcast_ledger_transaction_id, reservation_reversal_transaction_id, broadcast_reversal_transaction_id, policy_version, created_at, updated_at, version
FROM crypto.withdrawals
WHERE customer_reference = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListWithdrawalsParams struct {
	CustomerReference string `json:"customer_reference"`
	PageSize          int32  `json:"page_size"`
}

func (q *Queries) ListWithdrawals(ctx context.Context, arg ListWithdrawalsParams) ([]CryptoWithdrawal, error) {
	rows, err := q.db.Query(ctx, listWithdrawals, arg.CustomerReference, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoWithdrawal
	for rows.Next() {
		var i CryptoWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.CustomerReference,
			&i.WithdrawalAddressID,
			&i.AssetSymbol,
			&i.NetworkCode,
			&i.Quantity,
			&i.Status,
			&i.ReasonCode,
			&i.NextAction,
			&i.Provider,
			&i.ProviderWithdrawalID,
			&i.ReservationLedgerTransactionID,
			&i.BroadcastLedgerTransactionID,
			&i.ReservationReversalTransactionID,
			&i.BroadcastReversalTransactionID,
			&i.PolicyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumRecentCryptoToUSD = `-- name: SumRecentCryptoToUSD :one
SELECT COALESCE(SUM(legs.final_customer_usd), 0)::NUMERIC(38, 18) AS total
FROM crypto.legs AS legs
JOIN crypto.conversions AS conversions ON conversions.id = legs.conversion_id
WHERE conversions.customer_reference = $1
  AND legs.side = 'SELL'
  AND legs.created_at >= $2
  AND legs.status IN ('FILLED', 'PARTIALLY_FILLED')
`

type SumRecentCryptoToUSDParams struct {
	CustomerReference string             `json:"customer_reference"`
	SinceTime         pgtype.Timestamptz `json:"since_time"`
}

func (q *Queries) SumRecentCryptoToUSD(ctx context.Context, arg SumRecentCryptoToUSDParams) (money.Decimal, error) {
	row := q.db.QueryRow(ctx, sumRecentCryptoToUSD, arg.CustomerReference, arg.SinceTime)
	var total money.Decimal
	err := row.Scan(&total)
	return total, err
}

const transitionWithdrawal = `-- name: TransitionWithdrawal :one
UPDATE crypto.withdrawals
SET status = $1,
    reason_code = $2,
    next_action = $3,
    broadcast_ledger_transaction_id = $4,
    reservation_reversal_transaction_id = $5,
    broadcast_reversal_transaction_id = $6
WHERE id = $7
RETURNING id, customer_reference, withdrawal_address_id, asset_symbol, network_code, quantity, status, reason_code, next_action, provider, provider_withdrawal_id, reservation_ledger_transaction_id, broadcast_ledger_transaction_id, reservation_reversal_transaction_id, broadcast_reversal_transaction_id, policy_version, created_at, updated_at, version
`

type TransitionWithdrawalParams struct {
	Status                           string      `json:"status"`
	ReasonCode                       string      `json:"reason_code"`
	NextAction                       string      `json:"next_action"`
	BroadcastLedgerTransactionID     pgtype.UUID `json:"broadcast_ledger_transaction_id"`
	ReservationReversalTransactionID pgtype.UUID `json:"reservation_reversal_transaction_id"`
	BroadcastReversalTransactionID   pgtype.UUID `json:"broadcast_reversal_transaction_id"`
	ID                               pgtype.UUID `json:"id"`
}

func (q *Queries) TransitionWithdrawal(ctx context.Context, arg TransitionWithdrawalParams) (CryptoWithdrawal, error) {
	row := q.db.QueryRow(ctx, transitionWithdrawal,
		arg.Status,
		arg.ReasonCode,
		arg.NextAction,
		arg.BroadcastLedgerTransactionID,
		arg.ReservationReversalTransactionID,
		arg.BroadcastReversalTransactionID,
		arg.ID,
	)
	var i CryptoWithdrawal
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.WithdrawalAddressID,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.Quantity,
		&i.Status,
		&i.ReasonCode,
		&i.NextAction,
		&i.Provider,
		&i.ProviderWithdrawalID,
		&i.ReservationLedgerTransactionID,
		&i.BroadcastLedgerTransactionID,
		&i.ReservationReversalTransactionID,
		&i.BroadcastReversalTransactionID,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const transitionWithdrawalAddress = `-- name: TransitionWithdrawalAddress :one
UPDATE crypto.withdrawal_addresses
SET status = $1,
    risk_level = $2,
    cooling_until = $3,
    cooling_reason = $4
WHERE id = $5
RETURNING id, customer_reference, asset_symbol, network_code, external_address, label, status, risk_level, cooling_until, cooling_reason, policy_version, created_at, updated_at, version
`

type TransitionWithdrawalAddressParams struct {
	Status        string             `json:"status"`
	RiskLevel     string             `json:"risk_level"`
	CoolingUntil  pgtype.Timestamptz `json:"cooling_until"`
	CoolingReason string             `json:"cooling_reason"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) TransitionWithdrawalAddress(ctx context.Context, arg TransitionWithdrawalAddressParams) (CryptoWithdrawalAddress, error) {
	row := q.db.QueryRow(ctx, transitionWithdrawalAddress,
		arg.Status,
		arg.RiskLevel,
		arg.CoolingUntil,
		arg.CoolingReason,
		arg.ID,
	)
	var i CryptoWithdrawalAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerReference,
		&i.AssetSymbol,
		&i.NetworkCode,
		&i.ExternalAddress,
		&i.Label,
		&i.Status,
		&i.RiskLevel,
		&i.CoolingUntil,
		&i.CoolingReason,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
