// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type CryptoAsset struct {
	Symbol       string             `json:"symbol"`
	DisplayName  string             `json:"display_name"`
	IsStablecoin bool               `json:"is_stablecoin"`
	Tradable     bool               `json:"tradable"`
	Precision    int16              `json:"precision"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CryptoAssetLedgerAccount struct {
	CustomerReference               string             `json:"customer_reference"`
	AssetSymbol                     string             `json:"asset_symbol"`
	CustomerLedgerAccountID         pgtype.UUID        `json:"customer_ledger_account_id"`
	CustodyInventoryLedgerAccountID pgtype.UUID        `json:"custody_inventory_ledger_account_id"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
}

type CryptoAssetNetwork struct {
	AssetSymbol       string             `json:"asset_symbol"`
	NetworkCode       string             `json:"network_code"`
	NativeDeployment  bool               `json:"native_deployment"`
	DepositEnabled    bool               `json:"deposit_enabled"`
	WithdrawalEnabled bool               `json:"withdrawal_enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CryptoChildOrder struct {
	ID                 pgtype.UUID        `json:"id"`
	LegID              pgtype.UUID        `json:"leg_id"`
	ChildSequence      int16              `json:"child_sequence"`
	VenueCode          string             `json:"venue_code"`
	ClientOrderID      string             `json:"client_order_id"`
	ProviderOrderID    pgtype.Text        `json:"provider_order_id"`
	RequestedQuantity  money.Decimal      `json:"requested_quantity"`
	FilledQuantity     money.Decimal      `json:"filled_quantity"`
	QuoteBid           money.Decimal      `json:"quote_bid"`
	QuoteAsk           money.Decimal      `json:"quote_ask"`
	VenueFeeRate       money.Decimal      `json:"venue_fee_rate"`
	EffectiveUnitPrice money.Decimal      `json:"effective_unit_price"`
	ExecutionPrice     money.Decimal      `json:"execution_price"`
	GrossUsd           money.Decimal      `json:"gross_usd"`
	VenueFeeUsd        money.Decimal      `json:"venue_fee_usd"`
	Status             string             `json:"status"`
	FailureCode        pgtype.Text        `json:"failure_code"`
	QuoteObservedAt    pgtype.Timestamptz `json:"quote_observed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type CryptoConversion struct {
	ID                             pgtype.UUID        `json:"id"`
	CustomerReference              string             `json:"customer_reference"`
	SourceAsset                    string             `json:"source_asset"`
	DestinationAsset               string             `json:"destination_asset"`
	SourceAmount                   money.Decimal      `json:"source_amount"`
	SimulationScenario             string             `json:"simulation_scenario"`
	Status                         string             `json:"status"`
	ReasonCode                     pgtype.Text        `json:"reason_code"`
	NextAction                     string             `json:"next_action"`
	RoutingMetadata                []byte             `json:"routing_metadata"`
	PolicyVersion                  string             `json:"policy_version"`
	ReservationLedgerTransactionID pgtype.UUID        `json:"reservation_ledger_transaction_id"`
	ComplianceCaseID               pgtype.UUID        `json:"compliance_case_id"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	Version                        int64              `json:"version"`
}

type CryptoConversionRequest struct {
	CustomerReference string             `json:"customer_reference"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       string             `json:"request_hash"`
	ConversionID      pgtype.UUID        `json:"conversion_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CryptoCustomerProfile struct {
	CustomerReference   string             `json:"customer_reference"`
	PaperAccountID      pgtype.UUID        `json:"paper_account_id"`
	CashLedgerAccountID pgtype.UUID        `json:"cash_ledger_account_id"`
	PolicyVersion       string             `json:"policy_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Version             int64              `json:"version"`
}

type CryptoDeposit struct {
	ID                    pgtype.UUID        `json:"id"`
	CustomerReference     string             `json:"customer_reference"`
	DepositAddressID      pgtype.UUID        `json:"deposit_address_id"`
	AssetSymbol           string             `json:"asset_symbol"`
	NetworkCode           string             `json:"network_code"`
	Quantity              money.Decimal      `json:"quantity"`
	Status                string             `json:"status"`
	Provider              string             `json:"provider"`
	ProviderTransactionID string             `json:"provider_transaction_id"`
	LedgerTransactionID   pgtype.UUID        `json:"ledger_transaction_id"`
	ReasonCode            pgtype.Text        `json:"reason_code"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Version               int64              `json:"version"`
}

type CryptoDepositAddress struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	AssetSymbol       string             `json:"asset_symbol"`
	NetworkCode       string             `json:"network_code"`
	Provider          string             `json:"provider"`
	ExternalAddress   string             `json:"external_address"`
	Memo              pgtype.Text        `json:"memo"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CryptoDepositAddressRequest struct {
	CustomerReference string             `json:"customer_reference"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       string             `json:"request_hash"`
	DepositAddressID  pgtype.UUID        `json:"deposit_address_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CryptoFill struct {
	ID             pgtype.UUID        `json:"id"`
	ChildOrderID   pgtype.UUID        `json:"child_order_id"`
	VenueCode      string             `json:"venue_code"`
	ExternalFillID string             `json:"external_fill_id"`
	Quantity       money.Decimal      `json:"quantity"`
	Price          money.Decimal      `json:"price"`
	GrossUsd       money.Decimal      `json:"gross_usd"`
	VenueFeeUsd    money.Decimal      `json:"venue_fee_usd"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Every leg is quoted and settled only in USD. Cross-asset conversions require two explicit rows.
type CryptoLeg struct {
	ID                    pgtype.UUID        `json:"id"`
	ConversionID          pgtype.UUID        `json:"conversion_id"`
	LegSequence           int16              `json:"leg_sequence"`
	Side                  string             `json:"side"`
	AssetSymbol           string             `json:"asset_symbol"`
	QuoteCurrency         string             `json:"quote_currency"`
	InputAmount           money.Decimal      `json:"input_amount"`
	FilledQuantity        money.Decimal      `json:"filled_quantity"`
	ReferencePrice        money.Decimal      `json:"reference_price"`
	AverageExecutionPrice money.Decimal      `json:"average_execution_price"`
	GrossUsd              money.Decimal      `json:"gross_usd"`
	VenueFeeUsd           money.Decimal      `json:"venue_fee_usd"`
	PlatformFeeUsd        money.Decimal      `json:"platform_fee_usd"`
	FinalCustomerUsd      money.Decimal      `json:"final_customer_usd"`
	PriceImprovementUsd   money.Decimal      `json:"price_improvement_usd"`
	Status                string             `json:"status"`
	FailureCode           pgtype.Text        `json:"failure_code"`
	LedgerTransactionID   pgtype.UUID        `json:"ledger_transaction_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type CryptoPolicy struct {
	PolicyVersion string `json:"policy_version"`
	// Explicit, versioned simulator fee. Production fees require approved configuration.
	PlatformFeeRate             money.Decimal      `json:"platform_fee_rate"`
	ConversionReviewSingleUsd   money.Decimal      `json:"conversion_review_single_usd"`
	ConversionReviewRollingUsd  money.Decimal      `json:"conversion_review_rolling_usd"`
	ConversionReviewWindowDays  int32              `json:"conversion_review_window_days"`
	AddressCoolingBaseHours     int32              `json:"address_cooling_base_hours"`
	AddressCoolingDeviceHours   int32              `json:"address_cooling_device_hours"`
	AddressCoolingSecurityHours int32              `json:"address_cooling_security_hours"`
	AddressCoolingRecoveryHours int32              `json:"address_cooling_recovery_hours"`
	AddressCoolingMaxHours      int32              `json:"address_cooling_max_hours"`
	QuoteMaxAgeSeconds          int32              `json:"quote_max_age_seconds"`
	EffectiveAt                 pgtype.Timestamptz `json:"effective_at"`
	Active                      bool               `json:"active"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

// Immutable custody callback inbox. Providers cannot write Ledger balances directly.
type CryptoProviderEvent struct {
	Provider        string             `json:"provider"`
	ExternalEventID string             `json:"external_event_id"`
	ResourceType    string             `json:"resource_type"`
	ResourceID      pgtype.UUID        `json:"resource_id"`
	EventType       string             `json:"event_type"`
	PayloadHash     string             `json:"payload_hash"`
	DomainRecordID  pgtype.UUID        `json:"domain_record_id"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

type CryptoReconciliationRun struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	AssetSymbol       string             `json:"asset_symbol"`
	LedgerAmount      money.Decimal      `json:"ledger_amount"`
	CustodyAmount     money.Decimal      `json:"custody_amount"`
	Difference        money.Decimal      `json:"difference"`
	Status            string             `json:"status"`
	ComplianceCaseID  pgtype.UUID        `json:"compliance_case_id"`
	PolicyVersion     string             `json:"policy_version"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type CryptoVenue struct {
	VenueCode   string             `json:"venue_code"`
	DisplayName string             `json:"display_name"`
	Mode        string             `json:"mode"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CryptoWithdrawal struct {
	ID                               pgtype.UUID        `json:"id"`
	CustomerReference                string             `json:"customer_reference"`
	WithdrawalAddressID              pgtype.UUID        `json:"withdrawal_address_id"`
	AssetSymbol                      string             `json:"asset_symbol"`
	NetworkCode                      string             `json:"network_code"`
	Quantity                         money.Decimal      `json:"quantity"`
	Status                           string             `json:"status"`
	ReasonCode                       string             `json:"reason_code"`
	NextAction                       string             `json:"next_action"`
	Provider                         string             `json:"provider"`
	ProviderWithdrawalID             string             `json:"provider_withdrawal_id"`
	ReservationLedgerTransactionID   pgtype.UUID        `json:"reservation_ledger_transaction_id"`
	BroadcastLedgerTransactionID     pgtype.UUID        `json:"broadcast_ledger_transaction_id"`
	ReservationReversalTransactionID pgtype.UUID        `json:"reservation_reversal_transaction_id"`
	BroadcastReversalTransactionID   pgtype.UUID        `json:"broadcast_reversal_transaction_id"`
	PolicyVersion                    string             `json:"policy_version"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                        pgtype.Timestamptz `json:"updated_at"`
	Version                          int64              `json:"version"`
}

type CryptoWithdrawalAddress struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerReference string             `json:"customer_reference"`
	AssetSymbol       string             `json:"asset_symbol"`
	NetworkCode       string             `json:"network_code"`
	ExternalAddress   string             `json:"external_address"`
	Label             string             `json:"label"`
	Status            string             `json:"status"`
	RiskLevel         string             `json:"risk_level"`
	CoolingUntil      pgtype.Timestamptz `json:"cooling_until"`
	CoolingReason     string             `json:"cooling_reason"`
	PolicyVersion     string             `json:"policy_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Version           int64              `json:"version"`
}

type CryptoWithdrawalAddressEvent struct {
	ID         pgtype.UUID        `json:"id"`
	AddressID  pgtype.UUID        `json:"address_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	ActorType  string             `json:"actor_type"`
	ActorID    string             `json:"actor_id"`
	ReasonCode string             `json:"reason_code"`
	Metadata   []byte             `json:"metadata"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type CryptoWithdrawalAddressRequest struct {
	CustomerReference string             `json:"customer_reference"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       string             `json:"request_hash"`
	AddressID         pgtype.UUID        `json:"address_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CryptoWithdrawalRequest struct {
	CustomerReference string             `json:"customer_reference"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       string             `json:"request_hash"`
	WithdrawalID      pgtype.UUID        `json:"withdrawal_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
