// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/KDTikkly/Cytisus/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteConversion(ctx context.Context, arg CompleteConversionParams) (CryptoConversion, error)
	CreateConversion(ctx context.Context, arg CreateConversionParams) (CryptoConversion, error)
	CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CryptoCustomerProfile, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (CryptoDeposit, error)
	CreateDepositAddress(ctx context.Context, arg CreateDepositAddressParams) (CryptoDepositAddress, error)
	CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (CryptoReconciliationRun, error)
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (CryptoWithdrawal, error)
	CreateWithdrawalAddress(ctx context.Context, arg CreateWithdrawalAddressParams) (CryptoWithdrawalAddress, error)
	GetActivePolicy(ctx context.Context) (CryptoPolicy, error)
	GetAsset(ctx context.Context, symbol string) (CryptoAsset, error)
	GetAssetLedgerAccounts(ctx context.Context, arg GetAssetLedgerAccountsParams) (CryptoAssetLedgerAccount, error)
	GetAssetNetwork(ctx context.Context, arg GetAssetNetworkParams) (CryptoAssetNetwork, error)
	GetConversion(ctx context.Context, id pgtype.UUID) (CryptoConversion, error)
	GetConversionForUpdate(ctx context.Context, id pgtype.UUID) (CryptoConversion, error)
	GetConversionRequest(ctx context.Context, arg GetConversionRequestParams) (CryptoConversionRequest, error)
	GetCustomerProfile(ctx context.Context, customerReference string) (CryptoCustomerProfile, error)
	GetCustomerProfileForUpdate(ctx context.Context, customerReference string) (CryptoCustomerProfile, error)
	GetDeposit(ctx context.Context, id pgtype.UUID) (CryptoDeposit, error)
	GetDepositAddress(ctx context.Context, id pgtype.UUID) (CryptoDepositAddress, error)
	GetDepositAddressByAssetNetwork(ctx context.Context, arg GetDepositAddressByAssetNetworkParams) (CryptoDepositAddress, error)
	GetDepositAddressRequest(ctx context.Context, arg GetDepositAddressRequestParams) (CryptoDepositAddressRequest, error)
	GetPolicy(ctx context.Context, policyVersion string) (CryptoPolicy, error)
	GetProviderEvent(ctx context.Context, arg GetProviderEventParams) (CryptoProviderEvent, error)
	GetWithdrawal(ctx context.Context, id pgtype.UUID) (CryptoWithdrawal, error)
	GetWithdrawalAddress(ctx context.Context, id pgtype.UUID) (CryptoWithdrawalAddress, error)
	GetWithdrawalAddressForUpdate(ctx context.Context, id pgtype.UUID) (CryptoWithdrawalAddress, error)
	GetWithdrawalAddressRequest(ctx context.Context, arg GetWithdrawalAddressRequestParams) (CryptoWithdrawalAddressRequest, error)
	GetWithdrawalForUpdate(ctx context.Context, id pgtype.UUID) (CryptoWithdrawal, error)
	GetWithdrawalRequest(ctx context.Context, arg GetWithdrawalRequestParams) (CryptoWithdrawalRequest, error)
	InsertAssetLedgerAccounts(ctx context.Context, arg InsertAssetLedgerAccountsParams) (CryptoAssetLedgerAccount, error)
	InsertChildOrder(ctx context.Context, arg InsertChildOrderParams) (CryptoChildOrder, error)
	InsertConversionRequest(ctx context.Context, arg InsertConversionRequestParams) (pgtype.UUID, error)
	InsertDepositAddressRequest(ctx context.Context, arg InsertDepositAddressRequestParams) (pgtype.UUID, error)
	InsertFill(ctx context.Context, arg InsertFillParams) (CryptoFill, error)
	InsertLeg(ctx context.Context, arg InsertLegParams) (CryptoLeg, error)
	InsertProviderEvent(ctx context.Context, arg InsertProviderEventParams) (CryptoProviderEvent, error)
	InsertWithdrawalAddressEvent(ctx context.Context, arg InsertWithdrawalAddressEventParams) (CryptoWithdrawalAddressEvent, error)
	InsertWithdrawalAddressRequest(ctx context.Context, arg InsertWithdrawalAddressRequestParams) (pgtype.UUID, error)
	InsertWithdrawalRequest(ctx context.Context, arg InsertWithdrawalRequestParams) (pgtype.UUID, error)
	ListAssetNetworks(ctx context.Context, assetSymbol string) ([]ListAssetNetworksRow, error)
	ListAssets(ctx context.Context) ([]CryptoAsset, error)
	ListChildOrders(ctx context.Context, conversionID pgtype.UUID) ([]CryptoChildOrder, error)
	ListConversions(ctx context.Context, arg ListConversionsParams) ([]CryptoConversion, error)
	ListDepositAddresses(ctx context.Context, customerReference string) ([]CryptoDepositAddress, error)
	ListDeposits(ctx context.Context, arg ListDepositsParams) ([]CryptoDeposit, error)
	ListFills(ctx context.Context, conversionID pgtype.UUID) ([]CryptoFill, error)
	ListLegs(ctx context.Context, conversionID pgtype.UUID) ([]CryptoLeg, error)
	ListPortfolioBalances(ctx context.Context, customerReference string) ([]ListPortfolioBalancesRow, error)
	ListVenues(ctx context.Context) ([]CryptoVenue, error)
	ListWithdrawalAddresses(ctx context.Context, customerReference string) ([]CryptoWithdrawalAddress, error)
	ListWithdrawals(ctx context.Context, arg ListWithdrawalsParams) ([]CryptoWithdrawal, error)
	SumRecentCryptoToUSD(ctx context.Context, arg SumRecentCryptoToUSDParams) (money.Decimal, error)
	TransitionWithdrawal(ctx context.Context, arg TransitionWithdrawalParams) (CryptoWithdrawal, error)
	TransitionWithdrawalAddress(ctx context.Context, arg TransitionWithdrawalAddressParams) (CryptoWithdrawalAddress, error)
}

var _ Querier = (*Queries)(nil)
